### PR TITLE
xDscWebService: FIX The IIS apppool account and credentials cannot be set and fixing some bugs from PR #614

### LINKED ISSUE #463: xDscWebService: The IIS apppool account and credentials cannot be set
#### Details of the scenario you tried and the problem that is occurring

It is not possible to define the IIS Application Pool account. This is a problem if an SQL database to be used for the DSC Pull Server is not installed on the same computer. Then the application pool account must authenticate itself to the SQL Server database via the network. This is an issue for the "Local System" Account which is used as the account to run the IIS Application Pool.

#### Verbose logs showing the problem

N/A

#### Suggested solution to the issue

Adding a `Credential` parameter to the  `xDscWebService` like with the `xWebAppPool` resource from `xWebAdministration`. (https://github.com/PowerShell/xWebAdministration#xwebapppool). Another option would be to allow to specify the application poolname to be used. In this scenario the deepolyment of `xDscWebService` can be combined with `xWebAppPool` so that at first the appool is created which is then referenced by its name in `xDscWebService`. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

N/A 

#### The operating system the target node is running

N/A

#### Version and build of PowerShell the target node is running

N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
```Powershell
ResourceType  : MSFT_xDSCWebService
Name          : xDSCWebService
FriendlyName  : xDSCWebService
Module        : xPSDesiredStateConfiguration
ModuleName    : xPSDesiredStateConfiguration
Version       : 8.4.0.0
Path          : C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\8.4.0.0\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1
ParentPath    : C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\8.4.0.0\DSCResources\MSFT_xDSCWebService
ImplementedAs : PowerShell
CompanyName   : Microsoft Corporation
```

### PR DESCRIPTION
**Pull request by tmeckel**
#### Pull Request (PR) description
This PR contains a fix for issue #463 where the IIS application pool account cannot be set for a DSC Pull Server.

#### This Pull Request (PR) fixes the following issues
- Fixes #463 
- Fixes some bugs introduced with PR #614

#### Task list

This PR is currently marked as draft because work isn't finished yet. The following task list will be updated.

- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as
      appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/613)

### CODE REVIEW

**Comment by tmeckel** [comment]
@mhendric @PlagueHO @johlju the PR is now ready. Would be nice if one of you guys would do a review.

Some additional remarks about this PR. Aside the actual reason for this PR to have issue #463 fixed, I took the chance to expand the test coverage for **xDscWebService**. Especially the new code paves the way for more indepth unit testing of the resource because I removed the mock `New-PSWSEndpoint` which limits the unit tests to the **xDscWebService** resource itsself and not to the existing submodules which do the actual work and have never been under unit testing up to now. 

While working on the enahncement of the testing for **xDscWebService** I discovered some bugs that I introduced with PR #614, which @mhendric already merged into DEV. So I think before we can release another version of **xPSDesiredStateConfiguration* we should get this PR merged so that those bugs get fixed.

To prevent any regressions on the handling of the firewall and application pool features of  xDscWebService  I added additional integration tests, which now passes successfully with this PR.

**Comment by johlju** [comment]
@tmeckel I have some time now again, I will continue with the review. I have long days at the day job, so I don't have a lot of time to put in reviewing this week. :)

**Comment by johlju** [comment]
Almost half way through now at least.

**Comment by tmeckel** [comment]
> @tmeckel I have some time now again, I will continue with the review. I have long days at the day job, so I don't have a lot of time to put in reviewing this week. :)

Hi @johlju thanks for tanking the time to do the review on my PR. I appreciate this a lot! I think most people here who contribute on DSC do it their spare times. So I fully understand that often there's not enough time aside the normal (inlcuding family) duties to have PR reviewed and stuff.

**Comment by tmeckel** [comment]
> Almost half way through now at least.

Oh oh :-D I'm afraid this isn't going to end well for me. *LOL*

**Comment by johlju** [comment]
@mhendric @PlagueHO can anyone of you look at this and merge it? This looks good to me as far as I can see.

**Comment by PlagueHO** [comment]
@johlju - will get onto this tonight unless @mhendric gets there first! :grin:

**Comment by PlagueHO** [comment]
On this now.

**Comment by tmeckel** [comment]
Hey @PlagueHO I'll go through your comments later this afternoon. 
And yes you blame me here for the old code I only copied around **LOL** :stuck_out_tongue_winking_eye:

**Comment by tmeckel** [comment]
> 
> 
> Hi @mhendric, great stuff! I did comment on a lot of code that you didn't change, sorry about that. But 
>

And Mike (@mhendric ) gonna take the credit now? :laughing: :laughing: :laughing:

**Comment by tmeckel** [comment]
Hey @PlagueHO I think I worked through everything you put on the list. Was this some kinda test to check how easily I get frustrated?  *ROFL* :laughing: :laughing: :laughing:

**Comment by tmeckel** [comment]
> Sorry about all the nitpicks 😁 I may have been a bit OCD! And you passed the test! 🤣
> 

Happy that I passed the test!! 🤣 And that we finally got the PR out the door in time before Katie @kwirkykat is preparing the new release!

**Pull request merged**
