### PR TITLE
xPackage: updated conditional statement to -ne to provide correct verbose output (fixes #446)

### LINKED ISSUE #446: xPackage: incorrect verbose message "Product installation cannot be determined" due to bug in conditional statement
#### Details of the scenario you tried and the problem that is occurring

Hello all, I was working on a partial configuration using the xPackage Resource within xPSDesiredStateConfiguration and noticed incorrect output in the verbose statement due to an error in the conditional statement. It's a quick fix, the logic should be *not equal to* rather than *equal to* like the next set of logic below in the xPackage resource. This will result in proper *ProductIsProduct* validation and return the *$productEntry* rather than "Product installation cannot be determined".

#### Verbose logs showing the problem

```powershell
# Verbose output from running the xPackage Resource

VERBOSE: [VmName]: LCM:  [ Start  Resource ]  [[xPackage]FileName]
VERBOSE: [VmName]: LCM:  [ Start  Test     ]  [[xPackage]FileName]
VERBOSE: [VmName]:                            [[xPackage]FileName] The path extension was .exe
VERBOSE: [VmName]:                            [[xPackage]FileName] Parsing XXX-XXXX-XXX-XXXX-XXXXX as an identifyingNumber
VERBOSE: [VmName]:                            [[xPackage]FileName] Parsed XXX-XXXX-XXX-XXXX-XXXXX as {XXX-XXXX-XXX-XXXX-XXXXX}
VERBOSE: [VmName]:                            [[xPackage]FileName] Ensure is Present
VERBOSE: [VmName]:                            [[xPackage]FileName] Product installation cannot be determined
VERBOSE: [VmName]:                            [[xPackage]FileName] product as boolean is True
VERBOSE: [VmName]:                            [[xPackage]FileName] The package FileName is installed
VERBOSE: [VmName]: LCM:  [ End    Test     ]  [[xPackage]FileName] True in 0.1090 seconds.
VERBOSE: [VmName]: LCM:  [ End    Resource ]  [[xPackage]FileName]

```
#### Suggested solution to the issue

Current code within conditional statement

```powershell
# Lines 793-800 within xPackage Resource

    if ($null -eq $productEntry)
    {
        Write-Verbose -Message ($script:localizedData.ProductIsProduct -f $productEntry)
    }
    else
    {
        Write-Verbose -Message 'Product installation cannot be determined'
    }
```

Proposed code within conditional statement

```powershell
# Change '-eq' to '-ne' on Line 793 within xPackage Resource

    if ($null -ne $productEntry)
    {
        Write-Verbose -Message ($script:localizedData.ProductIsProduct -f $productEntry)
    }
    else
    {
        Write-Verbose -Message 'Product installation cannot be determined'
    }

```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell


# Example Partial Configuration Script (removed specifics)

        xPackage FileName
        {
            Ensure     = 'Present'
            Name       = 'FileName'
            Path       = "C:\Temp\FileBinary.exe"
            ProductId  = 'XXX-XXXX-XXX-XXXX-XXXXX'
            Arguments  = '/q'
        }

# Lines 761-832 within xPackage Resource

    Assert-PathExtensionValid -Path $Path
    $uri = Convert-PathToUri -Path $Path
    $identifyingNumber = $null

    if (-not [String]::IsNullOrEmpty($ProductId))
    {
        $identifyingNumber = Convert-ProductIdToIdentifyingNumber -ProductId $ProductId
    }

    $getProductEntryParameters = @{
        Name = $Name
        IdentifyingNumber = $identifyingNumber
    }

    $checkRegistryValueParameters = @{
        CreateCheckRegValue = $CreateCheckRegValue
        InstalledCheckRegHive = $InstalledCheckRegHive
        InstalledCheckRegKey = $InstalledCheckRegKey
        InstalledCheckRegValueName = $InstalledCheckRegValueName
        InstalledCheckRegValueData = $InstalledCheckRegValueData
    }

    if ($CreateCheckRegValue)
    {
        Assert-RegistryParametersValid -InstalledCheckRegKey $InstalledCheckRegKey -InstalledCheckRegValueName $InstalledCheckRegValueName -InstalledCheckRegValueData $InstalledCheckRegValueData
        $getProductEntryParameters += $checkRegistryValueParameters
    }

    $productEntry = Get-ProductEntry @getProductEntryParameters

    Write-Verbose -Message ($script:localizedData.EnsureIsEnsure -f $Ensure)

    if ($null -eq $productEntry)
    {
        Write-Verbose -Message ($script:localizedData.ProductIsProduct -f $productEntry)
    }
    else
    {
        Write-Verbose -Message 'Product installation cannot be determined'
    }

    Write-Verbose -Message ($script:localizedData.ProductAsBooleanIs -f [Boolean]$productEntry)

    if ($null -ne $productEntry)
    {
        if ($CreateCheckRegValue)
        {
            Write-Verbose -Message ($script:localizedData.PackageAppearsInstalled -f $Name)
        }
        else
        {
            $displayName = Get-LocalizedRegistryKeyValue -RegistryKey $productEntry -ValueName 'DisplayName'
            Write-Verbose -Message ($script:localizedData.PackageAppearsInstalled -f $displayName)
        }
    }
    else
    {
        $displayName = $null

        if (-not [String]::IsNullOrEmpty($Name))
        {
            $displayName = $Name
        }
        else
        {
            $displayName = $ProductId
        }

        Write-Verbose -Message ($script:localizedData.PackageDoesNotAppearInstalled -f $displayName)
    }

    return ($null -ne $productEntry -and $Ensure -eq 'Present') -or ($null -eq $productEntry -and $Ensure -eq 'Absent')
```

#### The operating system the target node is running

OsName: | Microsoft Windows Server 2016 Standard
-- | --
OsOperatingSystemSKU: | StandardServerEdition
OsArchitecture: | 64-bit
WindowsBuildLabEx: | 14393.0.amd64fre.rs1_release.160715-1616
OsLanguage: | en-US
OsMuiLanguages: | {en-US}

#### Version and build of PowerShell the target node is running

Name | Value
-- | --
---- | -----
PSVersion | 5.1.14393.0
PSEdition | Desktop
PSCompatibleVersions | {1.0, 2.0, 3.0, 4.0…}
BuildVersion | 10.0.14393.0
CLRVersion | 4.0.30319.42000
WSManStackVersion | 3
PSRemotingProtocolVersion | 2.3
SerializationVersion | 1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

xPSDesiredStateConfiguration 8.3.0.0

### PR DESCRIPTION
**Pull request by harnsin**
#### Pull Request (PR) description

Fixes conditional statement for verbose output specifically on Line 793 in the xPackage resource to fix bug found while debugging.

#### This Pull Request (PR) fixes the following issues

- Fixes #446 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/447)

### CODE REVIEW

**Comment by mhendric** [comment]
I've reviewed this change. The suggested changes look good to me, and the failing Integration tests look completely unrelated to this change. Furthermore, all Integration and Unit that tests related to code in MSFT_xPackageResource are still passing. I recommend that this PR be allowed to be merged.

**Comment by mhendric** [comment]
Hi @harnsin . Sorry for the extremely late responses on this. The failures with continuous integration should be resolved now. Can you rebase this PR and submit again? Hopefully it will pass and we can get this checked in. Thanks!

https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by mhendric** [comment]
FYI, I updated the README to move the unreleased statement to the actual Unreleased section (it was under 8.5.0.0). @PlagueHO or @johlju , can one of you give this a re-review? Thanks.

**Comment by PlagueHO** [comment]
Should be good to go @mhendric once the AppVeyor finishes. Great stuff - love how these are all getting knocked off!

**Comment by mhendric** [comment]
Looks like this one may actually be failing due to this change (although I'm not yet sure how). I'm going to resolve conflicts and kick of another build. If this fails again, we'll need to troubleshoot

```
[00:19:41] Executing script C:\projects\xpsdesiredstateconfiguration\Tests\Integration\MSFT_xWindowsPackageCab.Integration.Tests.ps1
[00:19:53]   [-] Error occurred in test script 'C:\projects\xpsdesiredstateconfiguration\Tests\Integration\MSFT_xWindowsPackageCab.Integration.Tests.ps1' 0ms
[00:19:53]     RemoteException: fatal: unable to access 'https://github.com/PowerShell/DscResource.Tests/': Could not resolve host: github.com
[00:19:53]     at Enter-DscResourceTestEnvironment, C:\projects\xpsdesiredstateconfiguration\Tests\CommonTestHelper.psm1: line 748
[00:19:53]     at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Integration\MSFT_xWindowsPackageCab.Integration.Tests.ps1: line 3
[00:19:53]     at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\4.6.0\Pester.psm1: line 1095
[00:19:53]     at Invoke-Pester<End>, C:\Program Files\WindowsPowerShell\Modules\Pester\4.6.0\Pester.psm1: line 1121
[00:19:53]     at Invoke-AppveyorTestScriptTask, C:\projects\xpsdesiredstateconfiguration\DscResource.Tests\AppVeyor.psm1: line 792
```

**Comment by mhendric** [comment]
Hmmmmm. The next CI run failed again, but in a different test. The error is similar though; it was unable to connect to GitHub for some reason. Sounds like something we may want to track in an attempt to make tests in this module for resilient. I can't see how the below error is realated to this particular change, but I would really like to see a successful CI run before we check this in. Thoughts?

```
[00:22:55] Executing script C:\projects\xpsdesiredstateconfiguration\Tests\Integration\MSFT_xWindowsFeature.Integration.Tests.ps1
[00:22:56]   [-] Error occurred in test script 'C:\projects\xpsdesiredstateconfiguration\Tests\Integration\MSFT_xWindowsFeature.Integration.Tests.ps1' 0ms
[00:22:56]     RemoteException: fatal: unable to access 'https://github.com/PowerShell/DscResource.Tests/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
[00:22:56]     at Enter-DscResourceTestEnvironment, C:\projects\xpsdesiredstateconfiguration\Tests\CommonTestHelper.psm1: line 748
[00:22:56]     at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Integration\MSFT_xWindowsFeature.Integration.Tests.ps1: line 16
[00:22:56]     at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\4.6.0\Pester.psm1: line 1095
[00:22:56]     at Invoke-Pester<End>, C:\Program Files\WindowsPowerShell\Modules\Pester\4.6.0\Pester.psm1: line 1121
[00:22:56]     at Invoke-AppveyorTestScriptTask, C:\projects\xpsdesiredstateconfiguration\DscResource.Tests\AppVeyor.psm1: line 792
```

**Comment by mhendric** [comment]
...hey and look at that, the tests passed this time! Better merge before it changes its mind :).

**Comment by mhendric** [comment]
Yeah, I think it was a temporary glitch. Hopefully whatever comes out of #505 will make it less likely for that to happen in the future.

**Comment by harnsin** [comment]
Appreciate the help all @mhendric @johlju @PlagueHO!

**Pull request merged**
