### PR TITLE
Update the license

### PR DESCRIPTION
**Pull request by RDIL**
#### Pull Request (PR) description
It isn't 2015 any more

#### This Pull Request (PR) fixes the following issues

N/A

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as
      appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/593)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @RDIL,

In the other DSC Resource kit repos we just remove the license year completely. See:
https://github.com/PowerShell/PSDscResources/blob/dev/LICENSE

So perhaps just use that format instead?

'Copyright (c) Microsoft Corporation. All rights reserved.'

**Comment by RDIL** [comment]
@PlagueHO fixed everything

**Comment by mhendric** [comment]
Hi @RDIL , looks like this one still needs an entry in the CHANGELOG.md. Also, you may need to do a rebase on this one to get it current.  https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by RDIL** [comment]
Yes I'm aware how to rebase

**Pull request closed without merging**
