### PR TITLE
xRemoteFile: Added Checksum support - Issue423

### LINKED ISSUE #423: xRemoteFile does not support Checksum
xRemoteFile doesn't have a way to specify a checksum for a remotely downloaded file.

### PR DESCRIPTION
**Pull request by limiteddenial**
#### Pull Request (PR) description

Adds Checksum support for the xRemoteFile resource

#### This Pull Request (PR) fixes the following issues
 - Fixes #423 

#### Task list

- [ x ] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [ x ] Resource documentation added/updated in README.md.
- [ x ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ x ] Comment-based help added/updated.
- [ x ] Localization strings added/updated in all localization files as
      appropriate.
- [ x ] Examples appropriately added/updated.
- [ x ] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ x ] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ x ] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/648)

### CODE REVIEW

**Comment by mhendric** [comment]
Sorry @limiteddenial , I forgot to flag this for follow up. Reviewable is giving me some grief this morning, but I have now flagged this, and will finish up the review ASAP.

**Comment by PavelPikat** [comment]
Can this be merged to master please?

**Comment by mhendric** [comment]
Tagging @PlagueHO or @johlju for assistance, as I'm not sure what the new merge process is.

**Comment by PlagueHO** [comment]
Hi @mhendric - we can merge it, but it can't be released until we've updated the module to the new CI/Release process. @johlju has put some great instructions together for this and I'll be implementing them on this module shortly (I'm just learning the process on WSManDsc). You can see the process here if you want to give it a go: https://gist.github.com/johlju/2ad77aa574aa07d3e9953fe86007731c

**Pull request merged**
