### PR TITLE
xServiceResource: Fixed state test #141

### PR DESCRIPTION
**Pull request by gigi81**

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @gigi81 - can you please add an entry for this fix to readme.md in the Unreleased section? Other than that, :LGTM:

<details><summary><i>Previously, msftclas (Microsoft Contribution License Agreements) wrote…</i></summary>
> Hi __@gigi81__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
> 
>     <span>
> 
>         This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
> 
>     </span>
> 
> 
> 
> TTYL, MSBOT;
> 
> 
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/145#-:-KJYlYw6HxODYmYVnL8G:-277969899)*

**Comment by gigi81** [comment]
Hi,
I updated the readme as tequested. Not sure why appveyor is failing (no code changes), seems like it's not working for some reason. Last build is from 4 days ago:
https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/history

**Comment by kwirkykat** [comment]
Re-ran the tests. They passed. Only looks like a fail because some other resources aren't passing PSSA.

**Comment by PlagueHO** [comment]
@kwirkykat , @gigi81 - I've included a fix for this PSSA failure in PR #123. It does however depend on build 1.6.0 of PSSA which was just released. So hopefully my PR #123 will be able to be merged (I'll perform a dummy commit to check).

**Pull request merged**
