### PR TITLE
Fixes #108

### LINKED ISSUE #108: xPackage: Does not remove CreateCheckRegValue on uninstall
I have a resource configured like so:
```powershell
xPackage InstallExampleResource {
    Name = 'ExampleResource';
    ProductId = '';
    Path = $executablePath;
    Arguments = '/add "{0}"' -f $Path;
    ReturnCode = 0;
    PsDscRunAsCredential = $Credential;
    InstalledCheckRegKey = 'Software\VirtualEngine';
    InstalledCheckRegValueName = 'Example';
    InstalledCheckRegValueData = 'True';
    CreateCheckRegValue = $true;
    Ensure = 'Present';
}
```
This works as expected, i.e. the HKLM\Software\VirtualEngine\Example` is checked for existence. If it doesn't exist, the package is run/installed and the registry value created.

However, if I specify that I want the package removed with `Ensure = 'Absent'`, like this:
```powershell
xPackage RemoveExampleResource {
    Name = 'ExampleResource';
    ProductId = '';
    Path = $executablePath;
    Arguments = '/add "{0}"' -f $Path;
    ReturnCode = 0;
    PsDscRunAsCredential = $Credential;
    InstalledCheckRegKey = 'Software\VirtualEngine';
    InstalledCheckRegValueName = 'Example';
    InstalledCheckRegValueData = 'True';
    CreateCheckRegValue = $true;
    Ensure = 'Absent';
}
```
This doesn't work as expected. The first pass correctly removes the package __but the registry value isn't deleted__. The next consistency check sees the registry value, thinks the package is installed and invokes the Set-TargetResource method unnecessarily.

### PR DESCRIPTION
**Pull request by iainbrighton**
Fixes bug in xPackage where CreateCheckRegValue was not being removed when removing packages

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/109)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1, line 158 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/109#-KFw_HYp9xoIpy-d4rzb:-KFw_HYp9xoIpy-d4rzc:-698849487) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/6be71fec5d0ebfe02744e56fe215bad9c7806244/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L158)):*
Why not use the powershell registry provider
`remove-item HKLM:\SOFTWARE\Microsoft\test`
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/109)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/109)*

**Comment by iainbrighton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1, line 158 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/109#-KFw_HYp9xoIpy-d4rzb:-KJ6bfP8IbRe97H9WUln:1478314843) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/6be71fec5d0ebfe02744e56fe215bad9c7806244/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L158)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> Why not use the powershell registry provider
> `remove-item HKLM:\SOFTWARE\Microsoft\test`
> ?
</details>
No reason - just sticking to the using the same implementation as the `Set-RegistryValue` method. You want me to change it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/109)*

**Comment by kwirkykat** [comment]
@TravisEz13 Any update here?

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1, line 158 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/109#-KFw_HYp9xoIpy-d4rzb:-KJgUkgOrXzjDjHHS3uy:2144517868) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/6be71fec5d0ebfe02744e56fe215bad9c7806244/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L158)):*
<details><summary><i>Previously, iainbrighton (Iain Brighton) wrote…</i></summary>
> No reason - just sticking to the using the same implementation as the `Set-RegistryValue` method. You want me to change it?
</details>
Can you file an issue for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/109)*

**Pull request merged**
