### PR TITLE
Major overhaul to pull server validation

### PR DESCRIPTION
**Pull request by FooBartn**
$script: scopes were unnecessary
Aligned naming conventions and case structure
Added HostFQDN to get hostname with domain
No need to use $skip, the -ErrorAction Stop when no web.config is found is sufficient
Added Contexts
Removed unnecessary messages after asserts
Put more information in IT and CONTEXT sections for the user
Separated Module and Configuration tests
Fixed configuration repository check, which was just checking the Module repository twice
Enabled pull server invoke-webrequest test
Moved variables and files for tests into the upper describe BeforeAll block
Modified test for local dsc configuration manager to not use alias ( or foreach, which was unnecessary )
Created tests to validate that the mof and checksum files were actually created as intended
Fixed NoOp configuration, since it was previously not functional
Separated Update-DscConfiguration into its own test
Changed -Verbose to -Verbose:$VerbosePreference

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/268)

### CODE REVIEW

**Comment by BerheAbrha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Examples/PullServerDeploymentVerificationTest/PullServerSetupTests.ps1, line 56 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/268#-KWEaQumkeltcVVFAdtG:-KWEaQumkeltcVVFAdtH:b-kdh7kv) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/00181830ca578262f5bc7ddc2d5ec02d223c134a/Examples/PullServerDeploymentVerificationTest/PullServerSetupTests.ps1#L56)):*
> ```PowerShell
>         $DscTestMetaConfigPath = "$PSScriptRoot\PullServerSetupTestMetaConfig"
>         $DscTestConfigName = "PullServerSetUpTest"
>         $DscTestMofPath = "$DscConfigPath/$DscTestConfigName.mof"
> ```


Great improvements from the original code ! Could you please use Join-Path instead of concatenating the strings ?  you have few of those..  "$DscConfigPath/$DscTestConfigName.mof"  -> Join path $DscConfigPath $DscTestConfigName.mof

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/268)*

**Comment by FooBartn** [comment]
Of course! I'll do my absolute best to get it done today. Thanks!

**Comment by BerheAbrha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/268#-:-KWHQkthWCThG0EjkDy-:bg7igk9)*

**Comment by kwirkykat** [comment]
@FooBartn Can you please add a bullet point describing your changes under the 'Unreleased' section in the README?

**Comment by kwirkykat** [comment]
@FooBartn Nevermind. This is only a change to the example. Good to go 👍

**Pull request merged**
