### PR TITLE
Merging In-Box Package Resource with xPackage

### PR DESCRIPTION
**Pull request by kwirkykat**
This merge is part of #160.

The in-box Package resource has been changed a lot since it was originally posted on GitHub, including a change to the schema of the resource. There were also quite a few changes from the community, most of which have been retained.

There is an HTTPS test added which is currently getting skipped. It seems to have problems with the local SSL connection. The test did not work with the original community resource either. Skipping it for now so the resource can get the needed updates and tests.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/176)

### CODE REVIEW

**Comment by kwirkykat** [comment]
The new Package tests have added 50 MINUTES to the overall xPSDesiredStateConfiguration tests. :-1: This is ridiculous. Looking at the cause of the crazy time delay now to see if anything can be done about it.

**Comment by kwirkykat** [comment]
Test time reduced back down to around 5 minutes. :+1:

**Comment by brantb** [comment]
@kwirkykat I noticed that [the ability to test the installation status using a registry key](https://github.com/PowerShell/xPSDesiredStateConfiguration/commit/911c72c806ad7f8202f32c8e4abd9a6927667979#diff-995f113318a6fdab03e3d9a8071a85f0L298) (using the `InstalledCheckReg*` properties) didn't survive the merge. Are there plans to restore it at some point or is that still up in the air?

**Comment by iainbrighton** [comment]
@kwirkykat @brantb DOH! We use that feature extensively as developers do some wacky stuff with their packages. Any idea why it was dropped and can this be added back in?

**Comment by kwirkykat** [comment]
@iainbrighton @brantb These parameters are no longer in the in-box Package resource. I'm not really sure why. I can add them back into xPackage if you guys would like.

Can you guys post some tests/scripts that *should* work with these parameters added back in?

**Comment by kwirkykat** [comment]
@iainbrighton @brantb Can one of you guys please submit an issue for this if you would like the params added back in?

**Comment by iainbrighton** [comment]
@kwirkykat @brantb Done (https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/187) :smile:

**Pull request merged**
