### PR TITLE
Fix minor style issues and Update xDSCWebService to meet HQRM - Fixes #623

### LINKED ISSUE #623: xDSCWebService: Update to Meet Style Guidelines
Module doesn't meet style guidelines.

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR fixes minor style issues and also updates xDSCWebService to meet HQRM guidelines. I updated this as part of fixing the issues identified by the new rules in this PR: https://github.com/PowerShell/DscResource.Tests/pull/347

#### This Pull Request (PR) fixes the following issues

- Fixes #623

#### Task list

- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as
      appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

@mhendric - would you mind reviewing when you have a chance?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/640)

### CODE REVIEW

**Comment by mhendric** [comment]
Good work @PlagueHO ! Changes approved.

**Comment by PlagueHO** [comment]
Hi @mhendric - sorry about this, but could you mark off the files again for me? Reviewable still showing them as pending.

**Comment by mhendric** [comment]
Oops, my bad. Done!

**Comment by PlagueHO** [comment]
No worries at all @mhendric ! Thank you! :grin:

**Pull request merged**
