### PR TITLE
Test against 2012R2 and 2016

### PR DESCRIPTION
**Pull request by mgreenegit**
I am submitting this for test and consideration - this would improve the xPSDesiredStateConfiguration resource quality by testing against both Windows Server 2012R2 and Windows Server 2016 (full desktop in both cases).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/403)

### CODE REVIEW

**Comment by johlju** [comment]
@mgreenegit a good plan testing against different platforms. A test fails on the platform that wasn't tested previously, can you look at that? https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/build/6.0.1031.0/job/o9lgudehyrerixae?fullLog=true#L2901

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by mhendric** [comment]
Hey @mgreenegit (or @PlagueHO or @johlju). Any idea what this change would do to the CI run time? Would it approximately double the time it takes to do tests? Or would the separate jobs run concurrently? Per #477, we're about to hit the 60 minute AppVeyor limit, so anything which significantly increases the build time may not be good.

And per @johlju 's comment, it looks like we had a failing test that will need to be resolved. May be worth a rebase (and rebuild) now that @PlagueHO fixed a bunch of the failing tests and see if we still have issues....

**Comment by mgreenegit** [comment]
Per the build results, they run independently of each other so it shouldn't increase the build time:
https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/build/6.0.1031.0

**Comment by mhendric** [comment]
Perfect, thanks @mgreenegit . Mind doing a rebase to see if your build issue was transient, or is still an issue? And we'll ultimately need an Unreleased entry in the README for this to be checked in...

**Comment by PlagueHO** [comment]
That is a good point @johlju - we do want to make sure contributors can still run CI builds on their own free accounts.

**Comment by johlju** [comment]
Regarding sending Codecov from one job, see https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/477#issuecomment-457852345 for a suggestion.

**Comment by mhendric** [comment]
Hey and look at that! Both the CI runs passed. Magic.

**Comment by PlagueHO** [comment]
I'm good with delaying this until #477 has been addressed. It is good this will still work on free AppVeyor accounts. But these test runs will run in series, which I assume will take around 45-60 mins each, making 90-120 minutes total. I'd definitely find that painful personally.

**Comment by PlagueHO** [comment]
Haha @johlju - you are right there - as long as we don't have to watch it. :grin: but what might be nice is to enable a lighter set of tests to run in working branches, with the full suite running in PR and master/dev branches. Not worth the complexity though. I'm used to only running unit/linting during CI and then Integration/E2E during CD pipeline. But that isn't really possible here.

**Comment by PlagueHO** [comment]
Loving your info and ideas there @johlju - something we should definitely look into once we've got some time!

**Comment by johlju** [comment]
@PlagueHO Yes I've had that last bit on the todo list for some time now. :)

**Pull request closed without merging**
