### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stevebanik-ndsc**
fix typo

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/408)

### CODE REVIEW

**Comment by johlju** [comment]
First! Thank you for you contribution! :smile:  Just a minor review comment.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/408#-LB0hKTqBqnV0H2ar085:-LB0hKTrDFRVL2rqfpd8:b-b2urgs) (no related file):*
Although this change is small, please add an entry to the Unreleased section of the  change log in the README.md. This is to keep a record of the changes when a new release is made.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/408#-:-LB0hq_X-QXwlQhsuire:bc5vi8t)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 639 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/408#-LB1_7On5mmZMe4bkmgS:-LB1_7On5mmZMe4bkmgT:b-vaqovx) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/03c09c03bb267667d7bfc58a684fdcdd74a56dfc/README.md#L639)):*
> ```Markdown
> ### Unreleased
> 
> ### 8.2.0.1
> ```

We should not add version number our self here as that is done during the release. Not easy to for you to know, I'm sorry. :slightly_smiling_face:  Just add the entry directly under `### Unreleased`, like this.

```markdown
### Unreleased

* README.md: Fixed typo

### 8.2.0.0
```

Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/408)*

**Comment by stevebanik-ndsc** [comment]
Sorry about that!  Thanks for correcting.

**Comment by johlju** [comment]
@stevebanik-ndsc Just so there was no missunderstanding, I didn't update your PR, I just showed how it should look like 🙂 If you can, could you please update the PR? Thanks!

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/408#-:-LB6eEjyB2FzBAI9VYaz:bnfp4nl)*

**Comment by johlju** [comment]
@stevebanik-ndsc Everything is looks okay to me. But, seems we have a problem with AppVeyor today. It is not reporting back to GutHub that test runs is finished. We have to wait a day or so and then I will close and reopen this issue to kick off the tests again. You don't have to do anything more at this time. 🙂 

/cc @kwirkykat

**Comment by johlju** [comment]
AppVeyor has solved the problem now. Closing and directly reopening this PR to try to kick off the tests again.

**Comment by johlju** [comment]
The tests failed with a strange error that can't be caused by this PR's change. Closing and directly reopening this PR to kick off the tests again as to see if that was temporary.

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/408#-:-LBR5O6ZESu-NuC7I7MR:bnfp4nl)*

**Pull request merged**
