### PR TITLE
Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1: Fix issues with disabled feature states

### LINKED ISSUE #586: Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1: Broken on Windows Server 2019
#### Details of the scenario you tried and the problem that is occurring
Tests in 'Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1' appear to be broken (at least) on Windows Server 2019. The problem occurs when the tests try to disable a feature. On my test machine, there is a third Disabled state, DisabledWithPayloadRemoved, which these tests are not looking for.

#### Verbose logs showing the problem
Here's what my feature state looks like:
```
PS C:\Users\Administrator> $optFeatures = Get-WindowsOptionalFeature -Online
PS C:\Users\Administrator> $optFeatures | where {$_.FeatureName -like "*xps*"}


FeatureName : Printing-XPSServices-Features
State       : Enabled

FeatureName : Xps-Foundation-Xps-Viewer
State       : DisabledWithPayloadRemoved

PS C:\Users\Administrator> ($optFeatures | where {$_.FeatureName -like "*xps*"})[1].State.GetType().GetEnumNames()
Disabled
DisablePending
Enabled
EnablePending
Superseded
PartiallyInstalled
DisabledWithPayloadRemoved
```

Here's the test results:
```
Executing script C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1
WARNING: There is no operation running currently. Stop will return without any action.

  Describing xWindowsOptionalFeatureSet Integration Tests

    Context Install two valid Windows optional features
      [+] Should be able to retrieve Windows optional feature RSAT-RDS-Tools-Feature before the configuration 2ms
      [+] Should have disabled Windows optional feature RSAT-RDS-Tools-Feature before the configuration 2ms
      [+] Should be able to retrieve Windows optional feature Xps-Foundation-Xps-Viewer before the configuration 1ms
      [-] Should have disabled Windows optional feature Xps-Foundation-Xps-Viewer before the configuration 3ms
        Expected $true, but got $false.
        90:                     $windowsOptionalFeature.State -in $script:disabledStates | Should -Be $true
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1: line 90
      [-] Should compile and run configuration 17.11s
        Expected no exception to be thrown, but an exception "Enable-WindowsOptionalFeature failed. Error code = 0x800f0950" was thrown from C:\Program Files\WindowsPowerShell\Module
s\xPSDesiredStateConfiguration\Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1:98 char:21
            + ...             Start-DscConfiguration -Path $TestDrive -ErrorAction 'Sto ...
            +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
        99:                 } | Should -Not -Throw
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1: line 95
      [+] Should be able to retrieve Windows optional feature RSAT-RDS-Tools-Feature after the configuration 6ms
      [+] Should have enabled Windows optional feature RSAT-RDS-Tools-Feature after the configuration 2ms
      [+] Should be able to retrieve Windows optional feature Xps-Foundation-Xps-Viewer after the configuration 1ms
      [-] Should have enabled Windows optional feature Xps-Foundation-Xps-Viewer after the configuration 19ms
        Expected $true, but got $false.
        120:                     $windowsOptionalFeature.State -in $script:enabledStates | Should -Be $true
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1: line 120
      [+] Should have created the log file 3ms
      [+] Should have created content in the log file 3ms

    Context Uninstall two valid Windows optional features
      [+] Should be able to retrieve Windows optional feature RSAT-RDS-Tools-Feature before the configuration 2ms
      [+] Should have enabled Windows optional feature RSAT-RDS-Tools-Feature before the configuration 2ms
      [+] Should be able to retrieve Windows optional feature Xps-Foundation-Xps-Viewer before the configuration 1ms
      [-] Should have enabled Windows optional feature Xps-Foundation-Xps-Viewer before the configuration 3ms
        Expected $true, but got $false.
        166:                     $windowsOptionalFeature.State -in $script:enabledStates | Should -Be $true
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1: line 166
      [+] Should compile and run configuration 5.15s
      [+] Should be able to retrieve Windows optional feature RSAT-RDS-Tools-Feature after the confguration 2ms
      [+] Should have disabled Windows optional feature RSAT-RDS-Tools-Feature after the confguration 2ms
      [+] Should be able to retrieve Windows optional feature Xps-Foundation-Xps-Viewer after the confguration 2ms
      [-] Should have disabled Windows optional feature Xps-Foundation-Xps-Viewer after the confguration 18ms
        Expected $true, but got $false.
        196:                     $windowsOptionalFeature.State -in $script:disabledStates | Should -Be $true
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1: line 196
      [+] Should have created the log file 8ms
      [+] Should have created content in the log file 3ms
    [-] Error occurred in Describe block 0ms
      RuntimeException: The variable '$windowsOptionalFeatureName' cannot be retrieved because it has not been set.
      at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\Tests\Integration\xWindowsOptionalFeatureSet.Integration.Tests.ps1: line 51
      at Invoke-Blocks, C:\Program Files\WindowsPowerShell\Modules\Pester\4.7.1\Functions\SetupTeardown.ps1: line 144
      at Invoke-TestGroupTeardownBlocks, C:\Program Files\WindowsPowerShell\Modules\Pester\4.7.1\Functions\SetupTeardown.ps1: line 134
      at DescribeImpl, C:\Program Files\WindowsPowerShell\Modules\Pester\4.7.1\Functions\Describe.ps1: line 203
WARNING: There is no operation running currently. Stop will return without any action.
```

#### The operating system the target node is running
PS C:\>     Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')

OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PS C:\> $PSVersionTable

Name                           Value                                                                                                     
----                           -----                                                                                                     
PSVersion                      5.1.17763.316                                                                                             
PSEdition                      Desktop                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                   
BuildVersion                   10.0.17763.316                                                                                            
CLRVersion                     4.0.30319.42000                                                                                           
WSManStackVersion              3.0                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                       
SerializationVersion           1.1.0.1      

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Fixes issue where tests fail if disabled Windows Optional Features in up in a state of DisabledWithPayloadRemoved.

#### This Pull Request (PR) fixes the following issues
- Fixes #586 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as
      appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/587)

### CODE REVIEW

**Comment by mhendric** [comment]
> Reviewable status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ykuijs)
> 
> 
> CHANGELOG.md, line 27 at r1 (raw file):
> Previously, ykuijs (Yorick Kuijs) wrote…
> That was indeed a type. Good catch! Fixed.

TypO ! Not type. Typing is hard...

**Comment by mhendric** [comment]
@PlagueHO , I'll leave this one for you to merge since it's my PR and someone else did the code review. Thanks.

**Comment by PlagueHO** [comment]
Hi @ykuijs - could you resolve conflicts?

**Comment by mhendric** [comment]
@PlagueHO , I'll resolve the conflicts since it's my PR (@ykuijs just did the review). Thanks.

**Pull request merged**
