### PR TITLE
xService: Fix issue where Get-TargetResource fails if service dependency is corrupt

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Fixes issue in xService where Get-TargetResource or Test-TargetResource will throw an exception if the target service is configured with a non-existent dependency. Also refactored Get-TargetResource Unit tests.

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/448)

### CODE REVIEW

**Comment by mhendric** [comment]
As best as I can tell, the Archive related Integration tests that are failing having nothing to do with the code I'm attempting to check in. Let me know if there's anything I need to do here though.

**Comment by mhendric** [comment]
On a related topic, I noticed that there's PSDscResources module now, and the Service resource within that module also has this same issue. I'm curious how these two modules are aligned. Are changes from one of these pulled into the other on a scheduled basis? Or should I submit a separate pull request with similar changes to the PSDscResources module? Thanks.

**Comment by johlju** [comment]
@mhendric xPSDesiredStateConfiguration and PSDscResources is not pulled into either one. Both resource  modules have their own lifecycle. PSDscResources does not accept any breaking changes, and only accepts approved changes. So if you'd like, then please open an issue in PSDscResources, and then submit a PR.

**Comment by mhendric** [comment]
Thanks @johlju . I'll wait and see what the result of this pull request is and if any changes are requested, and then probably submit one to PSDscResources as well.

**Comment by johlju** [comment]
Regarding lines not getting hit in AppVeyor but all is hit locally I have seen that too. In the beginning, when we added Codecov, it behaved oddly if there was a PR that used dev as the working branch. Not sure that is the case now. It doesn’t happen often, but would be great to find the cause.

**Comment by mhendric** [comment]
>           Regarding lines not getting hit in AppVeyor but all is hit locally I have seen that too. In the beginning, when we added Codecov, it behaved oddly if there was a PR that used dev as the working branch. Not sure that is the case now. It doesn’t happen often, but would be great to find the cause.

Yeah I'm not sure what's going on here. Wonder if it's related to the test issues with xArchive for instance, where they ran fine in local builds, but failed in the AppVeyor CI run. It would be good to get to the bottom of this. Shall we try to troubleshoot that with this PR, or save it for a rainy day?

Just to show that this does in fact work in my lab, here's my lab code cov:

```
Code coverage report:
Covered 94.46% of 325 analyzed Commands in 1 File.
Missed commands:

File                       Function                     Line Command
----                       --------                     ---- -------
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight     946 $logOnAsServiceText = @"...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1293 $null = [LogOnAsServiceHelper.NativeMethods]
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1297 $logOnAsServiceText = $logOnAsServiceText.Replace('Cann...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1299 $logOnAsServiceText = $logOnAsServiceText.Replace('User...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1301 $logOnAsServiceText = $logOnAsServiceText.Replace('Cann...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1303 $logOnAsServiceText = $logOnAsServiceText.Replace('Cann...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1305 $logOnAsServiceText = $logOnAsServiceText.Replace('Cann...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1307 $logOnAsServiceText = $logOnAsServiceText.Replace('Cann...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1309 $logOnAsServiceText = $logOnAsServiceText.Replace('Cann...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1311 $null = Add-Type $logOnAsServiceText -PassThru
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1314 if ($Username.StartsWith('.\'))...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1316 $Username = $Username.Substring(2)
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1321 [LogOnAsServiceHelper.NativeMethods]::SetLogOnAsService...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1325 $errorMessage = $script:localizedData.ErrorSettingLogOn...
MSFT_xServiceResource.psm1 Grant-LogOnAsServiceRight    1326 New-InvalidOperationException -Message $errorMessage
MSFT_xServiceResource.psm1 Remove-Service               1683 & 'sc.exe' 'delete' $Name
MSFT_xServiceResource.psm1 Wait-ServiceStateWithTimeout 1776 $service = Get-Service -Name $ServiceName -ErrorAction ...
MSFT_xServiceResource.psm1 Wait-ServiceStateWithTimeout 1777 $Service.WaitForStatus($State, $WaitTimeSpan)
```

and here's the latest CI code cov (which also shows a lot of code that I didn't even touch not getting hit):

```
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Get-TargetResource                      66 Write-Warning -Message ($script:localizedData.CorruptDependency -f $Name)                                         
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Get-TargetResource                      66 $script:localizedData.CorruptDependency -f $Name                                                                  
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Get-TargetResource                      74 'NetworkService'                                                                                                  
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    489 $errorMessage = $script:localizedData.CredentialParametersAreMutallyExclusive -f $Name                            
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    490 New-InvalidArgumentException -ArgumentName 'BuiltInAccount / Credential / GroupManagedServiceAccount' -Message ...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    500 return $true                                                                                                      
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    510 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    520 Write-Verbose -Message ($script:localizedData.ServicePathDoesNotMatch -f $Name, $Path, $serviceResource.Path)     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    520 $script:localizedData.ServicePathDoesNotMatch -f $Name, $Path, $serviceResource.Path                              
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    521 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    528 Write-Verbose -Message ($script:localizedData.ServicePropertyDoesNotMatch -f 'DisplayName', $Name, $DisplayName...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    528 $script:localizedData.ServicePropertyDoesNotMatch -f 'DisplayName', $Name, $DisplayName, $serviceResource.Displ...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    529 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    535 Write-Verbose -Message ($script:localizedData.ServicePropertyDoesNotMatch -f 'Description', $Name, $Description...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    535 $script:localizedData.ServicePropertyDoesNotMatch -f 'Description', $Name, $Description, $serviceResource.Descr...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    536 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    546 $serviceDependenciesDoNotMatch = $true                                                                            
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    556 $expectedDependenciesString = $Dependencies -join ','                                                             
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    557 $actualDependenciesString = $serviceResource.Dependencies -join ','                                               
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    559 Write-Verbose -Message ($script:localizedData.ServicePropertyDoesNotMatch -f 'Dependencies', $Name, $expectedDe...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    559 $script:localizedData.ServicePropertyDoesNotMatch -f 'Dependencies', $Name, $expectedDependenciesString, $actua...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    560 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    567 Write-Verbose -Message ($script:localizedData.ServicePropertyDoesNotMatch -f 'DesktopInteract', $Name, $Desktop...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    567 $script:localizedData.ServicePropertyDoesNotMatch -f 'DesktopInteract', $Name, $DesktopInteract, $serviceResour...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    568 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    574 Write-Verbose -Message ($script:localizedData.ServicePropertyDoesNotMatch -f 'BuiltInAccount', $Name, $BuiltInA...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    574 $script:localizedData.ServicePropertyDoesNotMatch -f 'BuiltInAccount', $Name, $BuiltInAccount, $serviceResource...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    575 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    579 $expectedStartName = ConvertTo-StartName -Username $GroupManagedServiceAccount                                    
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    581 if ($serviceResource.BuiltInAccount -ine $expectedStartName)...                                                   
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    583 Write-Verbose -Message ($script:localizedData.GroupManagedServiceCredentialDoesNotMatch -f $Name, $GroupManaged...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    583 $script:localizedData.GroupManagedServiceCredentialDoesNotMatch -f $Name, $GroupManagedServiceAccount, $service...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    584 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    593 Write-Verbose -Message ($script:localizedData.ServiceCredentialDoesNotMatch -f $Name, $Credential.UserName, $se...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    593 $script:localizedData.ServiceCredentialDoesNotMatch -f $Name, $Credential.UserName, $serviceResource.BuiltInAcc...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    594 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    601 Write-Verbose -Message ($script:localizedData.ServicePropertyDoesNotMatch -f 'StartupType', $Name, $StartupType...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    601 $script:localizedData.ServicePropertyDoesNotMatch -f 'StartupType', $Name, $StartupType, $serviceResource.Start...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    602 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    608 Write-Verbose -Message ($script:localizedData.ServicePropertyDoesNotMatch -f 'State', $Name, $State, $serviceRe...
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    608 $script:localizedData.ServicePropertyDoesNotMatch -f 'State', $Name, $State, $serviceResource.State               
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Test-TargetResource                    609 return $false                                                                                                     
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Assert-NoStartupTypeStateConflict      705 $errorMessage = $script:localizedData.StartupTypeStateConflict -f $ServiceName, $StartupType, $State              
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Assert-NoStartupTypeStateConflict      706 New-InvalidArgumentException -ArgumentName 'StartupType and State' -Message $errorMessage                         
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Assert-NoStartupTypeStateConflict      709 if ($State -eq 'Stopped')...                                                                                      
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Assert-NoStartupTypeStateConflict      711 if ($StartupType -eq 'Disabled')...                                                                               
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Assert-NoStartupTypeStateConflict      714 $errorMessage = $script:localizedData.StartupTypeStateConflict -f $ServiceName, $StartupType, $State              
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Assert-NoStartupTypeStateConflict      715 New-InvalidArgumentException -ArgumentName 'StartupType and State' -Message $errorMessage                         
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        ConvertTo-StartName                    774 $startName = "NT Authority\$Username"                                                                             
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        ConvertTo-StartName                    778 $startName = ".\$Username"                                                                                        
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight              946 $logOnAsServiceText = @"...                                                                                       
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1293 $null = [LogOnAsServiceHelper.NativeMethods]                                                                      
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1297 $logOnAsServiceText = $logOnAsServiceText.Replace('CannotOpenPolicyErrorMessage', `...                            
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1299 $logOnAsServiceText = $logOnAsServiceText.Replace('UserNameTooLongErrorMessage', `...                             
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1301 $logOnAsServiceText = $logOnAsServiceText.Replace('CannotLookupNamesErrorMessage', `...                           
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1303 $logOnAsServiceText = $logOnAsServiceText.Replace('CannotOpenAccountErrorMessage', `...                           
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1305 $logOnAsServiceText = $logOnAsServiceText.Replace('CannotCreateAccountAccessErrorMessage', `...                   
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1307 $logOnAsServiceText = $logOnAsServiceText.Replace('CannotGetAccountAccessErrorMessage', `...                      
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1309 $logOnAsServiceText = $logOnAsServiceText.Replace('CannotSetAccountAccessErrorMessage', `...                      
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1311 $null = Add-Type $logOnAsServiceText -PassThru                                                                    
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1314 if ($Username.StartsWith('.\'))...                                                                                
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1316 $Username = $Username.Substring(2)                                                                                
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1321 [LogOnAsServiceHelper.NativeMethods]::SetLogOnAsServicePolicy($Username)                                          
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1325 $errorMessage = $script:localizedData.ErrorSettingLogOnAsServiceRightsForUser -f $Username, $_.Exception.Message  
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Grant-LogOnAsServiceRight             1326 New-InvalidOperationException -Message $errorMessage                                                              
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Remove-Service                        1683 & 'sc.exe' 'delete' $Name                                                                                         
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Wait-ServiceStateWithTimeout          1776 $service = Get-Service -Name $ServiceName -ErrorAction 'SilentlyContinue'                                         
[00:44:01] MSFT_xServiceResource\MSFT_xServiceResource.psm1                        Wait-ServiceStateWithTimeout          1777 $Service.WaitForStatus($State, $WaitTimeSpan)                                                                     
```

**Comment by mhendric** [comment]
...and just a thought, is it possible the Code Coverage is somehow running against a different, outdated copy of the module when run in AppVeyor?

**Comment by johlju** [comment]
I just ignored it over at SqlServerDsc even if it lowered the percentage by 1%. I figured one day when we find the cause I get that 1% back :smile:
I say, leave it for a rainy day.

**Comment by johlju** [comment]
Yes that was my thought too. It compares the result against something else than it should. Or that there is a bug in the result that is sent to Codecov. I haven’t looked into it more. :)

**Comment by mhendric** [comment]
I just opened #480 to track this issue.

**Pull request merged**
