### PR TITLE
MSFT_xDSCWebService.psm1: Applied fix for issue #460

### LINKED ISSUE #460: xDscWebService: Redeploy DSC Pull Server fails with error
#### Details of the scenario you tried and the problem that is occurring
After a successfully configuration (deployment) of a DSC Pull Server via the `xDscWebService` resource, a redepolyment after the deletion of the IIS Webapplication failes with an error.

#### Verbose logs showing the problem
```powershell
VERBOSE: [UIDEFFMIMD54SPS]:                            [[xDSCWebService]PSDSCPullServer] Pull Server: Set values into the web.config that indicate the location of repository, configuration
, modules
VERBOSE: [UIDEFFMIMD54SPS]:                            [[xDSCWebService]PSDSCPullServer] Enabling Pull Server to run in a 64 bit process
The process cannot access the file 'C:\Windows\System32\inetsrv\IISSelfSignedCertModule.dll' because it is being used by another process.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.CopyItemCommand
    + PSComputerName        : localhost
 
VERBOSE: [UIDEFFMIMD54SPS]: LCM:  [ End    Set      ]  [[xDSCWebService]PSDSCPullServer]  in 5.5680 seconds.
The PowerShell DSC resource '[xDSCWebService]PSDSCPullServer' with SourceInfo 'E:\Projects\DSC\HTTPPullServer.ps1::40::9::xDscWebService' threw one or more non-terminating errors while 
running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
```
#### Suggested solution to the issue

By looking at the implementation (https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/01383b317abae8de69a1c093ddb51b2a064f8296/DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.psm1#L451) there should be a test if the module is already added to the globalModules section of the IIS instance and if so omit the installation. The easiest way to do is querying the the globalModules section and locate the module via a regex match:

```powershell
if (-not ((& $script:appCmd list config -section:system.webServer/globalModules) -match "IISSelfSignedCertModule")) {
   ...INSTALL MODULE...
}
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell

Configuration HTTPPullServer {

    Import-DSCResource -ModuleName xPSDesiredStateConfiguration

    Node $NodeName
    {
        WindowsFeature DSCServiceFeature
        {
            Ensure = "Present"
            Name   = "DSC-Service"
        }

        xDscWebService PSDSCPullServer
        {
            Ensure                  = $State
            EndpointName            = $EndpointName
            Port                    = $Port
            PhysicalPath            = "$env:SystemDrive\inetpub\PSDSCPullServer"
            CertificateThumbPrint   = $certificateThumbPrint
            ModulePath              = "$env:PROGRAMFILES\WindowsPowerShell\DscService\Modules"
            ConfigurationPath       = "$env:PROGRAMFILES\WindowsPowerShell\DscService\Configuration"
            State                   = "Started"
            DependsOn               = "[WindowsFeature]DSCServiceFeature"
            RegistrationKeyPath     = "$env:PROGRAMFILES\WindowsPowerShell\DscService"
            AcceptSelfSignedCertificates = $true
            Enable32BitAppOnWin64   = $false
            UseSecurityBestPractices = $false
        }

        File RegistrationKeyFile
        {
            Ensure          = $State
            Type            = 'File'
            DestinationPath = "$env:ProgramFiles\WindowsPowerShell\DscService\RegistrationKeys.txt"
            Contents        = $RegistrationKey
            DependsOn       = "[WindowsFeature]DSCServiceFeature"
        }
    }
}
```

#### The operating system the target node is running

```powershell
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19125.amd64fre.winblue_ltsb.180812-0703
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
```Powershell
ResourceType  : MSFT_xDSCWebService
Name          : xDSCWebService
FriendlyName  : xDSCWebService
Module        : xPSDesiredStateConfiguration
ModuleName    : xPSDesiredStateConfiguration
Version       : 8.4.0.0
Path          : C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\8.4.0.0\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1
ParentPath    : C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\8.4.0.0\DSCResources\MSFT_xDSCWebService
ImplementedAs : PowerShell
CompanyName   : Microsoft Corporation
```

### PR DESCRIPTION
**Pull request by tmeckel**
#### Pull Request (PR) description
This Pull Request (PR) implements a fix for issue #460

#### This Pull Request (PR) fixes the following issues
-Fixes #460

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/507)

### CODE REVIEW

**Comment by mhendric** [comment]
@tmeckel , it look like this change does in fact introduce new issues in the corresponding Unit tests. Those will need to be fixed before this can be merged. Let us know if you need help troubleshooting those tests.

```
[00:31:01]   Describing MSFT_xDSCWebService\Set-TargetResource
[00:31:01] 
[00:31:01]     Context DSC Service is not installed and Ensure is Absent
[00:31:01]       [+] Should call expected mocks 196ms
[00:31:01] 
[00:31:01]     Context DSC Service is installed and Ensure is Absent
[00:31:02]       [+] Should call expected mocks 229ms
[00:31:02] 
[00:31:02]     Context Ensure is Present
[00:31:03]       [-] Should call expected mocks 550ms
[00:31:03]         RuntimeException: Mock test failed.
[00:31:03]         at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 451
[00:31:03]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 505
[00:31:03]       [-] Should create the DatabasePath directory 586ms
[00:31:03]         RuntimeException: Mock test failed.
[00:31:03]         at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 451
[00:31:03]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 533
[00:31:04]       [-] Should create the RegistrationKeyPath directory 560ms
[00:31:04]         RuntimeException: Mock test failed.
[00:31:04]         at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 451
[00:31:04]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 533
[00:31:05]       [-] Should create the ModulePath directory 563ms
[00:31:05]         RuntimeException: Mock test failed.
[00:31:05]         at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 451
[00:31:05]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 533
[00:31:05]       [-] Should create the ConfigurationPath directory 542ms
[00:31:05]         RuntimeException: Mock test failed.
[00:31:05]         at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 451
[00:31:05]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 533
[00:31:05] 
[00:31:05]     Context Ensure is Present - isDownLevelOfBlue
[00:31:06]       [-] Should call expected mocks 580ms
[00:31:06]         RuntimeException: Mock test failed.
[00:31:06]         at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 451
[00:31:06]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 553
[00:31:06] 
[00:31:06]     Context Ensure is Present - isUpLevelOfBlue
[00:31:07]       [-] Should call expected mocks 742ms
[00:31:07]         RuntimeException: Mock test failed.
[00:31:07]         at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 451
[00:31:07]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 582
[00:31:07] 
[00:31:07]     Context Ensure is Present - Enable32BitAppOnWin64
[00:31:08]       [-] Should call expected mocks 562ms
[00:31:08]         RuntimeException: Mock test failed.
[00:31:08]         at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 451
[00:31:08]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 606
[00:31:08] 
[00:31:08]     Context Ensure is Present - AcceptSelfSignedCertificates is $false
[00:31:10]       [+] Should call expected mocks 1.34s
[00:31:10] 
[00:31:10]     Context Ensure is Present - UseSecurityBestPractices is $true
[00:31:10]       [+] Should throw an error because no certificate specified 34ms
[00:31:10] 
[00:31:10]     Context Ensure is Present - CertificateSubject
[00:31:11]       [-] Should call expected mocks 618ms
[00:31:11]         RuntimeException: Mock test failed.
[00:31:11]         at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 451
[00:31:11]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 678
[00:31:11] 
[00:31:11]     Context Ensure is Present - CertificateThumbprint and UseSecurityBestPractices is $true
[00:31:12]       [-] Should not throw an error 582ms
[00:31:12]         Expected no exception to be thrown, but an exception "Mock test failed." was thrown from line:1 char:59
[00:31:12]             + ... s -notcontains $MyInvocation.Line.Trim()) {throw 'Mock test failed.'}
[00:31:12]             +                                                ~~~~~~~~~~~~~~~~~~~~~~~~~.
[00:31:12]         701:                     {Set-TargetResource @altTestParameters @setTargetPaths -Ensure Present} | Should -Not -throw
[00:31:12]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 701
[00:31:12]       [-] Should call expected mocks 42ms
[00:31:12]         Expected Set-UseSecurityBestPractices in module MSFT_xDSCWebService to be called 1 times exactly but was called 0 times
[00:31:12]         706:                     Assert-MockCalled -Exactly -Times 1 -CommandName Set-UseSecurityBestPractices
[00:31:12]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 706
[00:31:12] 
[00:31:12]     Context Function parameters contain invalid data
[00:31:13]       [+] Should throw if CertificateThumbprint and CertificateSubject are not specifed 27ms
```

Also, it looks like the encoding was changed in README.md (Notepad often does this). You can try the helper function to fix that if you like, although sometimes it gets me in more trouble than I was already in. Another option is to just revert the file to its original state, then make the change using an editor like Notepad++ which won't alter the encoding or special characters.

```
[00:02:11]     Context When repository contains markdown files
[00:02:12]       [+] Markdown file 'HighQualityResourceModulePlan.md' should not have Byte Order Mark (BOM) 32ms
[00:02:12] README.md contain Byte Order Mark (BOM). Use fixer function 'ConvertTo-ASCII'.
[00:02:12]       [-] Markdown file 'README.md' should not have Byte Order Mark (BOM) 96ms
[00:02:12]         Expected $false, but got $true.
[00:02:12]         236:                 $markdownFileHasBom | Should -Be $false
[00:02:12]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\DscResource.Tests\Meta.Tests.ps1: line 236

```

**Comment by tmeckel** [comment]
@mhendric  Seems this fix is getting a real pest now *LOL*

Anyway ... removing the BOM from the Readme.md is an easy task. I'll correct the encoding an commit the change on the PR. And yes I used notepad to add the required lines to Readme.md and I wasn't aware of the fact that notepad changed the encoding. I only know that behavior from PowershellISE.

With the failing unit tests I'm definitely a bit baffled, because the only thing what's in the PR is a check if the `IISSelfSignedCertModule` IIS module is already configured on the web application. I'll look at this ... If I can't figure out what's going on I'd like to take your offer and ask for help :-)

**Comment by mhendric** [comment]
Hey @tmeckel . This is a weird one. I've found a fix, although I'm not sure I fully understand yet why the tests were implemented this way. Essentially, in Tests\Unit\MSFT_xDSCWebService.Tests.ps1, you need to change the $allowedArgs variable from:

```
        Describe -Name "$dscResourceName\Set-TargetResource" -Fixture {

            function Get-Website {}
            function Get-WebBinding {}

            #region Mocks
            $testArguments = 'if ($allowedArgs -notcontains $MyInvocation.Line.Trim()) {throw ''Mock test failed.''}'

            $allowedArgs = @(
                '& $script:appCmd install module /name:$iisSelfSignedModuleName /image:$destinationFilePath /add:false /lock:false'
                '& $script:appCmd add module /name:$iisSelfSignedModuleName  /app.name:"PSDSCPullServer/" $preConditionBitnessArgumentFor32BitInstall'
            )
```

to

```
            $allowedArgs = @(
                '& $script:appCmd install module /name:$iisSelfSignedModuleName /image:$destinationFilePath /add:false /lock:false'
                '& $script:appCmd add module /name:$iisSelfSignedModuleName  /app.name:"PSDSCPullServer/" $preConditionBitnessArgumentFor32BitInstall'
                "if (-not ((& `$script:appCmd list config -section:system.webServer/globalModules) -match 'IISSelfSignedCertModule'))"
            )
```

**Comment by tmeckel** [comment]
@mhendric Nice catch .. I wasn't aware of this feature in Pester 👍 Learned something! But I would call this fix the 'Get the stuff running syndrome' *LOL* because this wouldn't improve the testability and the robustness of the tests, the fix only allows us to complete the PR. But if we would act often like that we would put additional technical debts in here and I'm pretty sure there're enough of them right now. 

This said my proposal would be to write three additional functions: `Test-IISSelfSignedModule`, `Add-IISSelfSignedModule`, `Remove-IISSelfSignedModule`. `Test-IISSelfSignedModule` will encapsulate the currently offending if-statement and the Add and Remove functions will enable and disable the IIS module (calling `Test-IISSelfSignedModule` internally).

If you think I'm overstating here, please say so. Then, of course, we can apply the cheap fix.

**Comment by mhendric** [comment]
@tmeckel , I totally agree! I'd much rather have a highly functional, easier to understand, well written fix, then a cheap fix. If you're willing to take that on, then by all means, go for it!

**Comment by tmeckel** [comment]
Hi @mhendric thanks for starting reviewing my PR. Actually I think it's not in a reviewable state. I admit I should've added a comment respectively or worked on another branch which doesn't push here. As you noticed I started moving code into separate functions, especially for handling of the IIS self signed module. I already moved those functions to separate (helper) modules like `PSWSIISEndpoint.psm1` but I had numerous issues with the current Pester Unit tests, e.g. I wasn't abel to get the mock `Get-Website`working in a (new) PSM1 module which only contained the functions for the IIS module. So I decided to rollback this "cleanup" and only tried to get the Unit tests succeed with minimal changes and the new functions, which are unfortunately clutter up the main module MSFT_xDSCWebService.psm1. This definitely has to be sorted! 

To be honest, while I was working on this resource, I discovered so many parts which are implemented inconsistently. The methods for the IIS module are a good example for this. Partly they use appcmd.exe to test oder modify the settings. At other edges methods from the WebAdministration modules are (implicitly) used or own support functions are written. Because of this to me it was hard to find a way through all this cleaning up the code in the `*-TargetResource` methods without breaking the Unit Tests or even the functionality. That's why all those 'Write-Verbose' messages, which I don't actually plan to leave inside the module.

**Comment by mhendric** [comment]
Hey @tmeckel , just checking if you're ready for another code review on this or not. Let me know.

Also, that's totally fine if you want to leave code cleanup for the module until later or a different PR (although newly added code, or modified code, should still follow style guidelines).

**Comment by tmeckel** [comment]
Hey @mhendric ready for an additional review. As you can see I fixed another issue that prevents the successfull configuration of a PullServer when the IIS SelfSigned module has been already loaded by IIS and is thus locked in the filesystem. 

Well there is remaining risk that the configuration will fail, when the loaded module DLL differs from the one which is located in the IIS and the PullServer directory in `$env:windir\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PullServer` but this could only happen if a system update (patch install) is done. Nevertheless the situation with this DLL is really unsatisfying. I would prefer to NOT copy the module to different directory than the installation location `$env:windir...` because this would save numbers of lines of code and more importantly the issue that I described with a patch installation won't happen anymore because wusa.exe (TiWorker) will detect that the DLL is locked and require a reboot of the server.

Secondly, because I was working on the code sequence anyway, I (hopefully) fixed issue #528 :-D

**Comment by tmeckel** [comment]
Hey @mhendric … ready for the next review :-D in addition I found and corrected an issue how the module detects the FQDN of a host. The old code relied on environment variables. The adopted the code from the uni tests which uses `[System.Net.NetworkInformation.IPGlobalProperties]::GetIPGlobalProperties()` what is much more reliable!

**Comment by mhendric** [comment]
Hey @tmeckel , I just noticed that this fixes all but one of the script analyzer errors in the Meta tests. Up to you if you want to fix that here or not, but if not, we'll need another PR for it at some point.

[00:01:09]     Context MSFT_xDSCWebService.psm1
[00:01:09]       [+] Should pass all error-level PS Script Analyzer rules 67ms
[00:01:13]       [+] Should pass all required PS Script Analyzer rules 3.87s
[00:01:14] Flagged PSSA rule(s) did not pass.
[00:01:14] The following PSScriptAnalyzer rule 'PSDSCUseVerboseMessageInDSCResource' errors need to be fixed:
[00:01:14] MSFT_xDSCWebService.psm1 (Line 23): There is no call to Write-Verbose in DSC function 'Get-TargetResource'. If you are using Write-Verbose in a helper function, suppress this rule application.
[00:01:14] For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
[00:01:14] Common Tests - Flagged Script Analyzer Rules will not fail unless you opt-in.
[00:01:14] To opt-in, create a '.MetaTestOptIn.json' at the root
[00:01:14] of the repo in the following format:
[00:01:14] [
[00:01:14]      "Common Tests - Flagged Script Analyzer Rules"
[00:01:14] ]
[00:01:14]       [+] Should pass all flagged PS Script Analyzer rules 858ms
[00:01:14]       [+] Should pass any recently-added, error-level PS Script Analyzer rules 52ms
[00:01:14]       [+] Should not suppress any required PS Script Analyzer rules 41ms
[00:01:15]       [+] Should pass all custom DSC Resource Kit PSSA rules 803ms

**Comment by mhendric** [comment]
FYI, I opened #565 to track the PSSA issue above. Somehow I missed that file when I creates Issued for the rest of the problem files.

**Comment by mhendric** [comment]
@PlagueHO or @johlju , would one of you be able to give this one a code review too? This one is big enough that it probably needs another sets of eyes on it. Thanks.

**Comment by tmeckel** [comment]
> Hey @tmeckel , I just noticed that this fixes all but one of the script analyzer errors in the Meta tests. Up to you if you want to fix that here or not, but if not, we'll need another PR for it at some point.
> 
> [00:01:09] Context MSFT_xDSCWebService.psm1
> [00:01:09] [+] Should pass all error-level PS Script Analyzer rules 67ms
> [00:01:13] [+] Should pass all required PS Script Analyzer rules 3.87s
> [00:01:14] Flagged PSSA rule(s) did not pass.
> [00:01:14] The following PSScriptAnalyzer rule 'PSDSCUseVerboseMessageInDSCResource' errors need to be fixed:
> [00:01:14] MSFT_xDSCWebService.psm1 (Line 23): There is no call to Write-Verbose in DSC function 'Get-TargetResource'. If you are using Write-Verbose in a helper function, suppress this rule application.
> [00:01:14] For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
> [00:01:14] Common Tests - Flagged Script Analyzer Rules will not fail unless you opt-in.
> [00:01:14] To opt-in, create a '.MetaTestOptIn.json' at the root
> [00:01:14] of the repo in the following format:
> [00:01:14] [
> [00:01:14] "Common Tests - Flagged Script Analyzer Rules"
> [00:01:14] ]
> [00:01:14] [+] Should pass all flagged PS Script Analyzer rules 858ms
> [00:01:14] [+] Should pass any recently-added, error-level PS Script Analyzer rules 52ms
> [00:01:14] [+] Should not suppress any required PS Script Analyzer rules 41ms
> [00:01:15] [+] Should pass all custom DSC Resource Kit PSSA rules 803ms

Hey @mhendric I'll fix those issues on the current PR.

**Comment by tmeckel** [comment]
Hey @mhendric  I changed the implementation of the unit tests. Now this looks much more reasonable, although the syntax (implementation) of the mock for `Get-Command` looks weird! But now I'm confident that the tests really do their job!

**Comment by tmeckel** [comment]
I personally would leave the mocking code for `Get-Command` inside the Units tests because this would leave us the possibility to define tests that will call a specific action list, delete etc. with the appcmd.exe and if another action is used we can fail the test. I think this is a real benefit. But as how the tests designed I agree with you that the mock implementation is pretty useless because it didn't honor different code paths which call the appcmd.exe differently. This is my point for a longer time now: the tests for the MSFT_xDSCWebService resource aren't that well designed and only test small parts of the functionality present in the  resources. But I've to admit the resource implements so many potential variations thus a thoroughly test cover takes much time and is hard to accomplish. However the bugs in issue #528 and #468 would've been easy detectable even with a flat-out test implementation.

**Comment by tmeckel** [comment]
@mhendric I rebased the PR to the current origin/dev branch but still a hint about existing conflicts is displayed. If I should do another rebase lemme know. Secondly I fixed the PSSA issue #565. Hopefully we're finally on the finishing line for this PR! Oh .. do I have to adjust the CHANGELOG.md again because I fixed #565 and #528 ?

**Comment by mhendric** [comment]
@tmeckel , also note that after you rebase, your change log entry is going to be under the 8.5.0.0 section, and will need to be moved to the Unreleased section. Thanks.

**Comment by tmeckel** [comment]
Hey @mhendric your proposal on restrcuturing the mock code for `Get-Command`sounds good and yes I didn't understand what you wanted at first place. So I gonna rebase the PR over the weekend move the comments into the Unreleased section and add two comments that this PR also resolves two other issues. I'll get back to you as soon as I've done that.

**Comment by tmeckel** [comment]
Hey @mhendric I changed the `Get-Command`mock implementation as you proposed. I added a comment though into the code because a script block must be returned which will be executed from the calling code outof the DSC Resource. I had some strange errors when I directly copied your proposal which I had to anaylze and understood :-D ... Anyway I hope we can merge this PR finally into the dev branch. When this is done I can work on the other open issues related to xDSCWebService. Oh and  I added comments to CHANGELOG.md in the unreleased section as required.

**Pull request merged**
