### PR TITLE
BREAKING CHANGE: xWindowsOptionalFeature: Update to a high quality resource (Fixes #229)

### LINKED ISSUE #229: BREAKING CHANGE: xWindowsOptionalFeature: Remove the Source parameter
**Please do not work on this issue until WindowsOptionalFeature has been merged from in-box as part of #160**

In xWindowsOptionalFeature the Source parameter is not used.
It has not been implemented, it's not mandatory, and it is not a key, so it should be removed.

### PR DESCRIPTION
**Pull request by kwirkykat**
There was nothing to merge from the in-box WindowsOptionalFeature for #160 so instead, I went ahead and updated it to a high quality resource.

PSSA is clean on MSFT_xWindowsOptionalFeature.psm1.
Pester is showing unit test coverage at 95%.
Integration tests cover main functionality.
A clearly documented example is provided.
MSFT_xWindowsOptionalFeature.psm1 meets the DSC Resource Kit style guidelines.
All documentation here on GitHub has been updated for this resource.

There is one significant change in this PR which is that the Source parameter has been removed from this resource. This fixes #229. The parameter was not implemented at all in the resource, was not mandatory, and is not a key. However, if you did provide that parameter anyways in a script, those scripts will now break. So I will still mark this as a breaking change.

I also updated the common resource helper with a function to properly import localized strings. (@PlagueHO this is a function to contain the small snippet of localization code you normally add at the beginning of files)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/237)

### CODE REVIEW

**Comment by kwirkykat** [comment]
I added a small update after testing with Set-StrictMode -Version 4 which should simulate running the resource in WMF 4.

**Comment by mbreakey3** [comment]
Reviewed 6 of 11 files at r1, 2 of 2 files at r2, 2 of 3 files at r3.
Review status: 9 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.psm1, line 90 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRp4KCFw3QsnJfaJhd9:-KRp4KCFw3QsnJfaJhdA:b-in9mml) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.psm1#L90)):*
> ```PowerShell
>     .PARAMETER LogPath
>         The path to the log file to log this operation.
>         There is not default value, but if not set, the log will appear at
> ```

'There is no default...'

---

*[DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.strings.psd1, line 4 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRpAX1C7MjeQH6ste92:-KRpAX1C7MjeQH6ste93:b-br9rcn) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.strings.psd1#L4)):*
> ```PowerShell
> 
> ConvertFrom-StringData @'
> DismNotAvailable = PowerShell module DISM could not be imported.
> ```

tab this string content in

---

*[DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.strings.psd1, line 8 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRpAqML1fTqfxSlKz5_:-KRpAqML1fTqfxSlKz5a:b-9qtgje) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.strings.psd1#L8)):*
> ```PowerShell
> ElevationRequired = This resource must run as an Administrator.
> ValidatingPrerequisites = Validating resource prerequisites...
> CouldNotCovertFeatureState = Could not convert feature state '{0}' into Absent or Present.
> ```

'CouldNotConvert...' instead of 'Covert'

---

*[Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1, line 61 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRpOdy1HBFt8Zce93dt:-KRpOdy1HBFt8Zce93du:b-jo6sdy) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1#L61)):*
> ```PowerShell
>                 Mock Dism\Get-WindowsOptionalFeature { $FeatureName -eq $script:testFeatureName } -MockWith { return $script:fakeEnabledFeature }
> 
>                 It 'Should return a Boolean' {
> ```

? this test? is it really helpful?

---

*[Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1, line 243 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRpQZU-rcL7xM-w98Jc:-KRpQZU-rcL7xM-w98Jd:b-rviecl) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1#L243)):*
> ```PowerShell
>                 }
>                 
>                 It 'Should throw when the DISM module is not available' {
> ```

Is it possible to specify what is thrown - as this test will pass no matter what's thrown. You could also check that the mock is called

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237)*

**Comment by kwirkykat** [comment]
Review status: 8 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.psm1, line 90 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRp4KCFw3QsnJfaJhd9:-KS4-2vmfFgpeX6Mw0Aj:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.psm1#L90)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> 'There is no default...'
</details>
Done.

---

*[DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.strings.psd1, line 4 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRpAX1C7MjeQH6ste92:-KS4-3PxKvlxkiuQ1EVo:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.strings.psd1#L4)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> tab this string content in
</details>
Done.

---

*[DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.strings.psd1, line 8 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRpAqML1fTqfxSlKz5_:-KS4-3lEJU4e7VxG_m6C:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.strings.psd1#L8)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> 'CouldNotConvert...' instead of 'Covert'
</details>
Done.

---

*[Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1, line 61 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRpOdy1HBFt8Zce93dt:-KS3z3xmXbf7n2KL1sqA:bei886a) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1#L61)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> ? this test? is it really helpful?
</details>
I guess not since we already have the other tests.

---

*[Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1, line 243 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-KRpQZU-rcL7xM-w98Jc:-KS4-4xMMLyg5ud19APU:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/438fcdba70f40e68eddb0a2004c459b8aa79a846/Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1#L243)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Is it possible to specify what is thrown - as this test will pass no matter what's thrown. You could also check that the mock is called
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237)*

**Comment by mbreakey3** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237)*

**Comment by mbreakey3** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/237#-:-KS43GWr51Q6OykMhYgz:bnfp4nl)*

**Pull request merged**
