### PR TITLE
Security enhancements in xPackage

### PR DESCRIPTION
**Pull request by dlwyatt**
This still needs some work in the form of Pester tests and examples, but I figured I'd get the PR discussion and code review started.

From PowerShell.org fork:  Users of the resource can specify validation parameters based on the file's expected hash, digital signature, or both.

New:  Original Package and xPackage resources were setting the ServerCertificateValidationCallback property to {$true}, which may as well just be labelled "making malicious websites' jobs easy."

The resource now uses default behavior, refusing self-signed or otherwise invalid certificates.  Users can specifiy their own script block for the new ServerCertificateValidationCallback property, if they so choose.  (And they can be more secure about it, such as pinning a specific self-signed certificate by its thumbprint, etc.)

To do:

- Figure out how to test this stuff in Pester.  I've tested it manually, but we need a running web server to test this.  Maybe find something we can kick off from the command line locally in the tests, rather than relying on IIS.
- Add examples for usage of the new properties.

### CODE REVIEW

**Comment by dlwyatt** [comment]
Crap.. the ISE keeps converting schema.mof files to Unicode for no reason.  I'll fix that later.

**Comment by vors** [comment]
You can use fixers from fixer module to convert them back.
Dave, I will need to work with you to ask for contribution license agreement sign-off before we can take any contributions. I will be back next week with the right process for this. Sorry for this delay.

**Comment by vors** [comment]
Also, can you, please resubmit PR to `dev` branch, like described [here](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#contributing-to-existing-dsc-resources) ?

**Comment by dlwyatt** [comment]
The dev branch didn't exist when I created the PR, but sure.

**Comment by vors** [comment]
You are right, sorry for inconvenience. We are still nailing down all processes. Thank you for the earlier adoption!

**Pull request closed without merging**
