### PR TITLE
Upgrade the xRegistry resource to high quality

### PR DESCRIPTION
**Pull request by kwirkykat**
This is the high quality upgrade of xRegistry for #160.

It includes @Amedama96 's fix for setting a Binary registry value to 0.

Unit tests, integration tests, and examples have been added.
Documentation has been updated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/299)

### CODE REVIEW

**Comment by mbreakey3** [comment]
Reviewed 2 of 17 files at r1.
Review status: 1 of 16 files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 363 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9eVSWQPh8C03I2w4e:-KZ9eVSWQPh8C03I2w4f:b-iqjke9) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/README.md#L363)):*
> ```Markdown
> * **[String] Key** _(Key)_: The path of the registry key to add, modify, or remove. This path must include the registry hive/drive (e.g. HKEY_LOCAL_MACHINE, HKLM:).
> * **[String] ValueName** _(Key)_: The name of the registry value. To add or remove a registry key, specify this property as an empty string without specifying ValueType or ValueData. To modify or remove the default value of a registry key, specify this property as an empty string while also specifying ValueType or ValueData.
> * **[String] Ensure** _(Write)_: Specifies whether or not the registry key or value should exist. To add or modify a registry key or value, set this property to Present. To remove a registry key or value, set the property to Absent. { *Present* | Absent }.
> ```

...'set this property to Absent' for consistency.

---

*[README.md, line 365 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9ecpAs3EquXU9uZpM:-KZ9ecpAs3EquXU9uZpN:bfj9juq) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/README.md#L365)):*
> ```Markdown
> * **[String] Ensure** _(Write)_: Specifies whether or not the registry key or value should exist. To add or modify a registry key or value, set this property to Present. To remove a registry key or value, set the property to Absent. { *Present* | Absent }.
> * **[String] ValueData** _(Write)_: The data the specified registry key value should have as an array of strings.
> * **[String] ValueType** _(Write)_: The type of the specified registry key value should have. { *String* | Binary | DWord | QWord | MultiString | ExpandString }
> ```

The type the specified...'  (extra of)

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 176 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9hUM8_ZQ1k6ctKhDh:-KZ9hUM8_ZQ1k6ctKhDi:bqoez7o) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L176)):*
> ```PowerShell
>         If an empty string ValueName has been specified and no ValueType and no ValueData
>         has been specified, treat this case as if ValueName was not specified and target
>         the Key itself. This is to cater the limitation that both Key and ValueName
> ```

This last sentence is worded a bit weird.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 303 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9jsZw9mfouuANfdZg:-KZ9jsZw9mfouuANfdZh:b-h2uvfg) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L303)):*
> ```PowerShell
>                     Write-Verbose -Message ($script:localizedData.RemovingRegistryKeyValue -f $valueDisplayName, $Key)
>                         
>                     # If the specified registry key value exists, check if it is the user specified a registry key value with a name to remove
> ```

'check if the user....'

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 555 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9oiLr2rVCsnBscSqG:-KZ9oiLr2rVCsnBscSqH:bce4ji1) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L555)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Converts the specigied registry drive root to its corresponding registry drive name.
> ```

'specified'

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 951 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9s82saSJtmfVeYKZ-:-KZ9s82saSJtmfVeYKZ0:bce4ji1) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L951)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Creates a new subkey with the specified name under the specfied registry key.
> ```

'specified'

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1287 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9t_1O3pW986IQdtY3:-KZ9t_1O3pW986IQdtY4:b-kff170) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1287)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Sets the specified registry key value with the specified name to the specigied value.
> ```

specified   lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299)*

**Comment by kwirkykat** [comment]
Review status: 0 of 16 files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 363 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9eVSWQPh8C03I2w4e:-KZ9uhrc786oqnPZKdRd:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/README.md#L363)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

...'set this property to Absent' for consistency.
</blockquote></details>

Done.

---

*[README.md, line 365 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9ecpAs3EquXU9uZpM:-KZ9ul5LJS0ANMhLFVR7:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/README.md#L365)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

The type the specified...'  (extra of)
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 176 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9hUM8_ZQ1k6ctKhDh:-KZ9vB8STHi0OlNfy_kZ:bhpxikf) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L176)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

This last sentence is worded a bit weird.
</blockquote></details>

Moved to the ValueName parameter description

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 303 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9jsZw9mfouuANfdZg:-KZ9vKWGCJM4b2LjPC5t:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L303)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

'check if the user....'
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 555 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9oiLr2rVCsnBscSqG:-KZ9vPLUil8H5bX8jX8D:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L555)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

'specified'
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 951 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9s82saSJtmfVeYKZ-:-KZ9vUHIkqCYQKnp6Tx8:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L951)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

'specified'
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1287 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9t_1O3pW986IQdtY3:-KZ9vYqQ5DIVmnv_RyS4:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1287)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

specified   lol
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299)*

**Comment by mbreakey3** [comment]
Reviewed 14 of 17 files at r1.
Review status: 12 of 16 files reviewed at latest revision, 14 unresolved discussions.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.schema.mof, line 4 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9vGH8DxPTa5Pyj3VE:-KZ9vGH8DxPTa5Pyj3VF:bt9ensp) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.schema.mof#L4)):*
> ```
> class MSFT_xRegistryResource : OMI_BaseResource
> {
>   [Key,Description("The path of the registry key to add, modify, or remove. This path must include the registry hive/drive.")] String Key;
> ```

can you add spaces after the commas? 'Key, Description...'

---

*[DSCResources/MSFT_xRegistryResource/en-US/MSFT_xRegistryResource.strings.psd1, line 26 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9w8UR2AjPTQuqvOyj:-KZ9w8UR2AjPTQuqvOyk:bgeulaf) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/en-US/MSFT_xRegistryResource.strings.psd1#L26)):*
> ```PowerShell
>     RegistryKeyValueTypeDoesNotMatch = The type of the value {0} under the registry key at path {1} does not match the expected type. Expected {2} but was {3}.
>     RegistryKeyValueDoesNotMatch = The value {0} under the registry key at path {1} does not match the expected value. Expected {2} but was {3}.
> ```

did you mean to have an extra newline here?

---

*[Tests/MSFT_xRegistryResource.TestHelper.psm1, line 346 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9xI1wZ1ZOnoPRB3Ks:-KZ9xI1wZ1ZOnoPRB3Kt:b3l551c) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/MSFT_xRegistryResource.TestHelper.psm1#L346)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Tests if the registry drive of he given registry key path is mounted.
> ```

'...drive of the given....'

---

*[Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1, line 4 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9xT5TgQ-OvgsXJgTL:-KZ9xT5TgQ-OvgsXJgTM:b-zfnpzs) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1#L4)):*
> ```PowerShell
>     WARNING: DO NOT RUN THESE TESTS ON A VALUABLE MACHINE!
>     Running on a disposable VM or AppVeyor is strongly recommended.
>     If these tests go awry, your machine's registry could be corrupted which will brick your machine!
> ```

lol brick your machine? Is that what happened to yours?

---

*[Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1, line 59 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9xk5lEmNLfpyyV6h7:-KZ9xk5lEmNLfpyyV6h8:budxxpi) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1#L59)):*
> ```PowerShell
>             $registryKey = Get-Item -Path $registryParameters.Key -ErrorAction 'SilentlyContinue'
> 
>             It 'Should have created registry key' {
> ```

'..the registry key' 

---

*[Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1, line 87 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9xvWB7G_1OvCdWmjx:-KZ9xvWB7G_1OvCdWmjy:b9ehea9) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1#L87)):*
> ```PowerShell
>             $registryKeyValue = Get-ItemProperty -Path $registryParameters.Key -Name $registryParameters.ValueName -ErrorAction 'SilentlyContinue'
> 
>             It 'Should have created registry key value' {
> ```

the registry

---

*[Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1, line 214 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9yFzH6d99F-fSRaPV:-KZ9yFzH6d99F-fSRaPW:b9ehea9) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1#L214)):*
> ```PowerShell
>             $registryKeyValue = Get-ItemProperty -Path $registryParameters.Key -Name $registryParameters.ValueName -ErrorAction 'SilentlyContinue'
> 
>             It 'Should be able to retrieve registry key value' {
> ```

the registry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299)*

**Comment by kwirkykat** [comment]
Review status: 12 of 16 files reviewed at latest revision, 14 unresolved discussions.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.schema.mof, line 4 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9vGH8DxPTa5Pyj3VE:-KZ9znxX64zQ7fF4UB6v:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.schema.mof#L4)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

can you add spaces after the commas? 'Key, Description...'
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xRegistryResource/en-US/MSFT_xRegistryResource.strings.psd1, line 26 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9w8UR2AjPTQuqvOyj:-KZ9zq1W0m_9sgneLDQc:b-g6kxii) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/DSCResources/MSFT_xRegistryResource/en-US/MSFT_xRegistryResource.strings.psd1#L26)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

did you mean to have an extra newline here?
</blockquote></details>

Yup. They separate the Get/Test/Set-TargetResource-specific messages and the error messages

---

*[Tests/MSFT_xRegistryResource.TestHelper.psm1, line 346 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9xI1wZ1ZOnoPRB3Ks:-KZA-7lx2HeGBYDVwnMo:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/MSFT_xRegistryResource.TestHelper.psm1#L346)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

'...drive of the given....'
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1, line 4 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9xT5TgQ-OvgsXJgTL:-KZA-AP_w6kmLEOO0qPJ:b-1xb3ik) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1#L4)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

lol brick your machine? Is that what happened to yours?
</blockquote></details>

Pretty much. I couldn't open ANY programs... I could get to the desktop and that was it.

---

*[Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1, line 59 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9xk5lEmNLfpyyV6h7:-KZA-OkljdFPkylLR1ip:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1#L59)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

'..the registry key' 
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1, line 87 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9xvWB7G_1OvCdWmjx:-KZA-QhtlundJ2Cf3aw_:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1#L87)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

the registry
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1, line 214 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299#-KZ9yFzH6d99F-fSRaPV:-KZA-diLEA6dv8LrxCSL:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/903494e5db1dd2a7e49c3cc45f9172c7fe7918d7/Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1#L214)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

the registry
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299)*

**Comment by mbreakey3** [comment]
Reviewed 1 of 17 files at r1.
Review status: 11 of 16 files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299)*

**Comment by mbreakey3** [comment]
Reviewed 1 of 17 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/299)*

**Comment by mbreakey3** [comment]
LGTM

**Pull request merged**
