### PR TITLE
xPackage fixes and updates

### LINKED ISSUE #52: xPackage should allow some option to not validate installation until after reboot
Line 982+ of `MSFT_xPackageresource.psm1`:

```
if($Ensure -eq "Present")
{
    $productEntry = Get-ProductEntry $Name $identifyingNumber $InstalledCheckRegHive $InstalledCheckRegKey $InstalledCheckRegValueName $InstalledCheckRegValueData
    if(-not $productEntry)
    {
        Throw-TerminatingError ($LocalizedData.PostValidationError -f $OrigPath)
    }
}
```

This happens immediately after the package has installed. Whether a reboot has been requested or not. Some packages do not complete their installation until after a reboot. An example is .Net 4.6.1. The registry keys that one can use to determine whether it is installed or not do not actually appear until after the reboot.

So, xPackage fails. Even though it has succeeded. There needs to be some way to avoid this, allowing the reboot to proceed, and reevaluation to occur when it comes back up.

### LINKED ISSUE #195: xPackage arguments missing a space
xPackage is missing a space before the string in the Arguments parameter.

Example DSC that used to work:

```
xPackage InstallAccessDataBaseEngine_x64
{
    Name = 'Microsoft Access database engine 2010 (English)'
    Ensure = 'Present'
    Path = 'C:\Install\AceRedist.msi'
    ProductId = '90140000-00D1-0409-1000-0000000FF1CE'
    Arguments = '/quiet /norestart'
    ReturnCode = @(
        '0',
        '3010'
    )
}
```

Logged:

[[xPackage]InstallAccessDataBaseEngine_x64] Starting
C:\Windows\system32\msiexec.exe with /i "C:\Install\AceRedist.msi" /quiet/quiet /norestart
VERBOSE: [97561A4CD997]:
[[xPackage]InstallAccessDataBaseEngine_x64] Starting process C:\Windows\system32\msiexec.exe with arguments /i "C:\Install\AceRedist.msi" /quiet/quiet /norestart

process info showing the missing space

PS C:> gwmi win32_process -filter "name = 'msiexec.exe'" | Select-Object CommandLine
## CommandLine

"C:\Windows\system32\msiexec.exe" /i "C:\Install\AceRedist.msi" /quiet/quiet /norestart

### LINKED ISSUE #221: xPackage: RunAsCredential Parameter Removed
It appears that in the v3.13.0.0 release, the `RunAsCredential` has been removed. This breaks installations on WMF 4 where the `PsDscRunAsCredential` is not supported :disappointed:.

@kwirkykat is there any particular reason that this has been removed (before I look at adding it back in)?

### LINKED ISSUE #224: xPackage: Mispelled variable `errLogPath` and inverse conditional (minor)
Running into some issues with 3.13.0.0 release:
- [Line 1375](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L1375): errLogPath is mispelled. Should be "errorLogPath"
- [Line 467](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L467): The condition is wrong, should be `-ne` because otherwise it is formatting a message with null value.

### PR DESCRIPTION
**Pull request by iainbrighton**
xPackage:
* No longer checks for package installation when a reboot is required
  - Fixes #52 
* Ensures a space is added to MSI installation arguments
  - Fixes #195 
* Adds RunAsCredential parameter to permit installing packages with specific user account
  - Fixes #221 
* Fixes null verbose log output error
  - Fixes #224

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/278)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@iainbrighton - change looks great. I didn't review using the HQRM guidelines though. Sorry about the Out-Null nit picks :)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xPackageResource.Tests.ps1, line 38 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/278#-KX9qVbsn4hRx5-W2QJP:-KX9qVbsn4hRx5-W2QJQ:b-jep0vl) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c41f1cd065fc87396c1fbf656d8223a77b30a6d0/Tests/Unit/MSFT_xPackageResource.Tests.ps1#L38)):*
> ```PowerShell
>                 $script:testExecutablePath = Join-Path -Path $script:testDirectoryPath -ChildPath 'TestExecutable.exe'
>                 
>                 New-TestExecutable -DestinationPath $script:testExecutablePath | Out-Null
> ```

Not lines that you wrote, but could you assign these two lines to $null rather than pipe to Out-Null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/278#-:-KX9qwKw9DDfSJ78hNdL:b-bzqalc)*

**Comment by iainbrighton** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xPackageResource.Tests.ps1, line 38 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/278#-KX9qVbsn4hRx5-W2QJP:-KXAUEvIZvx2E2DfGs_v:blir1xk) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c41f1cd065fc87396c1fbf656d8223a77b30a6d0/Tests/Unit/MSFT_xPackageResource.Tests.ps1#L38)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Not lines that you wrote, but could you assign these two lines to $null rather than pipe to Out-Null?
</details>
No problem. Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/278)*

**Comment by TravisEz13** [comment]
piping to `$null` looks cleaner to me, but LGTM

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/278#-:-KXmKXoOyUEaHkhThzUW:bkm87v2)*

**Comment by TravisEz13** [comment]
Please resolve all merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )

**Comment by iainbrighton** [comment]
I don't see any merge conflicts?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/278#-:-KXv50BWQxxTkyA_g245:b-z0t2x9)*

**Comment by TravisEz13** [comment]
GitHub says readme.md has a conflict

**Comment by TravisEz13** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/278)*

**Pull request merged**
