### PR TITLE
xPSDesiredStateConfiguration: Multiple AppVeyor jobs

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Changes to xPSDesiredStateConfiguration
  - In AppVeyor CI the tests are split into three separate jobs, and also
    running tests on two different build worker images (Windows Server
    2012R2 and Windows Server 2016). The common tests are run on only
    one of the build worker images (Windows Server 2012R2). Helps with
    [issue #477](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/477).

@mhendric @PlagueHO I send in this PR if this is of any interest. If not then please close it.

#### This Pull Request (PR) fixes the following issues
Helps with issue #477.
Closes #403 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/509)

### CODE REVIEW

**Comment by johlju** [comment]
I will rebase this as soon as PR #510 is merged (can't checkout dev correctly until then).

**Comment by johlju** [comment]
I meant theoretically the change I did should work 😄

**Comment by johlju** [comment]
Yep, it did work! Yay! https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/builds/21962178/job/rk7d44iucc30j005#L65

**Comment by johlju** [comment]
@mhendric Let me know if you find more improvements that can be made. 😄

**Comment by mhendric** [comment]
Hey @johlju , sorry, haven't had a chance to dig into this yet today, but will do another CR later. It probably wouldn't hurt to have another set of eyes on this though, especially with the YAML (@PlagueHO ?).

And just for my clarity, what's the expected behavior here when you run this against a free AppVeyor account. Would it still run all 5 jobs (Meta + 2x(Integration + Unit)), or would it only run against the preferred image (thus reducing to 3 jobs)? I think we opted to delay adding multiple images via #403 until we can reduce test times (#477). If the same concern still exists, I'm wondering if for now we should take everything you have here except the multiple image part, and then add the multiple images at a later date. What do you think?

**Comment by johlju** [comment]
No worries. No hurry at all. 

On a free account it will run all 5 jobs sequentially. Time wise it is not a problem per individual job because each job are allowed to run for 60 minutes. 
Also, we want to run the test on both images for two free account as well. 

I have no problem leaving this as is until the tests have been refactored. But having both images while refactoring the test will make sure the resources still work on both images during refactoring. 

Anyways, let me know what you decide. I change to what ever you choose :smile:

**Comment by mhendric** [comment]
I think I'm probably OK with adding multiple images now. Nothing like feeling the pain (long overall build time on free accounts in this case) to motivate people to fix stuff, right? Let's let @PlagueHO weigh in on this though.

**Comment by johlju** [comment]
___
*[Tests/CommonTestHelper.psm1, line 826 at r4](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/509#-LXQP-I0EQYN2r-bfBIb:-LXQP-I0EQYN2r-bfBIc:blana0c) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5880437bb549bfb30415b8154617de109e5a6667/Tests/CommonTestHelper.psm1#L826)):*
> ```PowerShell
>     if ($env:APPVEYOR -eq $true -and $env:CONFIGURATION -ne $Type)
>     {
>         Write-Verbose -Message ('{1} tests for {0} will be skipped unless $env:CONFIGURATION is set to ''{1}''.' -f $Name, $Type) -Verbose
> ```

The message says “...test for <filename>...”, should it say “...tests in <filename>...” instead?

**Comment by johlju** [comment]
My fingers itched to fix the tests to the correct template when I added the code snippet to each file. I saw files using different variations too. And importing a module in the beforeeach-block. Definitely room for improvements in these tests, and surely if it takes time running tests maybe there are more contributors wanting to help resolve that :)

**Comment by johlju** [comment]
I will fix the review comments tomorrow morning. :)

**Comment by johlju** [comment]
@mhendric @PlagueHO There is only one potential problem with this PR that I see now, and this is that both the jobs that runs the unit tests, both will upload the Codcov result. They should report up the same information, so might be a non-issue.
To solve it there is two options.
1. Exclude the unit tests from one of the images. I rather not like this idea.
2. Add a rule to the matrix that when running the configuration 'Unit' on one of the images, the parameter `CodeCovIo` of the function  `Invoke-AppveyorTestScriptTask` is skipped in that job. Though, not sure it is possible to make this rule, so might need to ask the AppVeyor team. See example below.
   ```yml
   -
     matrix:
       only:
         - configuration: Unit
         - image: Visual Studio 2015
     environment:
       SkipAllCommonTests: True

     test_script:
       - ps: |
           Invoke-AppveyorTestScriptTask `
               -Type 'Default' `
               -CodeCoverage `
               -CodeCovIo `
               -ExcludeTag @()

   -
     matrix:
       only:
         - configuration: Unit
         - image: Visual Studio 2017
     environment:
       SkipAllCommonTests: True

     test_script:
       - ps: |
           Invoke-AppveyorTestScriptTask `
               -Type 'Default' `
               -CodeCoverage `
               -ExcludeTag @()

   ```

See AppVeyor documentation around [Specializing matrix job configuration](https://www.appveyor.com/docs/build-configuration/#exclude-configuration-from-the-matrix).

** I will test this out and report back.**

**Comment by johlju** [comment]
@mhendric @PlagueHO I have fixed the above. Codecov is not only reported by one of the jobs. Also added comments to the AppVeyor to explain a bit more of what the different parts mean.

**Comment by mhendric** [comment]
Question. Does testing against Visual Studio 2015 and Visual Studio 2017 really buy us that much? Per (this)[https://www.appveyor.com/docs/windows-images-software], it looks like both images include PowerShell 5.1. That does give us different OS versions (Win 2012 R2 vs. Win 2016), but it doesn't allow us to verify tests against legacy PowerShell (i.e. version 4). If we are concerned with testing against PS4, perhaps we should use the Visual Studio 2013 image instead of the Visual Studio 2015 image. That would still allow us to test against Win 2012 R2, but would also allow us to test against PS4. Thoughts?

**Comment by johlju** [comment]
Yes that is okay with me, to change to Visual Studio 2013. The reason I choose those to images was because that was what was in PR #403. Let’s change that, and see if anything fails (hope not).

**Comment by johlju** [comment]
It doesn't look like 'Windows Server 2013' contain PS4.0. According to this they all have PS5.1 https://www.appveyor.com/docs/windows-images-software/#powershell

**Comment by mhendric** [comment]
Hmmmm ok. I must have completely misread that. Sorry about that.

**Comment by johlju** [comment]
@mhendric There is an image called 'WMF 4', but it is only available on the AppVeyor PowerShell account. It fails on my account; https://ci.appveyor.com/project/johlju/xpsdesiredstateconfiguration, but it works in this PR. But that makes it a problem running tests for contributors.

**Comment by johlju** [comment]
I see now our test framework is not made to run on PS 4.0. It fails dramatically too. 😄 Reverting back to the 'Visual Studio 2015' image.

**Comment by johlju** [comment]
@mhendric I'm back to 'Visual Studio 2015' now, but maybe there is no point of adding two images as you mentioned? No need to test 2012R2 and 2016?

**Comment by mhendric** [comment]
What do you think about testing two OS versions but the same PowerShell version, @johlju ? I definitely think there's some value, but I question if it's worth the extra time that will be incurred against free AppVeyor accounts.

And that sucks that we can't do any automated PS4 testing (at least not with the current framework). If one of the reasons for having xPSDesiredStateConfiguration in addition to PSDscResources is in fact to maintain support for PS4 (which I'm not positive about but I've heard thrown around), we should probably figure out a way to actually test against PS4. I'm somewhat skeptical that all the resources actually do work with it (see my issue in #511).

**Comment by mhendric** [comment]
@johlju , first, sorry for being all indecisive on this one. But after working on #515 and utilizing my free AppVeyor account to check for errors, I'm totally OK with adding multiple images. When I utilize my free account, I'm generally checking to see if I hit any build/test errors, or if the output is what I expected it to be. If I do see something unexpected, I'll go try to fix it, and submit my changes, and won't wait for the current build to finish. Even if the jobs were to run sequentially, I'd have a pretty good idea after the first set of Unit and Integration tests whether the overall build is going to run as expected without having to wait for the second set of Unit and Integration tests to finish. All that being said, my vote is to add the multiple images.

On the topic of multiple images though, I wonder if the newest image should be executed first (when running sequentially)? I'm not sure what's more common these days (2012 R2 or 2016), but I think it would make sense to have the more common build run first.

**Comment by johlju** [comment]
No worries. Sorry I did not have time to answer you until now, been a busy week. I think it is good that we test on multiple images, there might be scenarios that we don't think of until the integration tests run on a specific OS. As you say, there is no need to wait for the full test suit to run finished before sending in a PR. If there is errors after sending in a PR those are probably pretty minor so a few additional commits is not a problem (IMHO). If there are more wpork it as easy closing the PR, and continue working "offline", and then reopen the PR and all the new commits will be added automatically. *Although, rebasing should only been done while the PR is open, otherwise the PR "breaks" and cannot reopen.*

**Comment by johlju** [comment]
I will put the latest OS to run first. Sounds like a good plan.

**Comment by PlagueHO** [comment]
I'll try and get onto a bunch of this stuff tomorrow.

**Comment by johlju** [comment]
@PlagueHO I have done the requested changes, except change the script to load the module the same way. I can't publish my Reviewable comments for some reason, see isssue https://github.com/Reviewable/Reviewable/issues/613.

Hers is my comments:
image

Please retract the comments if I haven't been able to publish the comments until next time you review.

**Comment by johlju** [comment]
@PlagueHO I reverted the change to MSFT_xRemoteFile.Tests.ps1 where I replace $global with $script. It takes more changes to that test file than is the scope for this PR. Let's do that in another PR. 😄

**Comment by johlju** [comment]
Now it deploys on the job number that is set in appveyor.yml. 
Job 1-4 do not deploy: https://ci.appveyor.com/project/johlju/xpsdesiredstateconfiguration/builds/22075321/job/l6ix4xh03su3b8ol#L2951
Job 5 deploy: https://ci.appveyor.com/project/johlju/xpsdesiredstateconfiguration/builds/22075321/job/en2b9a2t789x0s6c#L2657

**Comment by PlagueHO** [comment]
Here we go! :grin:

**Pull request merged**
