### PR TITLE
Update xProcess resource to fix PSSA and style Issues

### LINKED ISSUE #132: MSFT_xProcessResource: Fix PSSA Issues
The PowerShell Script Analyzer issues in MSFT_xProcessResource need to be fixed.
This is the current result of running Invoke-ScriptAnalyzer:
image
image

### PR DESCRIPTION
**Pull request by Dan1el42**
Hello everyone,

Another PR to fix #132  PSSA and style issues. Please review at your earliest convenience.

Thanks very much,
Daniel

### CODE REVIEW

**Comment by Dan1el42** [comment]
Script Analyzer:
- Before
image

- After
image

**Comment by kwirkykat** [comment]
Reviewed 1 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions.

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 140 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQqYP_89vZ1kWIc403W:-KQqYP_89vZ1kWIc403X:bta6ah) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L140)):*
> If this the
If this is the

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 224 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQq_HOf1564Ez_ExY1P:-KQq_HOf1564Ez_ExY1Q:bta6ah) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L224)):*
> If this the
If this is the

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 296 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQRytkEPz4Ld1DuU7Zo:-KQRytkEPz4Ld1DuU7Zp:b-gp8n36) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L296)):*
> ```PowerShell
>     if ($null -ne $PsDscContext.RunAsUser)
>     {
>         $params = @{
> ```

$params should have a more descriptive name. (ex: $exceptionParams, $invalidArgParams, $newInvalidArgumentExceptionParams)

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 320 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQRzAf3NFMAsmdxgUaZ:-KQRzAf4H5CNuggcUmq1:b5irqye) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L320)):*
> ```PowerShell
>     if ($Ensure -eq 'Absent')
>     {
>         $params = @{
> ```

$params should have a more descriptive name. (ex: $assertHashtableParams, $assertArgsParams)

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 373 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQqZKGstBEME9L4qVLZ:-KQqZKGstBEME9L4qVL_:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L373)):*
> ```PowerShell
>             if (-not [String]::IsNullOrEmpty($PSBoundParameters[$shouldBeRootedPathArgument]))
>             {
>                 $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 387 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQqZNP5F_xi6VARSy3O:-KQqZNP5F_xi6VARSy3P:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L387)):*
> ```PowerShell
>             if (-not [String]::IsNullOrEmpty($PSBoundParameters[$shouldExistPathArgument]))
>             {
>                 $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 412 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQqZmAOMI_relYAZxD5:-KQqZmAOMI_relYAZxD6:b2z8oxj) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L412)):*
> ```PowerShell
>             {
>                 $parameterKey = $startProcessOptionalArgumentMap[$startProcessOptionalArgumentName]
>                 $value = $PSBoundParameters[$parameterKey]
> ```

$value needs a more descriptive name (ex: $parameterValue, $startProcessArugmentValue, etc...)

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 440 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQq_3eLfS3dpf2Qj2Pl:-KQq_3eLfS3dpf2Qj2Pm:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L440)):*
> ```PowerShell
>                     foreach ($key in @('StandardOutputPath','StandardInputPath','WorkingDirectory'))
>                     {
>                         $params = {
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 507 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQq_Q4VpAZ83RKjzeZb:-KQq_Q4VpAZ83RKjzeZc:bta6ah) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L507)):*
> If this the
If this is the

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 521 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQq_WI-Xc103WyLlyE-:-KQq_WI-Xc103WyLlyE0:bvrgxq9) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L521)):*
> Set this property to "Present" to ensure that the process
>         exists. Otherwise, set it to "Absent".

Set this property to "Present" to return true if the process exisits.
Otherwise, set it to "Absent" to return true if the process does not exist.

Test-TargetResource will not change the state of the process.

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 524 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQqaC57kPmVCMeJr1i1:-KQqaC57kPmVCMeJr1i2:by0qppv) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L524)):*
> ```PowerShell
>         exists. Otherwise, set it to "Absent". The default is "Present".
> 
>     .PARAMETER StandardOutputPath
> ```

Only the Path, Arguments, Credential, and Ensure parameters are actually used for this function.
Can you please change the descriptions of the other parameters accordingly?

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 580 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQqa2as9l5DSunXX0-e:-KQqa2as9l5DSunXX0-f:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L580)):*
> ```PowerShell
>     if ($null -ne $PsDscContext.RunAsUser)
>     {
>         $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1, line 748 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-KQqaSZDri918rl-KnSw:-KQqaSZDri918rl-KnSx:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/2027c5f671d6af895a24776caaacab0f0ef8c116/DSCResources/MSFT_xProcessResource/MSFT_xProcessResource.psm1#L748)):*
> ```PowerShell
>             {
>                 Write-Verbose -Message ($LocalizedData.VerboseInProcessHandle -f $process.Id)
>                 $params = @{
> ```

$params needs a more descriptive name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206)*

**Comment by Dan1el42** [comment]
@kwirkykat , thanks so much for your thorough review on a Sunday 👍 . I've pushed a new commit to my branch which should fix everything you've highlighted with your comments.

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/206#-:-KR02F68ksxTPEBmN8PK:bnfp4nl)*

**Pull request merged**
