### PR TITLE
xRemoteFile: Remove progress bar for file download

### LINKED ISSUE #165: xRemoteFile verbose output does not display progress correctly
When xRemoteFile is in the process of downloading, the verbose output displays bytes transferred but does not display the progress bar or time remaining.

Example output:

```
Writing web request
    Writing request stream... (Number of bytes written: 251558324)
    [
    00:00:00 remaining.

    [node] Set-TargetResource
```

### LINKED ISSUE #383: xRemoteFile is very slow
I noticed that downloading files with xRemoteFile is very slow. From what I've read in the link below and the tests I've performed, I can confirm that it is due to the way the progress bar is rendered. This is really bad. Is it possible to disable the progress bar in the xRemoteFile cmdlet?

Something as silly as this should work:
```powershell
# Invoke web request
try
{
    Write-Verbose -Message $($LocalizedData.DownloadingURI `
        -f ${DestinationPath},${URI})
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest @PSBoundParameters -Headers $headersHashtable -outFile $DestinationPath
}
catch [System.OutOfMemoryException]
{
    ...
}
catch [System.Exception]
{
    ...
}
finally 
{
    $ProgressPreference = 'Continue'
}
```

More info can be found here:
https://github.com/PowerShell/PowerShell/issues/2138

### PR DESCRIPTION
**Pull request by claudiospizzi**
Our use case is to download the source files of an SQL server installation from a remote system. This sources files are up to 3GB. We often use `Start-DSCConfiguration -Wait` in integration testing. In this use case, the progress bar of the Invoke-WebRequest is extremely delayed, due to the byte download counter. In fact, the file gets downloaded within half a minute (1 Gbps) but the progress bar takes minutes to complete.

With this PR, we hide the byte counter progress bar of the Invoke-WebRequest cmdlet.

Fixes #165 
Fixes #383 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/390)

### CODE REVIEW

**Comment by johlju** [comment]
@claudiospizzi sorry it took so long for someone to review this. Could you rebase this PR to get the latest changes?

**Comment by claudiospizzi** [comment]
Rebased

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/390#-:-LCYOZNo6rT6u6vHQ_hm:b9x2p3v)*

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1, line 215 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/390#-LCc9oAw5vjcL0QUhodQ:-LCc9oAw5vjcL0QUhodR:b-qxo752) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/d1885d2b5afc4d3551f0bed429c452a2d8c114fa/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1#L215)):*
> ```PowerShell
>     try
>     {
>         $ProgressPreference = 'SilentlyContinue'
> ```

Maybe we should remember the current setting and set it back once `Invoke-WebRequest` has ran? Preferably in a finally-block.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/390)*

**Comment by claudiospizzi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1, line 215 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/390#-LCc9oAw5vjcL0QUhodQ:-LDwvgyQ216tJUtlONIO:b-sglk2z) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/d1885d2b5afc4d3551f0bed429c452a2d8c114fa/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1#L215)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe we should remember the current setting and set it back once `Invoke-WebRequest` has ran? Preferably in a finally-block.
</blockquote></details>

Good idea, implemented.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/390)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/390#-:-LE9ZrGw36xEDNW8o8Lx:bnfp4nl)*

**Pull request merged**
