### PR TITLE
xService: Adding support for Group Managed Service Account

### PR DESCRIPTION
**Pull request by danielboth**
#### Pull Request (PR) description
Add support for Group Managed Service Accounts to xService. This enables the xService DSC resource to setup the runas account for services using a Group Managed Service Account (GMSA). This pull request adds support and unit tests for the gMSA setup.

#### This Pull Request (PR) fixes the following issues
No open issues for the missing support of gMSA's on xService

#### Task list

- [X] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md.
- [X] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

Integration tests for the GroupManagedServiceAccount were not added as the appveyor build environment does not run in domain context, so integration testing gMSA's is not possible.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/441)

### CODE REVIEW

**Comment by johlju** [comment]
@danielboth I wanted to run this by you before I merge this PR. Please see this https://github.com/PowerShell/PSDscResources/issues/108#issuecomment-416788334, would it be possible to use the same technique adding a gMSA to the Credential property? I just want to rule it out, so we don't add something that is more overly complicated. Even if it do work, maybe this proposal has more advantages anyway? Appreciate your input on this one, thank you!

**Comment by danielboth** [comment]
Hi @johlju, it's definitely possible to add the gMSA in the same way in the Credential parameter. It would even be easier to add that way, since then we could just verify in the code that when the password is empty, we don't pass it forward to the CimMethod that set's the service properties.

For example this:
https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/d50a45e70308629de4726cb6babe5093ada2107b/DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.psm1#L1359

Could easily become:
```PowerShell
if(-not([string]::IsNullOrEmpty($Credential.GetNetworkCredential().Password))){
$changeServiceArguments['StartPassword'] = $Credential.GetNetworkCredential().Password
}
```

Now this has also one (big if you ask me) downside. That is the fact that DSC, even though we are passing an empty password, requires us to enable plaintext password support by setting PSDscAllowPlainTextPassword in the configuration for the node. Try explaning an auditor that in order to use more secure accounts, we need to enable plaintext password support. I would also like to avoid enabling my configurations to save plaintext passwords. That's why I opted for the separate parameter instead.

**Comment by johlju** [comment]
@danielboth This sounds like a much better approach then adding a separate property for this. And since `PSDscAllowPlainTextPassword` shouldn't be used in production, but instead the configuration should be encrypted I think an auditor see the benefit that the configuration is using a secure account, _and_ the configuration is encrypted, protecting the account name even more.
This resource is also most likely to be used in a configuration with other resources requiring securing the mof file as well. 
If it is used in a configuration where there were nothing else to secure, I can see the benefit of having a separate property for this, but I can't see that maintaining the additional code complexity making it worthwhile.

I'm in favor of changing this to your suggestion, using the `Credential` property, than adding another property.

**Comment by danielboth** [comment]
I stil feel that putting in a Group Managed Service Account in a credential object is not the right way. This because we cannot create a credential object for a gMSA, we can just define the user itself and the user itself is just a simple string, nothing more. So why claim you expect a credential when what you are really asking for is the username? Sounds a bit misleading and not intuitive at all.

I also see your point about implementing an extra parameter just for this, which might add a bit too much overhead on the codebase. I agree there.

What about renaming the current BuiltInAccount parameter to RunAsUser? That property could then be used both for the builtin users (LocalSystem, NetworkService) and for Group Managed Service Accounts. That way, if it's not LocalSystem or NetworkService we assume that the user provides us with a Group Managed Service Account. We will still support the Credential parameter for any other accounts.  Would that be acceptable?

**Comment by johlju** [comment]
I agree that using credential object can be misleading. Renaming built in account sounds like a good option, but would make use remove the ValidateSet, making users potentially spell those built in account wrong (really minor issue though :), and it would be a breaking change if we rename it. 

Honestly, In this case, and since there are only two opinions in this PR, I will weight the opinion of the PR author higher than my opinion. @danielboth If we disregard that any option need more work, or breaking change, what option do you like the best? Let's go with that.

**Comment by bielawb** [comment]
I read the whole thread and if I would have to choose (in order of preference) I'd go with:
* new parameter (no risk for breaking change, using gMSA the way God intended)
* merging it with BuiltInAccount (still using string for string property, but potential issues with spelling)
* credential object (fake one, with all the overhead of maintaining password/certs/plain text/LCM config)

I can't wait to start using it for that purpose within DSC, for now we have simple resources that enable us to work around the problem of the missing proper support, so the more, the merrier...

**Comment by johlju** [comment]
@danielboth sounds good.
@bielawb thanks for you voice on this!

**Comment by johlju** [comment]
The CLA bot is waiting for CLA to be signed, but that should be already signed (as per other PR's). Closing and directly open this PR to kick off the CLA bot again.

**Comment by johlju** [comment]
@danielboth This is merged now! Thank you for this, and the great discussion around this! 😃

**Pull request merged**
