### PR TITLE
xDSCWebservice: FIX Firewall Exception

### LINKED ISSUE #536: xDSCWebservice Firewall Exception
### Description

The xDSCWebservice Firewall exception automatically creates up a DSCPullServer_IIS_Port rule that opens up port 8080 to the complete internet. I'd like to be able to control this behaviour because now I have to jump through a couple of hoops to delete the firewall rule with a Script resource and create a new rull that only opens it to a certain subnet.

It is hardcoded on this line:
https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.psm1#L382

### Proposed properties

Add a parameter called FirewallException = $true or $false that controls the creation of the firewall rules.

### PR DESCRIPTION
**Pull request by tmeckel**
#### Pull Request (PR) description

This PR contains a fix for issue #536 where a (unwanted) firewall exception is automatically created during the deployment of a Pull Server.

#### This Pull Request (PR) fixes the following issues
- Fixes #536 

#### Task list
This PR is currently marked as draft because work isn't finished yet. The following task list will be updated.

- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated. 
- [x] Localization strings added/updated in all localization files as
      appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/614)

### CODE REVIEW

**Comment by tmeckel** [comment]
@mhendric can you give a hint why this meta test is failing??? I already rebased my branch to `origin/dev`. The error still persists.

https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/builds/23660190/job/xng6p5sns1k7c627/tests

```Powershell
at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\DscResource.Tests\Meta.Tests.ps1: line 499
499:                         $requiredPssaRulesOutput | Should -Be $null
``` 

Strangely enough the test is passed with my other PR #613  

https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/builds/23660192/job/u5lxm5awv412o4hn/tests

**Comment by mhendric** [comment]
It looks like it failed because the new function you added, Test-PullServerFirewallConfiguration, returns a type of Boolean, but does not have an OutputType specified in the param header.

```

    Context Firewall.psm1
1232
      [+] Should pass all error-level PS Script Analyzer rules 47ms
1233
Required PSSA rule(s) did not pass.
1234
The following PSScriptAnalyzer rule 'PSUseOutputTypeCorrectly' errors need to be fixed:
1235
Firewall.psm1 (Line 97): The cmdlet 'Test-PullServerFirewallConfiguration' returns an object of type 'System.Boolean' but this type is not declared in the OutputType attribute.
1236
For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
1237
      [-] Should pass all required PS Script Analyzer rules 1.99s
1238
        Expected $null, but got Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord.
1239
        499:                         $requiredPssaRulesOutput | Should -Be $null
1240
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\DscResource.Tests\Meta.Tests.ps1: line 499
1241
      [+] Should pass all flagged PS Script Analyzer rules 158ms
1242
      [+] Should pass any recently-added, error-level PS Script Analyzer rules 58ms
1243
      [+] Should not suppress any required PS Script Analyzer rules 10ms
```

**Comment by tmeckel** [comment]
@mhendric thanks for the quick answer! I added the OutputType declaration.

One additional question: I execute the defined Unit tests for xDSCWebService like so:

```Powershell
Invoke-Pester .\Tests\Unit\MSFT_xDSCWebService.Tests.ps1
```

How do I execute the meta test,  so that I won't push PRs that don't adhere to the defined coding rules in the future?

**Comment by mhendric** [comment]
> @mhendric thanks for the quick answer! I added the OutputType declaration.
> One additional question: I execute the defined Unit tests for xDSCWebService like so:
> Invoke-Pester .\Tests\Unit\MSFT_xDSCWebService.Tests.ps1
> How do I execute the meta test,  so that I won't push PRs that don't adhere to the defined coding rules in the future?

I think you just call DscResource.Tests\Meta.Tests.ps1.

**Comment by tmeckel** [comment]
@mhendric @PlagueHO @johlju the PR is now ready. Would be nice if one of you guys would do a review.

**Comment by mhendric** [comment]
Hi @tmeckel , I can review this one for you. However, can you try to get a clean build through first? I'd like to see if the Unit and Integration tests are passing too. Looks like this is failing on Meta tests again (mostly due to lines longer than 80 chars, or trailing whitespace in README.MD).

1879
    Context When there are markdown files
1880
VERBOSE: Using markdownlint settings file from repository folder 'C:\projects\xpsdesiredstateconfiguration'.
1881
C:\projects\xpsdesiredstateconfiguration\CHANGELOG.md: 19: MD013/line-length Line length [Expected: 80; Actual: 130]
1882
C:\projects\xpsdesiredstateconfiguration\README.md: 195: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
1883
C:\projects\xpsdesiredstateconfiguration\README.md: 199: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
1884
C:\projects\xpsdesiredstateconfiguration\README.md: 191: MD013/line-length Line length [Expected: 80; Actual: 183]
1885
C:\projects\xpsdesiredstateconfiguration\README.md: 195: MD013/line-length Line length [Expected: 80; Actual: 185]
1886
C:\projects\xpsdesiredstateconfiguration\README.md: 197: MD013/line-length Line length [Expected: 80; Actual: 332]
1887
C:\projects\xpsdesiredstateconfiguration\README.md: 199: MD013/line-length Line length [Expected: 80; Actual: 273]
1888
      [-] Should not have errors in any markdown files 5.18s
1889
        Expected 0, but got 7.
1890
        976:                     $mdErrors | Should -Be 0
1891
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\DscResource.Tests\Meta.Tests.ps1: line 976
1892
1893
    Context When uninstalling markdown validation dependencies
1894
      [+] Should not throw an error when uninstalling package gulp-concat as a dev-dependency 7.07s

**Comment by mhendric** [comment]
Hey @tmeckel , this all looks good to me. Just to confirm, are you done working on this? If so I'll get this merged.

**Comment by tmeckel** [comment]
> Hey @tmeckel , this all looks good to me. Just to confirm, are you done working on this? If so I'll get this merged.

Hey @mhendric thanks for the review! Highly appreciated. I'm done working on this, so go ahead with the merge. When you've done with it I can rebase my other PR https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/613 and prepare it for review as well.

**Pull request merged**
