### PR TITLE
PublishModulesAndMofsToPullServer: Fixed a bug in Publish-MOFToPullServer introduced in 8.5.0.0

### PR DESCRIPTION
**Pull request by HansOMartinsen**
#### Task list
- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as
      appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/617)

### CODE REVIEW

**Comment by mhendric** [comment]
Hey @HansOMartinsen , thanks for the contribution. The original code [changed here](https://github.com/PowerShell/xPSDesiredStateConfiguration/commit/08343751146fa6a5634719539f49da92fa0308b3) actually created a new file, it would just overwrite if it already exists. Your update assumes the file already exists, which I'm not sure is what we should expect or not. I'm haven't dug into this enough to know myself, but do you know whether or not we should expect the file to already exist when this function is called? If we can't make know for certain, I'd be more inclined to just overwrite an existing file like the original version did, by adding -Force. i.e.

```
PS C:\Users\Mike> New-Item -Path 'test.txt' -ItemType File


    Directory: C:\Users\Mike


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        4/22/2019   2:44 PM              0 test.txt

# The error we're seeing now
PS C:\Users\Mike> New-Item -Path 'test.txt' -ItemType File
New-Item : The file 'C:\Users\Mike\test.txt' already exists.
At line:1 char:1
+ New-Item -Path 'test.txt' -ItemType File
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Mike\test.txt:String) [New-Item], IOException
    + FullyQualifiedErrorId : NewItemIOError,Microsoft.PowerShell.Commands.NewItemCommand

PS C:\Users\Mike> New-Item -Path 'test.txt' -ItemType File -Force


    Directory: C:\Users\Mike


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        4/22/2019   2:44 PM              0 test.txt
```

**Comment by RossUA** [comment]
Hi @mhendric ,

Found the same issue as @HansOMartinsen is referring to. The purpose of this function is to take an existing MOF file and publish it on a Pull Server with checksum. If you use -Force flag, you will overwrite all the settings in the MOF file, rendering it blank.

This function doesn't make sense without an input file, so if there's no input file, there's nothing to publish. So we should expect an input file to exist and we should not create it.

Have a great day!
Ross

**Comment by mhendric** [comment]
@RossUA , thanks for your insight. Looking at the full function now, I agree with you that the MOF must exist, or else this function is pointless. Let me see if I can get conflicts resolved on this and get it merged.

**Comment by mhendric** [comment]
Looks like this has a couple CI failures due to new style tests added in DSCResources.Tests. Since we haven't heard from @HansOMartinsen in a while, I'm going to go ahead and just create a new PR that addresses this issue plus these CI issues. I'll close out this PR once the new one has been submitted.

**Comment by mhendric** [comment]
Hey @SSvilen, @PlagueHO , and @johlju . since you guys recently worked on the tests for Hashtables aligning to the DSC style guidelines, I wanted to see if you can help identify why the above CI run (https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/builds/28862468) is failing. Specifically I'm looking for help with the failure in xFileUpload.schema.psm1. Given the line number it's failing on (72), it almost seems to me like the test may be incorrectly identifying the Script resource block as a hashtable. Thoughts?

```
[00:03:10]     Context xFileUpload.schema.psm1
[00:03:10]       [+] Should pass all error-level PS Script Analyzer rules 139ms
[00:03:11]       [+] Should pass all required PS Script Analyzer rules 215ms
[00:03:12]       [+] Should pass all flagged PS Script Analyzer rules 985ms
[00:03:12]       [+] Should pass any recently-added, error-level PS Script Analyzer rules 115ms
[00:03:12]       [+] Should not suppress any required PS Script Analyzer rules 69ms
[00:03:13] Custom DSC Resource Kit PSSA rule(s) did not pass.
[00:03:13] The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Hashtable' errors need to be fixed:
[00:03:13] xFileUpload.schema.psm1 (Line 72): Hashtable is not correctly formatted. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects
[00:03:13] For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
[00:03:13]       [-] Should pass all custom DSC Resource Kit PSSA rules 1.54s
[00:03:13]         Expected $null, but got Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord.
[00:03:13]         582:                         $customPssaRulesOutput | Should -Be $null
[00:03:13]         at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\DscResource.Tests\Meta.Tests.ps1: line 582
```

**Comment by SSvilen** [comment]
Indeed they are... I already have a fix, but I'll run checks against couple of DSC repos just to make sure that nothing gets broken again..

**Comment by mhendric** [comment]
Thanks for the confirmation @SSvilen . I'll put this PR on hold and then pick it back up once your fix gets checked in.

**Comment by SSvilen** [comment]
[PR](https://github.com/PowerShell/DscResource.Tests/pull/356) has been opened.

**Comment by mhendric** [comment]
Closing this PR, as the issue is being addressed in #647

**Pull request closed without merging**
