### PR TITLE
Add Proxy and Timeout support to xRemoteFile - Fixes #122

### LINKED ISSUE #120: xRemoteFile failing due to timeout
I'm trying to download an asset from a server where an initial response is quite long (doing some preparation of big file), but it is not possible to set a timeout for the operation.

Fixed locally by changing the resource scripts:

``` powershell
    try
    {
        Write-Verbose "Downloading $Uri to $DestinationPath"
        Invoke-WebRequest @PSBoundParameters -Headers $headersHashtable -outFile $DestinationPath -TimeoutSec 14400
    }
```

### LINKED ISSUE #122: xRemotefile download fails via proxy
The original reported issue is in the link below -
https://github.com/puppetlabs/puppetlabs-dsc/issues/160#issuecomment-163691226

In summary, the issue is -
The xRemoteFile DSC Resource is a wrapper around the Invoke-WebRequest cmdlet. Invoke-WebRequest does provide parameters to handle proxy details, however xRemoteFile does not expose parameters itself that uses them. 

What is the environment configuration is required to make it work via proxy. We have tried with http_proxy and https_proxy environment variable set, ie proxy and winhttp proxy.

### PR DESCRIPTION
**Pull request by PlagueHO**
- Fixes #122 
- Fixes #120 

This PR contains the following changes:
```
* xRemoteFile: Added parameters:
                - TimeoutSec
                - ProxyURI
                - ProxyCredential
               Added unit tests.
               Corrected Style Guidelines issues.
               Added Localization support.
               URI parameter supports File://.
               Get-TargetResource returns URI parameter.
               Fixed logging of error message reported when download fails.
* Examples: Fixed missing newline at end of PullServerSetupTests.ps1.
* xFileUpload: Added PSSA rule suppression attribute.
* xPackageResource: Removed hardcoded ComputerName 'localhost' parameter from Get-WMIObject to eliminate PSSA rule violation. The parameter is not required.
* Added .gitignore to prevent DSCResource.Tests from being commited to repo.
* Updated AppVeyor.yml to use WMF 5 build OS so that latest test methods work.
```

The key purpose of this PR was to resolve issues #122 and #120. However, this resource violated many current Style Guidliness and didn't contain unit or integration tests. So in order to bring it up to current standards and allow it to be commited I had to update it as well as create unit and integration tests. This also exposed various other PSSA violations that therefore also had to be fixed. Also, AppVeyor had to be updated to use a WMF5 machine to support the current unit tests and integration test methods.

**Note**: There is still a PSSA violation that is occurring in the ```MSFT_xFileUpload.schema.psm1``` which is preventing a successful build. This **should** have been resolved by including the attribute:
```powershell
[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingConvertToSecureStringWithPlainText", "")]
```
in the Configuration, but after investigation, this only works for Functions. I believe this is an issue with Pester and have logged it here: https://github.com/PowerShell/PSScriptAnalyzer/issues/523

I could work around this PSSA violation by changing the secure string generation code to something that doesn't set off the PSSA rule, but this I think is a bad idea. It would be better to wait for a fix for Pester.

@riponbanik , @asmagin , if you need this fix before Pester is updated and this PR is merged, you could use my build of the resource (here https://github.com/PlagueHO/xPSDesiredStateConfiguration/tree/Fix/122-Support-Proxy), but I'd recommend waiting for it to be merged and released via PSGallery.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/123)

### CODE REVIEW

**Comment by KarolKaczmarek** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1, line 129 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KHMh8N6pPqW0s3aILBG:-KHMh8N6pPqW0s3aILBH:1744240512) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/dd9bebb0fcbe08355fc18060bf375e3f58c85de5/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1#L129)):*
> ```PowerShell
> 
>         [System.String]
>         $ProxyUri,
> ```

Looks like you are passing it later to Invoke-WebRequest via @PSBoundParameters but Invoke-WebRequest accepts Proxy, not ProxyUri

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123)*

**Comment by KarolKaczmarek** [comment]
I also pinged the PSSA team about the issue you've filed.

**Comment by PlagueHO** [comment]
Awesome! Thanks @KarolKaczmarek

<details><summary><i>Previously, KarolKaczmarek wrote…</i></summary>
> I also pinged the PSSA team about the issue you've filed.</details>


---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1, line 129 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KHMh8N6pPqW0s3aILBG:-KHMs9J2yeuEn7bqlS5d:1270178213) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/dd9bebb0fcbe08355fc18060bf375e3f58c85de5/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1#L129)):*
<details><summary><i>Previously, KarolKaczmarek wrote…</i></summary>
> Looks like you are passing it later to Invoke-WebRequest via @PSBoundParameters but Invoke-WebRequest accepts Proxy, not ProxyUri</details>
That is a good catch. Thanks for reviewing and noticing that! Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-:-KHMruYdTXapTiOdF8k0:1739382596)*

**Comment by KarolKaczmarek** [comment]
They added it to 1605 milestone, should be fixed soon

**Comment by riponbanik** [comment]
Hi Guys. is this merged yet. if not @PlagueHO which repo shall i clone to get your change

**Comment by PlagueHO** [comment]
Hi @riponbanik  - still waiting on the Pester changes at the moment. But you can give my branch a try if you want. You'll find it here:

https://github.com/PlagueHO/xPSDesiredStateConfiguration/tree/Fix/122-Support-Proxy

I'd recommend that you only use it for testing and wait for the official version to use in production.

**Comment by PlagueHO** [comment]
Edit: I mean PSSA changes - not Pester.

**Comment by KarolKaczmarek** [comment]
PR is pending though so we should see it merged soon https://github.com/PowerShell/PSScriptAnalyzer/pull/529

**Comment by riponbanik** [comment]
Thanks @PlagueHO, I tried but still it says that the module does not accept proxy. I suppose the parent module xPSDesiredStateConfiguration may have something in reference that we need to change as well.

**Comment by PlagueHO** [comment]
@riponbanik - PR https://github.com/PowerShell/PSScriptAnalyzer/pull/529 for PSSA has been merged now so this shouldn't be long. Just need to wait for the new release to PS Gallery. 

Regarding my branch, you might need to remove any existing copies of the xPSDesiredStateConfiguration module you have floating around.

**Comment by TravisEz13** [comment]
Reviewed 7 of 12 files at r1, 2 of 3 files at r2.
Review status: 9 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[README.md, line 74 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KIjPZD0RVbZ3LBw53yV:-KIjPZD0RVbZ3LBw53yW:-1013960324) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/b95d100b594df43766b533bdbdcefecbead02d12/README.md#L74)):*
> ```Markdown
> * **MatchSource**: Determines whether the remote file should be re-downloaded if file in the DestinationPath was modified locally. Optional.
> * **TimeoutSec**: Specifies how long the request can be pending before it times out. Optional.
> * **Proxy**: Uses a proxy server for the request, rather than connecting directly to the Internet resource. Optional.
> ```

describe the allowed format

---

*[DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1, line 269 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KIjOd7TMILNpRO0pVdF:-KIjOd7UQ9b5fdZrj8T-:179089286) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/a3bf5e183d980fbb42b71d78dfe67310f186bf59/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L269)):*
> ```PowerShell
> 
>         #if 64bit OS, check 64bit registry view first
>         if ((Get-WmiObject -Class Win32_OperatingSystem -ComputerName "localhost" -ea 0).OSArchitecture -eq '64-bit')
> ```

Why are you specifying computername?

---

*[DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.schema.mof, line 12 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KIjPOh_fcniSv2HJXhp:-KIjPOh_fcniSv2HJXhq:-1013960324) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/b95d100b594df43766b533bdbdcefecbead02d12/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.schema.mof#L12)):*
> ```
>     [Write, Description("A boolean value to indicate whether the remote file should be re-downloaded if the file in the DestinationPath was modified locally.")] Boolean MatchSource;
>     [Write, Description("Specifies how long the request can be pending before it times out.")] Uint32 TimeoutSec;
>     [Write, Description("Uses a proxy server for the request, rather than connecting directly to the Internet resource.")] String Proxy;
> ```

describe the allowed format

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123)*

**Comment by PlagueHO** [comment]
@TravisEz13 - I've also added another sample showing xRemoteFile usage with a Proxy to make it a bit clearer. Cheers! Now if only we could get the release of the new PSSA - the fix went into the 1605 sprint - but that sprint is still only 50% complete.

<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> @riponbanik - PR https://github.com/PowerShell/PSScriptAnalyzer/pull/529 for PSSA has been merged now so this shouldn't be long. Just need to wait for the new release to PS Gallery. 
> 
> 
> 
> Regarding my branch, you might need to remove any existing copies of the xPSDesiredStateConfiguration module you have floating around, otherwise DSC might use the older one.
</details>


---

Review status: 9 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[README.md, line 74 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KIjPZD0RVbZ3LBw53yV:-KIoFTG26xR4FUGVrctb:-499146009) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/b95d100b594df43766b533bdbdcefecbead02d12/README.md#L74)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> describe the allowed format
</details>
Done.

---

*[DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1, line 269 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KIjOd7TMILNpRO0pVdF:-KIoFGQp7W6cLZ9c-d_z:1005810887) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/a3bf5e183d980fbb42b71d78dfe67310f186bf59/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L269)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> Why are you specifying computername?
</details>
I didn't - I removed it (it was triggering a PSSA rule violation).

---

*[DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.schema.mof, line 12 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KIjPOh_fcniSv2HJXhp:-KIoFRMXT77xrZAWLZtq:-499146009) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/b95d100b594df43766b533bdbdcefecbead02d12/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.schema.mof#L12)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> describe the allowed format
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-:-KIoFU2nXzP-0kkAKqp3:1149497454)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 12 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 72 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KIzApkOZLOEKJqrrHs6:-KIzApkOZLOEKJqrrHs7:-363290278) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/b95d100b594df43766b533bdbdcefecbead02d12/README.md#L72)):*
> ```Markdown
> * **Headers**: Headers of the web request. Optional.
> * **Credential**: Specifies credential of a user which has permissions to send the request. Optional.
> * **MatchSource**: Determines whether the remote file should be re-downloaded if file in the DestinationPath was modified locally. Optional.
> ```

Please resolve all merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )
[Instructions to setup BC4, my favorite merge tool](http://www.scootersoftware.com/support.php?zz=kb_vcs#gitwindows)

tests are failing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123)*

**Comment by PlagueHO** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 72 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KIzApkOZLOEKJqrrHs6:-KJ4h7CTluMX2JBzv2JG:1485127506) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/b95d100b594df43766b533bdbdcefecbead02d12/README.md#L72)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> Please resolve all merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )
> [Instructions to setup BC4, my favorite merge tool](http://www.scootersoftware.com/support.php?zz=kb_vcs#gitwindows)
> 
> tests are failing
> 
</details>
Have resolved merge conflicts.

I'm aware of the test failures - they'll continue to fail until build 1605 of PSSA is released to allow suppressing of PSSA rules in DSC config files. Once PSSA 1605 is released (soon hopefully) I'll trigger a dummy commit so that a rebuild goes through.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123)*

**Comment by PlagueHO** [comment]
Now that PSSA 1.6.0 has been released I've fixed the merge conflicts in this PR. I also noticed that the version numbers in the Readme.md were all messed up: it referenced v4.0.0.0 and v3.11.0.0, both of which have not been released yet (no tag, not available on PS Gallery, not pushed to master). I've moved the items that appeared under these non-existent versions into # Unreleased.

**Comment by kwirkykat** [comment]
Thank you for fixing the README :smiley:  That will save me a lot of hassle in the next release.

<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Now that PSSA 1.6.0 has been released I've fixed the merge conflicts in this PR. I also noticed that the version numbers in the Readme.md were all messed up: it referenced v4.0.0.0 and v3.11.0.0, both of which have not been released yet (no tag, not available on PS Gallery, not pushed to master). I've moved the items that appeared under these non-existent versions into # Unreleased. 
</details>


---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1, line 204 \[r4\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KJl9mIy6z9HSVbQv6fw:-KJl9mIzHAgvTekS6lPL:-575757887) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/3a04f99e4c2258b19824a42074b3706ca661c2bc/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1#L204)):*
> ```PowerShell
> 
>     # Convert headers to hashtable
>     $null = $PSBoundParameters.Remove("Headers")
> ```

Why are you assigning to $null instead of piping to Out-Null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-:-KJlAUNerwLzaJ50aoZq:-1490033847)*

**Comment by kwirkykat** [comment]
:lgtm:

<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Thank you for fixing the README :smiley:  That will save me a lot of hassle in the next release.
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1, line 204 \[r4\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-KJl9mIy6z9HSVbQv6fw:-KJlGyO77cZkVVkIo1FT:-892435600) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/3a04f99e4c2258b19824a42074b3706ca661c2bc/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1#L204)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Why are you assigning to $null instead of piping to Out-Null?
</details>
In case anyone else is wondering, apparently piping to Out-Null takes more time and has more overhead. This is just one of the several alternatives.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/123#-:-KJlH80kx5JFuswbujax:1417088721)*

**Pull request merged**
