### PR TITLE
Update xRegistry resource to fix PSSA and style issues

### LINKED ISSUE #134: MSFT_xRegistryResource: Fix PSSA Issues
The PowerShell Script Analyzer issues in MSFT_xRegistryResource need to be fixed.
This is the current result of running Invoke-ScriptAnalyzer:
image

### PR DESCRIPTION
**Pull request by Dan1el42**
1. Fix #134 PSSA and style issues
2. Renamed internal functions to follow verb-noun format
3. Decorated all functions with comment-based help
4. Updated Unreleased section of README.md

Script Analyzer
- Before
image

- After
image

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/207)

### CODE REVIEW

**Comment by kwirkykat** [comment]
This resource has not yet been merged with it's in-box version.
Come of your changes may be overwritten when that occurs, but I will try my best to keep them in.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 21 unresolved discussions.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 3 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqb3EJH-Mi2nGUoRU3:-KQqb3EJH-Mi2nGUoRU4:bhrjflx) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L3)):*
> ```PowerShell
> # This PS module contains functions for Desired State Configuration (DSC) Registry provider.
> # It enables querying, creation, removal and update of Windows registry keys through
> # Get, Set and Test operations on DSC managed nodes.
> ```

Can you please change this multi-line comment to use the <# ... #> format instead as per [this section](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-comments) of the style guidelines?

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 71 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqbo22lmdPxSXtsVyt:-KQqbo22lmdPxSXtsVyu:btufg86) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L71)):*
> ```PowerShell
>     Invoke-RegistryProviderSetup -KeyName ([ref]$Key)
> 
>     $ValueNameSpecified = $PSBoundParameters.ContainsKey('ValueName')
> ```

$ValueNameSpecified should not be capitalized as it is not a parameter

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 90 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqc-NjEuKAzC0B4CVN:-KQqc-NjEuKAzC0B4CVO:bhrjflx) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L90)):*
> ```PowerShell
> 
>     # If $ValueName parameter has not been specified
>     # then we simply report success on finding the $Key
> ```

Can you please change this multi-line comment to use the <# ... #> format instead as per [this section](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-comments) of the style guidelines?

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 99 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqc1eEARMrJfuxds1c:-KQqc1eEARMrJfuxds1d:bhrjflx) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L99)):*
> ```PowerShell
> 
>     # If the control reaches here, the $ValueName has been specified as a parameter
>     # and we should query it now
> ```

Can you please change this multi-line comment to use the <# ... #> format instead as per [this section](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-comments) of the style guidelines?

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 111 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqcDZMHnn2egxYgTtX:-KQqcDZMHnn2egxYgTtY:b-ty8xm2) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L111)):*
> ```PowerShell
>             Ensure='Absent'
>             Key=$Key
>             ValueName=(Get-ValueDisplayName -ValueName $ValueName)
> ```

There should be spaces surrounding all equal signs in this hash table

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 134 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqcTyUoUNXuxgtlBce:-KQqcTyUoUNXuxgtlBcf:bhrjflx) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L134)):*
> ```PowerShell
> 
>     # If the control reaches here, both the $Key and the $ValueName have been found,
>     # query is fully successful
> ```

Can you please change this multi-line comment to use the <# ... #> format instead as per [this section](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-comments) of the style guidelines?

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 182 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqcag9tRBCRD5grQUo:-KQqcag9tRBCRD5grQUp:btdor2g) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L182)):*
> ```PowerShell
> 
>         # Special-case: Used only as a boolean flag (along with ValueType) to determine
>         # if the target entity is the Default Value or the key itself.
> ```

Can you please change this multi-line comment to use the <# ... #> format instead as per this section of the style guidelines?

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 187 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqcmSTzC6jb2MmEaQr:-KQqcmSTzC6jb2MmEaQs:bhrjflx) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L187)):*
> ```PowerShell
> 
>         # Special-case: Used only as a boolean flag (along with ValueData) to determine
>         # if the target entity is the Default Value or the key itself.
> ```

Can you please change this multi-line comment to use the <# ... #> format instead as per [this section](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-comments) of the style guidelines?

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 362 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqdB6ttSuncbTbmP8W:-KQqdB6ttSuncbTbmP8X:b-mc5238) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L362)):*
> -eq
-ne

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 424 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqdpqD2-xshgVTknhz:-KQqdpqD2-xshgVTkni-:b47gbuk) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L424)):*
> ```PowerShell
>                 Write-Log $errorMessage
> 
>                 $params = @{
> ```

$params need a more descriptive name

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 845 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqesIB559BALj6VyP6:-KQqesIB559BALj6VyP7:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L845)):*
> ```PowerShell
>     {
>         $errorMessage = $localizedData.InvalidPSDriveSpecified -f $psDriveName, $Key
>         $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1005 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqf64Er4P858fIihuo:-KQqf64Er4P858fIihup:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1005)):*
> ```PowerShell
>             (Convert-ArrayToString -Value $Data), $Type
>         Write-Verbose $errorMessage
>         $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1019 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqf8KwLzmaBHd2OQST:-KQqf8KwLzmaBHd2OQSU:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1019)):*
> ```PowerShell
>     if (($Type -ine 'Multistring') -and ($null -ne $Data) -and ($Data.Count -gt 1))
>     {
>         $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1086 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqfE9eOmNT1MVwyuid:-KQqfE9eOmNT1MVwyuie:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1086)):*
> ```PowerShell
>                 else
>                 {
>                     $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1118 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqfGHD28a_AWJ8eSXb:-KQqfGHD28a_AWJ8eSXc:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1118)):*
> ```PowerShell
>                 else
>                 {
>                     $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1160 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqfJ2SDTpJL68QpR3Z:-KQqfJ2SDTpJL68QpR3_:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1160)):*
> ```PowerShell
>             catch [Exception]
>             {
>                 $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1230 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqfQYa1YbDJK_6Uzbw:-KQqfQYa1YbDJK_6Uzbx:b-nkufqb) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1230)):*
> to handle
to retrieve

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1233 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqfWBgNgCGX8MR6eEB:-KQqfWBgNgCGX8MR6eEC:b-fxwakj) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1233)):*
> Specifies the value name to be handled.
Specifies the name of the value to be retrieved

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1270 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqffSfYQirWOB7NfH9:-KQqffSfYQirWOB7NfHA:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1270)):*
> ```PowerShell
>     $psDriveNames = (Get-PSDrive).Name.ToUpperInvariant()
> 
>     $params = @{
> ```

$params needs a more descriptive name

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1302 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqfmAD6Tmwb5pkXxl6:-KQqfmAD6Tmwb5pkXxl7:b-3gqvfq) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1302)):*
> ```PowerShell
> 
>     .PARAMETER KeyName
> ```

Missed the parameter description here

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 1339 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqfyV9nrx0nDhGpdbv:-KQqfyV9nrx0nDhGpdbw:b3nfenh) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L1339)):*
> ```PowerShell
>             $errorMessage = $localizedData.InvalidRegistryHiveSpecified -f $Key
> 
>             $params = @{
> ```

$params needs a more descriptive name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-:-KQqbX_l7djZ7d5r7SnX:b-j09cgm)*

**Comment by Dan1el42** [comment]
Are you sure that the in-box version of the Registry resource hasn't been merged yet?

I am asking because a diff of the xRegistry resource before my modification with the Registry resource in the PSDesiredStateConfiguration module on my Windows 10 AU machine looks almost identical.

I've updated the PR with another commit to reflect the requested changes. You'll find a couple of additional style and consistency changes in revision 2 because I gave the code another once-over due to your valid comments for revision 1.

---

Review status: 1 of 2 files reviewed at latest revision, 21 unresolved discussions.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 362 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KQqdB6ttSuncbTbmP8W:-KQtIatwIxcXrfvtHtb6:bstkmv3) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/c9cadfd0f90828b5ec826452ec099c931da7160d/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L362)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > -eq
> -ne
</details>
Good catch :-). Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-:-KQtWFwrmdk4NHepc20T:bjmjh6w)*

**Comment by kwirkykat** [comment]
@Dan1el42 Yup. Registry hasn't been merged yet. It's listed as in progess [here](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/HighQualityResourceModulePlan.md#progress). 
I ran a diff with our code (may have some changes not yet pushed out to general public) and there only seems to beonly a few lines that have any significant changes between the in-box and open-source, so I can definitely include your changes in the merged version.

Updates look great :+1: Just a couple last wording changes and fixing merge conflicts in the README and then this is good to go.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 257 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KR03obBuBMXI8-xqUJL:-KR03obCNZDBLJRLC1qF:bnrkvro) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/b5590e60d47defbf0eba07dcc4ee97b599d6ba3c/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L257)):*
> Indicates if the key and value exist.
Indicates if the key and value should exist.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 557 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KR04LbJtApv46yZiivP:-KR04LbJtApv46yZiivQ:bnrkvro) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/b5590e60d47defbf0eba07dcc4ee97b599d6ba3c/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L557)):*
> Indicates if the key and value exist.
Indicates if the key and value should exist.

---

*[DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1, line 559 \[r2\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-KR04OzkfGpfhfzm7kTI:-KR04OzlIuTla_kGswy-:b-7fybno) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/b5590e60d47defbf0eba07dcc4ee97b599d6ba3c/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1#L559)):*
> To ensure that they do, set this property to "Present".
> To ensure that they do not exist, set the property to "Absent".

To test that they exist, set this pro...
To test that they do not exist, set this pro...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-:-KR02gSyPiGZ17vlWo8Y:bdwteo6)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/207#-:-KR4sWhiBZFHKJaWZ2wj:bnfp4nl)*

**Pull request merged**
