### PR TITLE
Updated documentation for use of "AllowUnencryptedTraffic" as CertificateThumbprint parameter value.

### LINKED ISSUE #116: xDSCWebService documentation needs update for AllowUnencryptedTraffic
While setting up Pull Server, if the user does not want to set up SSL, they can specify "AllowUnencryptedTraffic" as the value for the certificate thumbprint parameter. This information needs to be documented in the sample.

### PR DESCRIPTION
**Pull request by Indhukrishna**
Resolve #116

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/117)

### CODE REVIEW

**Comment by TravisEz13** [comment]
@berheabrha  Can you review this is your area?
@indhukrishna Talk to me about how to fix the CLA

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.Schema.mof, line 5 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/117#-KFzUGpwDXJ7V2_mkIJ7:-KFzUGpwDXJ7V2_mkIJ8:534909825) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/e2ad8bd245fb0d260a75ea0176e06003afbc74d3/DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.Schema.mof#L5)):*
should use description attribute, not comment example
`[key, Description("...")]`

---

*[Examples/Sample_xDscWebService.ps1, line 12 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/117#-KFzUZkmZctzQG5eztfK:-KFzUZkmZctzQG5eztfL:-180591490) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/e2ad8bd245fb0d260a75ea0176e06003afbc74d3/Examples/Sample_xDscWebService.ps1#L12)):*
Should use `[Parameter(HelpMessage='...')]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/117#-:-KFzUMdd8QG2lkCOan8I:-680658306)*

**Comment by TravisEz13** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/117)*

**Comment by Indhukrishna** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.Schema.mof, line 5 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/117#-KFzUGpwDXJ7V2_mkIJ7:-KGEY5-RKtE3dzEy0QRg:-499146009) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/e2ad8bd245fb0d260a75ea0176e06003afbc74d3/DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.Schema.mof#L5)):*
Done.

---

*[Examples/Sample_xDscWebService.ps1, line 12 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/117#-KFzUZkmZctzQG5eztfK:-KGEY6IZhsFNdIN9Kd3C:-499146009) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/e2ad8bd245fb0d260a75ea0176e06003afbc74d3/Examples/Sample_xDscWebService.ps1#L12)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/117)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/117)*

**Pull request merged**
