### PR TITLE
Bulk Update: Replace Type Accelerators with Fully Qualified Type Names

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Replaces Type Accelerators with Fully Qualified Type Names

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as
      appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/556)

### CODE REVIEW

**Comment by mhendric** [comment]
@PlagueHO , I think this one is ready for review. Careful what you wish for :)

@tmeckel , this one is probably going to be fun to rebase with your DSCWebService changes. If you feel you're close to finishing, we can delay checking in this PR until yours has been checked in, and then I'll do the rebase on this one. Just let me know.

**Comment by mhendric** [comment]
Also, @PlagueHO , I left out a bunch of the 'System.Management.Automation' based type accelerators that are also attributes (like CmdletBinding, Parameter, ValidateNotNullOrEmpty, etc). I wasn't sure if we were going that far or not. Let me know what you think we should do.

```
Key                          Value
---                          -----
Alias                        System.Management.Automation.AliasAttribute
AllowEmptyCollection         System.Management.Automation.AllowEmptyCollectionAttribute
AllowEmptyString             System.Management.Automation.AllowEmptyStringAttribute
AllowNull                    System.Management.Automation.AllowNullAttribute
ArgumentCompleter            System.Management.Automation.ArgumentCompleterAttribute
array                        System.Array
bool                         System.Boolean
byte                         System.Byte
char                         System.Char
CmdletBinding                System.Management.Automation.CmdletBindingAttribute
datetime                     System.DateTime
decimal                      System.Decimal
double                       System.Double
DscResource                  System.Management.Automation.DscResourceAttribute
float                        System.Single
single                       System.Single
guid                         System.Guid
hashtable                    System.Collections.Hashtable
int                          System.Int32
int32                        System.Int32
int16                        System.Int16
long                         System.Int64
int64                        System.Int64
ciminstance                  Microsoft.Management.Infrastructure.CimInstance
cimclass                     Microsoft.Management.Infrastructure.CimClass
cimtype                      Microsoft.Management.Infrastructure.CimType
cimconverter                 Microsoft.Management.Infrastructure.CimConverter
IPEndpoint                   System.Net.IPEndPoint
NullString                   System.Management.Automation.Language.NullString
OutputType                   System.Management.Automation.OutputTypeAttribute
ObjectSecurity               System.Security.AccessControl.ObjectSecurity
Parameter                    System.Management.Automation.ParameterAttribute
PhysicalAddress              System.Net.NetworkInformation.PhysicalAddress
pscredential                 System.Management.Automation.PSCredential
PSDefaultValue               System.Management.Automation.PSDefaultValueAttribute
pslistmodifier               System.Management.Automation.PSListModifier
psobject                     System.Management.Automation.PSObject
pscustomobject               System.Management.Automation.PSObject
psprimitivedictionary        System.Management.Automation.PSPrimitiveDictionary
ref                          System.Management.Automation.PSReference
PSTypeNameAttribute          System.Management.Automation.PSTypeNameAttribute
regex                        System.Text.RegularExpressions.Regex
DscProperty                  System.Management.Automation.DscPropertyAttribute
sbyte                        System.SByte
string                       System.String
SupportsWildcards            System.Management.Automation.SupportsWildcardsAttribute
switch                       System.Management.Automation.SwitchParameter
cultureinfo                  System.Globalization.CultureInfo
bigint                       System.Numerics.BigInteger
securestring                 System.Security.SecureString
timespan                     System.TimeSpan
uint16                       System.UInt16
uint32                       System.UInt32
uint64                       System.UInt64
uri                          System.Uri
ValidateCount                System.Management.Automation.ValidateCountAttribute
ValidateDrive                System.Management.Automation.ValidateDriveAttribute
ValidateLength               System.Management.Automation.ValidateLengthAttribute
ValidateNotNull              System.Management.Automation.ValidateNotNullAttribute
ValidateNotNullOrEmpty       System.Management.Automation.ValidateNotNullOrEmptyAttribute
ValidatePattern              System.Management.Automation.ValidatePatternAttribute
ValidateRange                System.Management.Automation.ValidateRangeAttribute
ValidateScript               System.Management.Automation.ValidateScriptAttribute
ValidateSet                  System.Management.Automation.ValidateSetAttribute
ValidateTrustedData          System.Management.Automation.ValidateTrustedDataAttribute
ValidateUserDrive            System.Management.Automation.ValidateUserDriveAttribute
version                      System.Version
void                         System.Void
ipaddress                    System.Net.IPAddress
DscLocalConfigurationManager System.Management.Automation.DscLocalConfigurationManagerAttribute
WildcardPattern              System.Management.Automation.WildcardPattern
X509Certificate              System.Security.Cryptography.X509Certificates.X509Certificate
X500DistinguishedName        System.Security.Cryptography.X509Certificates.X500DistinguishedName
xml                          System.Xml.XmlDocument
CimSession                   Microsoft.Management.Infrastructure.CimSession
adsi                         System.DirectoryServices.DirectoryEntry
adsisearcher                 System.DirectoryServices.DirectorySearcher
wmiclass                     System.Management.ManagementClass
wmi                          System.Management.ManagementObject
wmisearcher                  System.Management.ManagementObjectSearcher
mailaddress                  System.Net.Mail.MailAddress
scriptblock                  System.Management.Automation.ScriptBlock
psvariable                   System.Management.Automation.PSVariable
type                         System.Type
psmoduleinfo                 System.Management.Automation.PSModuleInfo
powershell                   System.Management.Automation.PowerShell
runspacefactory              System.Management.Automation.Runspaces.RunspaceFactory
runspace                     System.Management.Automation.Runspaces.Runspace
initialsessionstate          System.Management.Automation.Runspaces.InitialSessionState
psscriptmethod               System.Management.Automation.PSScriptMethod
psscriptproperty             System.Management.Automation.PSScriptProperty
psnoteproperty               System.Management.Automation.PSNoteProperty
psaliasproperty              System.Management.Automation.PSAliasProperty
psvariableproperty           System.Management.Automation.PSVariableProperty

```

**Comment by mhendric** [comment]
Looks like at least xRegistry doesn't like having [ref] converted to [System.Management.Automation.PSReference]. I'll have to do some troubleshooting on this later this weekend.

**Comment by PlagueHO** [comment]
No worries - maybe leave [ref] as is (although using [ref] is usually an indicator of design issues).

**Comment by tmeckel** [comment]
@mhendric I just rebased my PR #507 to the latest dev commits with no issues (conflicts). So I guess the changes here haven't been merged into the dev branch. Right? In the meanwhile I saw that you created 34 (!) comments on my PR. I've to see if I can go through all of them over the weekend. Seems not likely though. So before my PR gets a blocker for merging those changes in this PR, go and merge them. I'll cope with the potential conflicts then :-D 

oh, by the way: why are those changes are required? I know there're issues with those aliases, like with creating an new PSObject from a hashtable via `[pscustomobject]`which doesn't work with `[psobject]`, but are there any other reasons why this PR exists?

**Comment by mhendric** [comment]
@PlagueHO , I think this one is ready for a code review again. Thanks.

@tmeckel , this PR is mostly designed to standardize type declarations throughout the module, help prevent conflicting type accelerators, and fix wrong case of letters in types. That being said, if we don't make an actual policy that type accelerators aren't allowed, this module is probably going to eventually drift back into an inconsistent state. Perhaps we should agree on a standard first and get it documented. Or alternately agree that maybe this isn't worth the effort. What do you guys think?

**Comment by tmeckel** [comment]
Oh okay now I understand the motivation about this PR. Thanks for the clarifacation @mhendric . I do agree that there might be subtle differences between how the aliases work and therefore it could be useful to remove them from the existing code. But as you said there must be some comments on this in the contribute.md stating that aliases are not allowed inside this module. The probable issue I see might be the fact that people abandon their PR after review or never submit a PR when there are too many rules to follow, because this might let the project look like it's ruled by pedantic people *LOL* Don't get me wrong I'm the last that don't understand the importance of coding rules but I learned over the last decades that when you overdo it, it won't help anyone.

**Comment by tmeckel** [comment]
Oh one more thing @mhendric  ... in the current style guidelines https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md you'll find examples using `[string]` instead of `[System.String]` all over the place. So this has to be changed when this PR is merged I guess.

**Comment by mhendric** [comment]
Yeah maybe this one is going too far. Although I do like the idea of at least requiring consistent casing (i.e. [String] vs. [string]). But maybe we should bring these ideas as a discussion over to the DSC Style Guidelines first and get community consensus.

**Comment by tmeckel** [comment]
I totally agree with the casing and as I said there are some pitfalls using alias (accelerator), so we should definitly have a broaded discussion about how and if they shoould be used. Not only in this particular module but throughout all DSC modules. I would like to hear @johlju opinion on this for example.

Oh and I "fixed" 25 of your reviews on my PR #507 :-D only 9 to go ... but those relate to the Unit Tests. Important I know but harder to cope with as with those style guides things.

**Comment by tmeckel** [comment]
Oh and about adhering to the coding and style guides: will it be feasible to have a VSCode "addin" or somthing that will help people to "correctly contribute".

**Comment by mhendric** [comment]
That would be awesome to have a VSCode plugin that automatically detected and fixed style violations. It would also be cool if we had some custom script analyzer rules for violations. That would at least allow us to have the issues flagged during testing, and take the onus off the reviewers for hunting down style violations.

**Comment by PlagueHO** [comment]
We already have VSCode detecting some of the style violations and have issues open to add more. You should already be getting underlining for some of custom style rules in VSCode (eg param formats).

**Comment by tmeckel** [comment]
@PlagueHO yes I realized this already because as @mhendric and me were talking, I saw that VSCode informed my about some of the style violations that @mhendric commented in his review. So in the end we must enhance `.\DSCResource.Tests\DscResource.AnalyzerRules` to include all important recommendations from the DSC style guide. However the PSAnalyzer rules in `DSCResource.Tests\DscResource.AnalyzerRules` are not a submodule currently, but they should be though, so that every DSC module can use them.

**Comment by PlagueHO** [comment]
We should probably have this discussion over at DSCResources. I'd prefer not using type accelerators, but as you all rightly point out: enforcing this suddenly accumulates a _lot_ of tech debt across all repos. But also, if we don't enforce it with PSSA rules etc then these repos will just drift back.

But I still think it would be worthwhile completing making this repo consistent.

My main goal is to get consistency within a repo - but it was pretty mixed within this one.

@tmeckel - All DSC modules can use the custom rules. I use them in all the ones I maintain. Pretty sure @johlju does too. Every module uses DSCResource.Tests I think.

**Comment by tmeckel** [comment]
@plagueho the advantage if having the custom rules in a separate GIT module would be the fact that every DSC module would benefit from improvements and addons to it without having to manually import them into each module and as we're talking about drift... A submodule would guarantee that every DSC module is using the same rules. And on top the module could be overseen by a maintainer.

**Comment by PlagueHO** [comment]
Oh, right - thought you meant PS Module rather than Git Submodule.

The problem with using Git Submodules though is that they don't point to head - they point to a specific commit. This means every maintainer would have to continuously update the .GitSubmodule file every time the rules update - which really is not likely to happen in many cases (I know I'd forget - just another thing for me to do across the 10+ modules I maintain). And many of the other modules haven't yet managed to meet HQRM standards, so getting them to adopt these rules should maybe start with getting them to HQRM - then it becomes much easier to tweak rules and so on.

I think empowering maintainers is great, but as many repos and maintainers are struggling under the load already, if we add a requirement to continuously update the external style rule modules within their own repos then it'll just not happen. I for one really don't want to add this to any of the modules I maintain.

But I'm not sure it is even necessary because maintainers can opt-in and out of specific PSSA rules by controlling the ScriptAnalyzer.psd1 file in their own repos. We also have the .MetaTestOptIn file to enable maintainers to opt  in to some of more powerful rules when they choose to.

I might of course misunderstand the problem that needs to be solved here :grin: So, I apologize if that is the case :grin:

**Comment by PlagueHO** [comment]
@tmeckel - one thing I should add: We definitely don't want everyone adding DSCResource.Tests into their module repos directly - this was never the intent - and hopefully no one is doing this :grin:. It is currently Git Cloned when tests are run and updated every time the tests are run (which is why we're quite keen to ensure it is always updated on each users machine in every repo).

**Comment by tmeckel** [comment]
Lol 😂 damn you're right... That explains why VSCode started to show issues with the code AFTER I run tge Unit tests tge first time... Shame on me... Bwahahahahahahaaaa 😂

**Comment by PlagueHO** [comment]
@tmeckel - you wouldn't be the first to do this - I do this regularly myself :cry:. Ideally we'd have a way to sort this when the module is cloned/updated - as you suggested, Submodules would be a good solution, but because it is pinned to a commit it would rarely be kept-up-to-date. But we couldn't come up with a good solution yet.

**Comment by tmeckel** [comment]
@PlagueHO I think the discussion I've started is a good example of not interfering in things that much more intelligent people than oneself have thought about. And TBH I wasn't aware of the fact that the DSCResource.Tests is pull every time the tests got run because I normally run my tests on a VM and not on the computer where I've installed my VSCode, except yesterday because I was in a small hurry to get some of the review stuff fixed from @mhendric. That resulted in the fact that VSCode "suddenly" showed "problems" in my code that relate to the DSC best practices.

After you mentioned the somewhat annoying issues with Git submodules (Subversions externals are so much better :-D) I thought about if subtrees could be a solutions. But they're not stored as metadata to the repo so every developer must add the subtree every time again when the repo got pulled the first time. Impractical and error prone! Than I remembered that Git as of 1.8.2 is able to track branches in submodules so the update to a new (head) version of a submodule is easy but again as you said the update must be manually done. Again error prone! 

But how about using the post-merge hook in Git which runs after each pull? Like so 

```powershell
PS> echo "git submodule update --init --recursive" >> .git/hooks/post-merge
```
This will update all submodules to the latest version automatically every time a pull is done. When we combine this with the ability of a submodule to track branches this could be a way to replace the current implementation of pulling the DSCResource.Tests only when tests run. Or, if we don't wanna go that far, we might separate the VSCode (PSScriptAnalyzer) stuff to a separate repo which is then included as submodule that is always present when the parent repo is pulled.

**Comment by tmeckel** [comment]
@PlagueHO sorry pestering you :-D but I made a proposal to use GIT hooks for managing submodules. Whats's your opinion about this?

https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/556#issuecomment-464454524

**Pull request merged**
