### PR TITLE
Enable CodeCov.io and fix breaks

### PR DESCRIPTION
**Pull request by TravisEz13**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/320)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@TravisEz13 Any idea why this update is crashing a bunch of different tests? Are the new common tests using a special strict mode or a crazy scope or something?

**Comment by TravisEz13** [comment]
@kwirkykat Not sure.  I rebased to your latest changes to make sure it wasn't fixed by one of those.

**Comment by johlju** [comment]
@TravisEz13 @kwirkykat When using the new appveyor model in xSQLServer I had to change so it imports the cmdlet stubs (mocked SQLPS module) using `-Global` as @TravisEz13 did in the User resource. But only when the tests are inside InModuleScope as far as I have seen. So the scope has changed in some way.

**Comment by TravisEz13** [comment]
This is dependent on https://github.com/PowerShell/DscResource.Tests/pull/125.  Please do not merge until this has been changed and I have removed the commits to clone or pull the private branch.

**Comment by TravisEz13** [comment]
@kwirkykat @mbreakey3 Can one of you take a look?

**Comment by kwirkykat** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[appveyor.yml, line 9 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/320#-Kdc2VYsbKw4GuY4PAvk:-Kdc2VYsbKw4GuY4PAvl:b-e0ef4z) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/36c1966e1f09acc79e6bea0e05796d12dfe74893/appveyor.yml#L9)):*
> $mainModuleFolder = ".\"

Also why not use $PSScriptRoot?

---

*[appveyor.yml, line 10 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/320#-Kdc2oDLOWc2ITX8OTCO:-Kdc2oDLOWc2ITX8OTCP:bhbdqad) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/36c1966e1f09acc79e6bea0e05796d12dfe74893/appveyor.yml#L10)):*
> Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"

Unnamed parameter (add -Name)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/320)*

**Comment by TravisEz13** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[appveyor.yml, line 9 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/320#-Kdc2VYsbKw4GuY4PAvk:-Kdc8hX32VACWTUA-n0R:b-nef13k) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/36c1966e1f09acc79e6bea0e05796d12dfe74893/appveyor.yml#L9)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> $mainModuleFolder = ".\"

Also why not use $PSScriptRoot?
</blockquote></details>

There won't be a $PSScriptRoot unless we run a script (`.ps1` or `.psm1`)

---

*[appveyor.yml, line 10 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/320#-Kdc2oDLOWc2ITX8OTCO:-Kdc96dJrfCKk9CJYPQ6:b-896fjx) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/36c1966e1f09acc79e6bea0e05796d12dfe74893/appveyor.yml#L10)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"

Unnamed parameter (add -Name)
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/320)*

**Comment by TravisEz13** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[appveyor.yml, line 9 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/320#-Kdc2VYsbKw4GuY4PAvk:-KdcB-qj-q22kFzBTqFo:bcurz6v) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/36c1966e1f09acc79e6bea0e05796d12dfe74893/appveyor.yml#L9)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary><blockquote>

There won't be a $PSScriptRoot unless we run a script (`.ps1` or `.psm1`)
</blockquote></details>

Removed it since the default is the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/320)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/320#-:-KdcC_5HSV4xi7V_Q2a6:bnfp4nl)*

**Pull request merged**
