### PR TITLE
Add markdown lint

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Add .markdownlint.json file using settings from [here](https://raw.githubusercontent.com/PowerShell/SqlServerDsc/dev/.markdownlint.json) as a starting point.

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as
      appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/576)

### CODE REVIEW

**Comment by mhendric** [comment]
@PlagueHO , I'll leave this one for you to merge since it's my PR and someone else did the code review. Thanks.

**Comment by PlagueHO** [comment]
Hi @ykuijs - could you resolve conflicts?

**Comment by mhendric** [comment]
@PlagueHO , I'll resolve the conflicts since it's my PR (@ykuijs just did the review). Thanks.

**Comment by PlagueHO** [comment]
@mhendric - doh! Needs another resolve. Actually, if we always put new CHANGELOG entries just below the # Unreleased header then this doesn't happen. I usually forget though and put them at the bottom

**Comment by mhendric** [comment]
> Actually, if we always put new CHANGELOG entries just below the # Unreleased header then this doesn't happen. I usually forget though and put them at the bottom

Interesting, didn't know that. I tend to put them at the bottom as it seems to make more sense chronologically. Perhaps I need to look at this as a stack instead. That could be an alternate approach to #592 that I just opened. Although I'd personally prefer to just take this responsibility off the pull request submitter so as to reduce the number of failed code reviews just because of the change log.

**Pull request merged**
