### PR TITLE
updated unit tests and style fixes in xUserResource

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/238)

### CODE REVIEW

**Comment by Dan1el42** [comment]
Great work.

---

Reviewed 1 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xUserResource/MSFT_xUserResource.psm1, line 244 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238#-KRsnbl0zcBXev9spxgf:-KRsnbl0zcBXev9spxgg:b7rw758) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/90eaf5bf0a896c90143052f99c1f9989984a24bb/DSCResources/MSFT_xUserResource/MSFT_xUserResource.psm1#L244)):*
> ```PowerShell
>         .SYNOPSIS
>         The Set-TargetResource cmdlet on a full server.
>         .Notes
> ```

Please update to .NOTES for consistency reasons.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238#-:-KRspXQ1sSAxnMRIHc5B:b-9dwnyz)*

**Comment by mbreakey3** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xUserResource/MSFT_xUserResource.psm1, line 244 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238#-KRsnbl0zcBXev9spxgf:-KS3kUyiJNQ_yF8IvcYZ:b-601cx0) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/90eaf5bf0a896c90143052f99c1f9989984a24bb/DSCResources/MSFT_xUserResource/MSFT_xUserResource.psm1#L244)):*
<details><summary><i>Previously, Dan1el42 (Daniel Krebs) wrote…</i></summary>
> Please update to .NOTES for consistency reasons.
</details>
Done. - yeah, still working on fixing some of the style in this resource

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238)*

**Comment by eshaparmar** [comment]
Reviewed 2 of 5 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.schema.mfl, line 1 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238#-KSHqTyTviRsPwbCiOgo:-KSHqTyTviRsPwbCiOgp:b4f6dwa) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8428c3d6dd862c2c3b5896e2491895ca5b3cc64a/DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.schema.mfl#L1)):*
> ```
> [Description("This resource is used to enable and disable Windows optional features.") : Amended,AMENDMENT, LOCALE("MS_409")] 
> ```

There are no changes in this file, can we remove this from the pr?

---

*[Examples/Sample_xUser_CreateUser.ps1, line 1 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238#-KSHqeNQNzSUkB5juuZN:-KSHqeNQNzSUkB5juuZO:b4f6dwa) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8428c3d6dd862c2c3b5896e2491895ca5b3cc64a/Examples/Sample_xUser_CreateUser.ps1#L1)):*
> ```PowerShell
> Configuration xUserExample
> ```

There are no changes in this file, can we remove this from the pr?

---

*[Tests/Integration/MSFT_xUserResource.Integration.Tests.ps1, line 1 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238#-KSHqqgU_avr2AyYVDxR:-KSHqqgU_avr2AyYVDxS:b93yj7e) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8428c3d6dd862c2c3b5896e2491895ca5b3cc64a/Tests/Integration/MSFT_xUserResource.Integration.Tests.ps1#L1)):*
> ```PowerShell
> #To run these tests, the currently logged on user must have rights to create a user
> ```

please add an uber description of the scenarios this test is trying to test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238)*

**Comment by eshaparmar** [comment]
Reviewed 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238)*

**Comment by mbreakey3** [comment]
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.schema.mfl, line 1 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238#-KSHqTyTviRsPwbCiOgo:-KSI1CZCFPZiggou9HU7:b-888f7) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8428c3d6dd862c2c3b5896e2491895ca5b3cc64a/DSCResources/MSFT_xWindowsOptionalFeature/en-US/MSFT_xWindowsOptionalFeature.schema.mfl#L1)):*
<details><summary><i>Previously, eshaparmar (Esha Parmar) wrote…</i></summary>
> There are no changes in this file, can we remove this from the pr?
</details>
There was a minor spacing issue that I fixed - it just doesn't show up here since it's a .mfl file

---

*[Examples/Sample_xUser_CreateUser.ps1, line 1 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238#-KSHqeNQNzSUkB5juuZN:-KSI1XfyywH-mRKujuvd:bljd7xd) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8428c3d6dd862c2c3b5896e2491895ca5b3cc64a/Examples/Sample_xUser_CreateUser.ps1#L1)):*
<details><summary><i>Previously, eshaparmar (Esha Parmar) wrote…</i></summary>
> There are no changes in this file, can we remove this from the pr?
</details>
It was renamed 

---

*[Tests/Integration/MSFT_xUserResource.Integration.Tests.ps1, line 1 at r3](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238#-KSHqqgU_avr2AyYVDxR:-KSI7c2kbxeg1uE9kCOV:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8428c3d6dd862c2c3b5896e2491895ca5b3cc64a/Tests/Integration/MSFT_xUserResource.Integration.Tests.ps1#L1)):*
<details><summary><i>Previously, eshaparmar (Esha Parmar) wrote…</i></summary>
> please add an uber description of the scenarios this test is trying to test
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/238)*

**Comment by mbreakey3** [comment]
Closing this PR and opening a new one as the commit history got messed up.

**Pull request closed without merging**
