### PR TITLE
Fix composite resources are not available

### LINKED ISSUE #146: xFileUpload is not available as a resource
After installing the module xFileUpload does not appear in Get-DscResource. When present the Configuration fails with:

Undefined DSC resource 'xFileUpload'. Use Import-DSCResource to import the resource.

(Version 3.10.0.0 from the PowerShell Gallery)

### PR DESCRIPTION
**Pull request by Dan1el42**
Fixes #146

Resources affected:
* xFileUpload
* xGroupSet
* xProcessSet
* xServiceSet
* xWindowsFeatureSet
* xWindowsOptionalFeatureSet

Changes:
1. Rename folders and files of the composite resources, remove auto-generated module manifest headers
2. Update integration tests for composite resources

P.S.: Please let me know if you want me to update the Unreleased section of the README.md.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/209)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@Dan1el42 Yes please update the Unreleased section of the README since it fixes #146 

This is probably also the issue with other composite resources xFirefox, xChrome, xPhp etc not showing up as DSC resources... You've solved the mystery! :smile: 

I have no problem with removing the MSFT prefix (especially if it fixes this problem), but I need to ask the team on Tuesday why we have it in the first place. Will have to get back to you soon on this one.

**Comment by Dan1el42** [comment]
Great. Thanks very much. I've added an update of README.md to this PR.

**Comment by Dan1el42** [comment]
I'd like to add that I'll be happy to create PRs for the other affected composite resources once you've the go-ahead from the team.

**Comment by Dan1el42** [comment]
@kwirkykat Have you've had a chance to ask the team about removing the MSFT_ prefix from these composite resources?

**Comment by kwirkykat** [comment]
@Dan1el42 Yup I asked and they said that the composite resource files definitely should NOT have the MSFT_, so this PR is good to go once merge conflicts are resolved. :+1:

**Comment by Dan1el42** [comment]
PR updated to resolve merge conflict in README.md.

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 29 of 29 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/209#-:-KS2acia-cpU6EqvT2iy:bnfp4nl)*

**Pull request merged**
