### PR TITLE
xPSDesiredStateConfiguration: Add an ability to ignore reboot during package installation

### PR DESCRIPTION
**Pull request by ivadim**
#### Pull Request (PR) description
This PR adds an ability to ignore pending reboots for xPackage resource. This solves two problems:
* badly designed packages may require reboot even if not necessary
* xPackage uses `Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager' -Name 'PendingFileRenameOperations'` to get pending reboots. Values of the registry path can be changed by other processes not related to the installation process.

#### This Pull Request (PR) fixes the following issues
* None

#### Task list

- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as
      appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596)

### CODE REVIEW

**Comment by ivadim** [comment]
___
*[DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.schema.mof, line 28 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSkyYlDWDxAR0a7Mvp:-LaTTu_rBg74MXUOy_nl:bightxu) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.schema.mof#L28)):*
> xMsiPackage 
@Mike do you mean to do `[Write, Description("Ignore a reboot if MSI requested it.")] Boolean IgnoreReboot;` in MSFT_xPackageResource.schema.mof?

**Comment by ivadim** [comment]
___
*[README.md, line 549 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSk0K28ZmNtFWF7lN6:-LaT_bc51cgzprK5n9sZ:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/README.md#L549)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
>   * installation. By default is `$false` and DSC will try to reboot the system.
> ```
This asterisk doesn't appear to be necessary, and forces a line break in the output
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[README.md, line 643 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSkHLGENmiiLozQG5F:-LaT_ewHDnQpDoBu-8UA:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/README.md#L643)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
>   * by package installation. By default is `$false` and DSC will try to reboot
>   * the system.
> ```
These asterisks don't appear to be necessary, and force a line break in the output
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[DSCResources/MSFT_xMsiPackage/MSFT_xMsiPackage.psm1, line 353 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSjXGVDeYYzBuiKYXw:-LaT_tZ4CCC4vhRzAHY9:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/DSCResources/MSFT_xMsiPackage/MSFT_xMsiPackage.psm1#L353)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
> } else
> ```
Can you move this else to a new line?
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[DSCResources/MSFT_xMsiPackage/MSFT_xMsiPackage.schema.mof, line 15 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSkXMY7ZOY8-WB1cwk:-LaT_xkJ4N9S47WP8ArQ:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/DSCResources/MSFT_xMsiPackage/MSFT_xMsiPackage.schema.mof#L15)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
>Description("Ignore a reboot if MSI requested it.")] 
> ```
Can you change the Description to match what is in the parameter help?
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1, line 681 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSnyrr0lyLlHPEjV5E:-LaT_zfM725Vive_G6P9:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L681)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
> } else
> ```
Move else to new line
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[Examples/xPackage_InstallMsiConfig.ps1, line 44 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSo9FJ89zZbj_sfbxM:-LaTa60JCApzuuUf_G_J:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/Examples/xPackage_InstallMsiConfig.ps1#L44)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
>         Compiles a configuration that installs a package named 'Package Name'
>         located in the path '\\software\installer.msi' and ignore reboot request sent by that package.
> ```
Duplicate text from above is being added here.
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[Tests/Unit/MSFT_xMsiPackage.Tests.ps1, line 8 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSoLeO5xaU5_pulKa1:-LaTa8Wm8-6yc7Aju5LX:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/Tests/Unit/MSFT_xMsiPackage.Tests.ps1#L8)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

Unnecessary line break being added
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[Tests/Unit/MSFT_xMsiPackage.Tests.ps1, line 32 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSoOhj-sKR5HR4K-4D:-LaTaATQDAS9F2YJxjPp:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/Tests/Unit/MSFT_xMsiPackage.Tests.ps1#L32)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
> 
> ```
Unnecessary line breaks being added
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[Tests/Unit/MSFT_xMsiPackage.Tests.ps1, line 289 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSoTVjAM73TLnkLZNt:-LaTaDkH9owkv9jMaUr5:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/Tests/Unit/MSFT_xMsiPackage.Tests.ps1#L289)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
> Mock Start-MsiProcess { return 3010 }
> ```
Please use named parameters on this per the DSC style guidelines
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[Tests/Unit/MSFT_xPackageResource.Tests.ps1, line 520 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSoavY2ugtLVpI2qDc:-LaTaHxiDhiZixHofsvT:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/Tests/Unit/MSFT_xPackageResource.Tests.ps1#L520)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
>                     Mock Invoke-Process { return [System.Management.Automation.PSObject] @{ ExitCode = 3010 } }
>                     Mock Test-TargetResource { return $false }
>                     Mock Get-ProductEntry { return $null }
> ```
Need named parameters on these
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.schema.mof, line 28 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSkyYlDWDxAR0a7Mvp:-LaTaOgA9g08aHURxScn:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.schema.mof#L28)):*
<details><summary><i>Previously, ivadim wrote…</i></summary><blockquote>

> xMsiPackage 
@Mike do you mean to do `[Write, Description("Ignore a reboot if MSI requested it.")] Boolean IgnoreReboot;` in MSFT_xPackageResource.schema.mof? 
</blockquote></details>

Done.

**Comment by ivadim** [comment]
___
*[Tests/Unit/MSFT_xMsiPackage.Tests.ps1, line 32 at r2](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/596#-LaSoOhj-sKR5HR4K-4D:-LaaOGxh4-Yge4tP90Eg:bkm2fjc) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8a51d23337733fc26bd2ac3cfc3acd84d660236f/Tests/Unit/MSFT_xMsiPackage.Tests.ps1#L32)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

Still have one extra line break here that wasn't there originally. Can you remove this as well?
</blockquote></details>

Removed the line

**Comment by mhendric** [comment]
Good work here @ivadim . Thanks for the contribution!

**Pull request merged**
