### PR TITLE
xDscWebService: Implemented fix for issue 460

### LINKED ISSUE #460: xDscWebService: Redeploy DSC Pull Server fails with error
#### Details of the scenario you tried and the problem that is occurring
After a successfully configuration (deployment) of a DSC Pull Server via the `xDscWebService` resource, a redepolyment after the deletion of the IIS Webapplication failes with an error.

#### Verbose logs showing the problem
```powershell
VERBOSE: [UIDEFFMIMD54SPS]:                            [[xDSCWebService]PSDSCPullServer] Pull Server: Set values into the web.config that indicate the location of repository, configuration
, modules
VERBOSE: [UIDEFFMIMD54SPS]:                            [[xDSCWebService]PSDSCPullServer] Enabling Pull Server to run in a 64 bit process
The process cannot access the file 'C:\Windows\System32\inetsrv\IISSelfSignedCertModule.dll' because it is being used by another process.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.CopyItemCommand
    + PSComputerName        : localhost
 
VERBOSE: [UIDEFFMIMD54SPS]: LCM:  [ End    Set      ]  [[xDSCWebService]PSDSCPullServer]  in 5.5680 seconds.
The PowerShell DSC resource '[xDSCWebService]PSDSCPullServer' with SourceInfo 'E:\Projects\DSC\HTTPPullServer.ps1::40::9::xDscWebService' threw one or more non-terminating errors while 
running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
```
#### Suggested solution to the issue

By looking at the implementation (https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/01383b317abae8de69a1c093ddb51b2a064f8296/DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.psm1#L451) there should be a test if the module is already added to the globalModules section of the IIS instance and if so omit the installation. The easiest way to do is querying the the globalModules section and locate the module via a regex match:

```powershell
if (-not ((& $script:appCmd list config -section:system.webServer/globalModules) -match "IISSelfSignedCertModule")) {
   ...INSTALL MODULE...
}
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell

Configuration HTTPPullServer {

    Import-DSCResource -ModuleName xPSDesiredStateConfiguration

    Node $NodeName
    {
        WindowsFeature DSCServiceFeature
        {
            Ensure = "Present"
            Name   = "DSC-Service"
        }

        xDscWebService PSDSCPullServer
        {
            Ensure                  = $State
            EndpointName            = $EndpointName
            Port                    = $Port
            PhysicalPath            = "$env:SystemDrive\inetpub\PSDSCPullServer"
            CertificateThumbPrint   = $certificateThumbPrint
            ModulePath              = "$env:PROGRAMFILES\WindowsPowerShell\DscService\Modules"
            ConfigurationPath       = "$env:PROGRAMFILES\WindowsPowerShell\DscService\Configuration"
            State                   = "Started"
            DependsOn               = "[WindowsFeature]DSCServiceFeature"
            RegistrationKeyPath     = "$env:PROGRAMFILES\WindowsPowerShell\DscService"
            AcceptSelfSignedCertificates = $true
            Enable32BitAppOnWin64   = $false
            UseSecurityBestPractices = $false
        }

        File RegistrationKeyFile
        {
            Ensure          = $State
            Type            = 'File'
            DestinationPath = "$env:ProgramFiles\WindowsPowerShell\DscService\RegistrationKeys.txt"
            Contents        = $RegistrationKey
            DependsOn       = "[WindowsFeature]DSCServiceFeature"
        }
    }
}
```

#### The operating system the target node is running

```powershell
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19125.amd64fre.winblue_ltsb.180812-0703
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
```Powershell
ResourceType  : MSFT_xDSCWebService
Name          : xDSCWebService
FriendlyName  : xDSCWebService
Module        : xPSDesiredStateConfiguration
ModuleName    : xPSDesiredStateConfiguration
Version       : 8.4.0.0
Path          : C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\8.4.0.0\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1
ParentPath    : C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\8.4.0.0\DSCResources\MSFT_xDSCWebService
ImplementedAs : PowerShell
CompanyName   : Microsoft Corporation
```

### PR DESCRIPTION
**Pull request by tmeckel**
#### Pull Request (PR) description

This Pull Request (PR) implements a fix for issue #460 

#### This Pull Request (PR) fixes the following issues

Fixes #460 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/461)

### CODE REVIEW

**Comment by PlagueHO** [comment]
We should be able to pick this one up again once I've got all the integration tests passing again (and we've got a maintainer with merge permissions).

**Comment by mhendric** [comment]
@tmeckel , @PlagueHO was able to fix the integration tests. Can you rebase this when you get a chance? That will trigger a new CI build, which should pass. Thanks for your patience on this!

https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by PlagueHO** [comment]
I updated the branch on this one too and the tests are now running. Fingers crossed we can just get the review done :grin:

**Comment by mhendric** [comment]
Looks like the new build may in fact be failing due to this change:

```
6463
6464
  Describing MSFT_xDSCWebService\Set-TargetResource
6465
6466
    Context DSC Service is not installed and Ensure is Absent
6467
      [+] Should call expected mocks 234ms
6468
6469
    Context DSC Service is installed and Ensure is Absent
6470
      [+] Should call expected mocks 325ms
6471
6472
    Context Ensure is Present
6473
      [-] Should call expected mocks 693ms
6474
        RuntimeException: Mock test failed.
6475
        at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 449
6476
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 505
6477
      [-] Should create the DatabasePath directory 758ms
6478
        RuntimeException: Mock test failed.
6479
        at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 449
6480
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 533
6481
      [-] Should create the RegistrationKeyPath directory 848ms
6482
        RuntimeException: Mock test failed.
6483
        at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 449
6484
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 533
6485
      [-] Should create the ModulePath directory 621ms
6486
        RuntimeException: Mock test failed.
6487
        at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 449
6488
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 533
6489
      [-] Should create the ConfigurationPath directory 554ms
6490
        RuntimeException: Mock test failed.
6491
        at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 449
6492
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 533
6493
6494
    Context Ensure is Present - isDownLevelOfBlue
6495
      [-] Should call expected mocks 868ms
6496
        RuntimeException: Mock test failed.
6497
        at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 449
6498
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 553
6499
6500
    Context Ensure is Present - isUpLevelOfBlue
6501
      [-] Should call expected mocks 626ms
6502
        RuntimeException: Mock test failed.
6503
        at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 449
6504
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 582
6505
6506
    Context Ensure is Present - Enable32BitAppOnWin64
6507
      [-] Should call expected mocks 1s
6508
        RuntimeException: Mock test failed.
6509
        at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 449
6510
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 606
6511
6512
    Context Ensure is Present - AcceptSelfSignedCertificates is $false
6513
      [+] Should call expected mocks 1.91s
6514
6515
    Context Ensure is Present - UseSecurityBestPractices is $true
6516
      [+] Should throw an error because no certificate specified 49ms
6517
6518
    Context Ensure is Present - CertificateSubject
6519
      [-] Should call expected mocks 730ms
6520
        RuntimeException: Mock test failed.
6521
        at Set-TargetResource, C:\projects\xpsdesiredstateconfiguration\DSCResources\MSFT_xDSCWebService\MSFT_xDSCWebService.psm1: line 449
6522
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 678
6523
6524
    Context Ensure is Present - CertificateThumbprint and UseSecurityBestPractices is $true
6525
      [-] Should not throw an error 814ms
6526
        Expected no exception to be thrown, but an exception "Mock test failed." was thrown from line:1 char:59
6527
            + ... s -notcontains $MyInvocation.Line.Trim()) {throw 'Mock test failed.'}
6528
            +                                                ~~~~~~~~~~~~~~~~~~~~~~~~~.
6529
        701:                     {Set-TargetResource @altTestParameters @setTargetPaths -Ensure Present} | Should -Not -throw
6530
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 701
6531
      [-] Should call expected mocks 42ms
6532
        Expected Set-UseSecurityBestPractices in module MSFT_xDSCWebService to be called 1 times exactly but was called 0 times
6533
        706:                     Assert-MockCalled -Exactly -Times 1 -CommandName Set-UseSecurityBestPractices
6534
        at <ScriptBlock>, C:\projects\xpsdesiredstateconfiguration\Tests\Unit\MSFT_xDSCWebService.Tests.ps1: line 706
6535
6536
    Context Function parameters contain invalid data
6537
      [+] Should throw if CertificateThumbprint and CertificateSubject are not specifed 43ms
6538
```

**Comment by PlagueHO** [comment]
This one needs a rebase to resolve conflicts.

**Comment by tmeckel** [comment]
@PlagueHO  @mhendric  sorry guys but I'm unable to rebase the PR because since I rebased my/dev to origin/dev I now get modified files when I checkout my/dev. 

``
modified:   DSCPullServerSetup/README.md
modified:   DSCResources/MSFT_xArchive/MSFT_xArchive.schema.mof
modified:   DSCResources/MSFT_xDSCWebService/PSWSIISEndpoint.psm1
modified:   DSCResources/MSFT_xEnvironmentResource/MSFT_xEnvironmentResource.schema.mof
modified:   DSCResources/MSFT_xEnvironmentResource/en-US/MSFT_xEnvironmentResource.strings.psd1
modified:   DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.schema.mof
modified:   DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.schema.mof
modified:   DSCResources/MSFT_xRegistryResource/en-US/MSFT_xRegistryResource.schema.mfl
modified:   DSCResources/MSFT_xRegistryResource/en-US/MSFT_xRegistryResource.strings.psd1
modified:   DSCResources/MSFT_xScriptResource/MSFT_xScriptResource.schema.mof
modified:   DSCResources/MSFT_xScriptResource/en-US/MSFT_xScriptResource.strings.psd1
modified:   DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.schema.mof
modified:   DSCResources/MSFT_xWindowsFeature/MSFT_xWindowsFeature.schema.mof
modified:   DSCResources/MSFT_xWindowsFeature/en-US/MSFT_xWindowsFeature.strings.psd1
modified:   DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.schema.mof
modified:   DSCResources/MSFT_xWindowsPackageCab/MSFT_xWindowsPackageCab.schema.mof
`` 

seems to be an issue with line ending or file encoding, because when I add 

```powershell
$ git config core.autocrlf false
```

git only detectes the following files as modified on checkout my/dev

``
DSCResources/MSFT_xDSCWebService/PSWSIISEndpoint.psm1 DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.schema.mof
``

Because the PR only contains a small fix (including updating the readme.md) I would close this PR and start with a new one.

Please let me know what you want to do.

**Comment by mhendric** [comment]
Hey @tmeckel . I think this is possibly due to something in this commit (https://github.com/PowerShell/xPSDesiredStateConfiguration/commit/ae31fd920583cbe28d39199bbbd9ffd1b949cbe4). I think that change may be enforcing new rules which are getting flagged on files even if you didn't change them yourself. Until someone does a check-in that fixes these, everyone will see this. I'll go ahead and submit a new PR to address this. Then your rebase should be much cleaner. 

As an example, check out the brand new clone below. All I did was clone the repo, and didn't change anything. But git status shows a bunch of modified files.

```
PS D:\GitHub\xp> git clone https://github.com/PowerShell/xPSDesiredStateConfiguration
Cloning into 'xPSDesiredStateConfiguration'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (22/22), done.
Receiving objects: 100% (5416/5416), 2.23 MiB | 6.73 MiB/s, done.5384Receiving objects: 100% (5416/5416)

Resolving deltas: 100% (3881/3881), done.
PS D:\GitHub\xp> cd .\xPSDesiredStateConfiguration\
PS D:\GitHub\xp\xPSDesiredStateConfiguration> git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   DSCPullServerSetup/README.md
        modified:   DSCResources/MSFT_xArchive/MSFT_xArchive.schema.mof
        modified:   DSCResources/MSFT_xDSCWebService/PSWSIISEndpoint.psm1
        modified:   DSCResources/MSFT_xEnvironmentResource/MSFT_xEnvironmentResource.schema.mof
        modified:   DSCResources/MSFT_xEnvironmentResource/en-US/MSFT_xEnvironmentResource.strings.psd1
        modified:   DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.schema.mof
        modified:   DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.schema.mof
        modified:   DSCResources/MSFT_xRegistryResource/en-US/MSFT_xRegistryResource.schema.mfl
        modified:   DSCResources/MSFT_xRegistryResource/en-US/MSFT_xRegistryResource.strings.psd1
        modified:   DSCResources/MSFT_xScriptResource/MSFT_xScriptResource.schema.mof
        modified:   DSCResources/MSFT_xScriptResource/en-US/MSFT_xScriptResource.strings.psd1
        modified:   DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.schema.mof
        modified:   DSCResources/MSFT_xWindowsFeature/MSFT_xWindowsFeature.schema.mof
        modified:   DSCResources/MSFT_xWindowsFeature/en-US/MSFT_xWindowsFeature.strings.psd1
        modified:   DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.schema.mof
        modified:   DSCResources/MSFT_xWindowsPackageCab/MSFT_xWindowsPackageCab.schema.mof

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by mhendric** [comment]
Opened PR #481 to attempt to fix this.

**Comment by PlagueHO** [comment]
I think @mhendric is right, @tmeckel - rebasing back onto the current Dev branch on this fork should resolve these issues. If not, we should look further.

**Comment by mhendric** [comment]
@tmeckel , #481 has been merged. Can you give another shot at a rebase? If you have too much trouble, it may just be easier to do a new PR (as you suggested above).

**Comment by mhendric** [comment]
Sounds good. Thanks @tmeckel .

**Pull request closed without merging**
