### PR TITLE
xRemoteFile: Updating parameter description for MatchSource - Fixes #409

### LINKED ISSUE #409: xRemoteFile always returns false in test
As a devops, I expect to be able to test if the system is in desired state, including xRemoteFile resources. Here is an example of the resource I am applying:

```
        xRemoteFile SQLMediaArchive
        {
            Uri             = "http://$env:PACKER_HTTP_ADDR/SQLServer2014SP1.zip"
            DestinationPath = "C:\Install\SQLServer2014SP1.zip"
        }
```

First, I run Start-DscConfiguration and the file is downloaded successfully. Then I need to test that configuration is in desired state, so I run Test-DscConfiguration and I get False:
```
VERBOSE: An LCM method call arrived from computer WIN-SLU589M70V9 with user sid
 S-1-5-21-3913156103-666311135-156080423-500.
VERBOSE: [WIN-SLU589M70V9]: LCM:  [ Start  Compare  ]
VERBOSE: [WIN-SLU589M70V9]: LCM:  [ Start  Resource ]
[[xRemoteFile]SQLMediaArchive]
VERBOSE: [WIN-SLU589M70V9]: LCM:  [ Start  Test     ]
[[xRemoteFile]SQLMediaArchive]
VERBOSE: [WIN-SLU589M70V9]:
[[xRemoteFile]SQLMediaArchive] DestinationPath
'C:\Install\SQLServer2014SP1.zip' is existing file on the machine.
VERBOSE: [WIN-SLU589M70V9]:
[[xRemoteFile]SQLMediaArchive] Looking for cache path
'C:\ProgramData\Microsoft\Windows\PowerShell\Configuration\BuiltinProvCache\MSF
T_xRemoteFile\1645172953'.
VERBOSE: [WIN-SLU589M70V9]:
[[xRemoteFile]SQLMediaArchive] No cache found for DestinationPath
'C:\Install\SQLServer2014SP1.zip' and Uri
'http://10.0.2.2:8328/SQLServer2014SP1.zip' CacheKey '1645172953'.
VERBOSE: [WIN-SLU589M70V9]:
[[xRemoteFile]SQLMediaArchive] Cache is empty or it doesn't reflect current
state. File will be downloaded.
VERBOSE: [WIN-SLU589M70V9]: LCM:  [ End    Test     ]
[[xRemoteFile]SQLMediaArchive] **False** in 0.1090 seconds.
VERBOSE: [WIN-SLU589M70V9]: LCM:  [ End    Resource ]
[[xRemoteFile]SQLMediaArchive]
VERBOSE: [WIN-SLU589M70V9]: LCM:  [ Start  Resource ]
```

### PR DESCRIPTION
**Pull request by shurick81**
Fixes #409 

This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/410)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/410#-LBPs9J5-PzG_-u4gu3H:-LBPs9J5-PzG_-u4gu3I:b-jv6vp2) (no related file):*
Please add an entry for this to the Unreleased section of the chnage log in the file README.md.

---

*[README.md, line 295 at r1](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/410#-LBPs-pB6CHPnMvTOv47:-LBPs-pB6CHPnMvTOv48:b2gzr0c) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/70d18d20052f1588d9c2a3038bd5e78ea5ef6582/README.md#L295)):*
> ```Markdown
> * **Headers**: Headers of the web request. Optional.
> * **Credential**: Specifies credential of a user which has permissions to send the request. Optional.
> * **MatchSource**: Determines whether the remote file should be re-downloaded if file in the DestinationPath was modified locally. Optional. True by default.
> ```

In other locations this is written as 'The default value is true.'. Could we change to that? 

---

*[README.md, line 295 at r1](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/410#-LBPsG5D0LzBYfiJGKnS:-LBPsG5D0LzBYfiJGKnT:b-jb5rc0) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/70d18d20052f1588d9c2a3038bd5e78ea5ef6582/README.md#L295)):*
> ```Markdown
> * **Headers**: Headers of the web request. Optional.
> * **Credential**: Specifies credential of a user which has permissions to send the request. Optional.
> * **MatchSource**: Determines whether the remote file should be re-downloaded if file in the DestinationPath was modified locally. Optional. True by default.
> ```

Please update the description in the schema.mof for the xRemoteFile resource as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/410)*

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by mhendric** [comment]
Hi @shurick81 . Following up on this to see if you can still finish this one up? Looks like this just needs a rebase per the below article, and an entry added to the Unreleased section saying what you did. Thanks in advance.

https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by mhendric** [comment]
@PlagueHO and @johlju , what do you think we should do with this one?

**Comment by PlagueHO** [comment]
Probably we just recreate the PR and close this one.

**Comment by PlagueHO** [comment]
I'm going to recreate the PR for this one.

**Pull request closed without merging**
