### PR TITLE
xRegistry: Merge with In-Box Resource, Add Tests, and Fix Key/Value Removal

### PR DESCRIPTION
**Pull request by kwirkykat**
This is for #160.

I merged the Registry resource with our current in-box resource. This was a fairly small change.
I also ported the Registry unit tests.

While porting these tests, I found that removal of registry keys and values with the resource was not working, so I fixed this as well.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/226)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Made a small update to the code so that tests now all pass with StrictMode -Version 4.
Also noticed a discrepancy between the ValueType values in the README vs. in the acutal resource, so I fixed that as well.

**Comment by mbreakey3** [comment]
Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 373 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVIcWsQ0lRxB9CQMGU:-KRVIcWsQ0lRxB9CQMGV:b41417) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L373)):*
> ```PowerShell
>         }
> 
>         $null = New-PSDrive @newPSDriveParams -Name $mappingKey -Root $registryDriveRootMappings[$mappingKey]
> ```

Why is this being set to null? Can you add a comment in this function?

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 400 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVItVdJTyyXEq4CUIS:-KRVItVdJTyyXEq4CUIT:b-ciaek) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L400)):*
> ```PowerShell
> 
>     $driveName = Split-Path -Path $KeyPath -Qualifier
>     Write-Verbose -Message "Mount-RegistryDrive - Drive name: $driveName"
> ```

Do you mean 'Dismount' here in this Verbose message? 

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 449 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVJADHKjX75IjZ5nKD:-KRVJADHKjX75IjZ5nKE:b-4lfxvg) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L449)):*
> ```PowerShell
>     )
> 
>     $retString = ''
> ```

maybe change this to $hexString for clarity?

---

*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 18 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVJRhfQAVPb0KC31Rn:-KRVJRhfQAVPb0KC31Ro:b-n4wgc1) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L18)):*
> ```PowerShell
>                 $script:registryKeyPath = $baseRegistryKeyPath
> 
>                 while (Test-RegistryKeyExists -KeyPath $script:registryKeyPath)
> ```

Could there ever be a situation where this infinite loops?

---

*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 255 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVLLMnjYSibndFlWoe:-KRVLLMnjYSibndFlWof:b-1ud8qa) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L255)):*
> ```PowerShell
>                 }
> 
>                 It 'Should return true for a registry value that does not exist' {
> ```

It says true testing value says $false

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by kwirkykat** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 373 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVIcWsQ0lRxB9CQMGU:-KRVLpr7jyS6zmPx2mCh:bnwrsr2) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L373)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Why is this being set to null? Can you add a comment in this function?
</details>
This is 'nullifying' the output of New-PSDrive. It's the same thing as piping to Out-Null but with less overhead.

Added some comments as well as the 2 missing parameters from the 2nd call to New-PSDrive

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 400 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVItVdJTyyXEq4CUIS:-KRVM6BgE7jWmYl8zoJr:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L400)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Do you mean 'Dismount' here in this Verbose message? 
</details>
Done.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 449 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVJADHKjX75IjZ5nKD:-KRVMEVyHWHpbpbnupS5:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L449)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> maybe change this to $hexString for clarity?
</details>
Done.

---

*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 18 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVJRhfQAVPb0KC31Rn:-KRVSa9Ly7yHt6vfHfkc:b3jim7s) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L18)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Could there ever be a situation where this infinite loops?
</details>
It's very unlikely, but I added a timeout of 1 minute just in case.

---

*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 255 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVLLMnjYSibndFlWoe:-KRVMT6LBQXk7rvkh8cS:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L255)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> It says true testing value says $false
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by mbreakey3** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by mbreakey3** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-:-KRV_GmdPQ6ELgMtAUXe:bnfp4nl)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 3 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVZR5QDeSUVs_MPDUe:-KRVZR5QDeSUVs_MPDUf:bta7poc) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L3)):*
> read-only
Please update the synopsis since it is not 100% accurate. `$WriteAccess` parameter opens the key with write access.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 111 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRV_iH1ZgOruZd12fm8:-KRV_iH2SQEBDksETJhN:b-ua3pqd) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L111)):*
> $registryValueExists

Check the value here. If it is `false`, then return `$false` here. This way the rest of the function code does not need to check for this every time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 168 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVa_AEhTHgv8VVw42l:-KRVa_AEhTHgv8VVw42m:b-ectdte) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L168)):*
> Test-Path -Path $parentPath

Why not  use `Test-RegistryKeyExists` here too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 318 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVbkTNqDDeyJMcU7-M:-KRVbkTNqDDeyJMcU7-N:b8fdzzg) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L318)):*
> $registryDrivePath = Split-Path -Path $KeyPath -Qualifier
>     $registryDrive = Get-Item -Path $registryDrivePath
>  
>     $subKeyPath = Split-Path -Path $KeyPath -NoQualifier
>     $subKeyPath = $subKeyPath.Substring(1)
>  
>     $registryKey = $registryDrive.OpenSubKey($subKeyPath, $true)

Use `Get-RegistryKey`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 376 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVdFrSvAcfrMx3Zg_O:-KRVdFrTShhGJrZTiifl:b-j6h185) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L376)):*
> $registryDriveRootMappings[$mappingKey]

This is the same as `$driveName`. So no need to lookup `$mappingKey` for this translation. Just use `$driveName`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 376 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVeRniRh4L5jac2G3m:-KRVeRnjmnadOgjAImN9:b-617phb) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L376)):*
> @newPSDriveParams

Where is this coming from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 18 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVJRhfQAVPb0KC31Rn:-KRVfnuP6ImvB3eN2ll_:b-7qj2qs) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/8397e2d6046039cd3e65ce7b0575360de6a7dbf2/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L18)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> It's very unlikely, but I added a timeout of 1 minute just in case.
</details>
Katie is right. It is very unlikely. So I believe the timeout is overkill. Also, you can use a GUID and/or some format of the current date and time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 31 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVgW5vr3HeuODCymyf:-KRVgW5wA6IMzCG6CtI-:b-abrshu) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L31)):*
> if (Test-RegistryKeyExists -KeyPath $script:registryKeyPath)

What's the point of this IF statement here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 33 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVgb7ephMbR6WF8d_A:-KRVgb7ephMbR6WF8d_B:bmmjt7j) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L33)):*
> $script:doNotDeleteRegistryKey = $true
>                     throw "Timed out while attempting to set up a non-destructive registry key for testing. Last testing key attempted: $script:registryKeyPath"
>                     return

Why set a variable right before throwing an exception? And what's the `return` for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 56 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVh7IhltVJrOW9ce1d:-KRVh7IhltVJrOW9ce1e:b-r44dlo) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L56)):*
> $script:doNotDeleteRegistryKey

I don't see the need for this variable. If the key is supposed to be a test key created for this test suite only, why should we not delete it afterwards?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 114 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVi4MIjFzHyKQ6Tp_Z:-KRVi4MIjFzHyKQ6Tp__:b-26sm44) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L114)):*
> $registryKeyTreePath

Why not define this in `BeforeAll` too. It is common between at least two tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226)*

**Comment by kwirkykat** [comment]
@zjalali I will submit a new PR with changes per your comments :+1:

---

Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 3 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVZR5QDeSUVs_MPDUe:-KRVpJKONG9peDM5tYay:b74557p) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L3)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > read-only
> Please update the synopsis since it is not 100% accurate. `$WriteAccess` parameter opens the key with write access.
</details>
Will fix in new PR.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 111 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRV_iH1ZgOruZd12fm8:-KRVpIRkQSmBblb016ZE:b74557p) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L111)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > $registryValueExists
> 
> Check the value here. If it is `false`, then return `$false` here. This way the rest of the function code does not need to check for this every time.
</details>
Will fix in new PR.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 168 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVa_AEhTHgv8VVw42l:-KRVpHpoy2Kf6hw6lu0q:b74557p) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L168)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > Test-Path -Path $parentPath
> 
> Why not  use `Test-RegistryKeyExists` here too?
</details>
Will fix in new PR.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 318 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVbkTNqDDeyJMcU7-M:-KRVpHSWjHrXMCUKVeGv:b74557p) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L318)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > $registryDrivePath = Split-Path -Path $KeyPath -Qualifier
> >     $registryDrive = Get-Item -Path $registryDrivePath
> >  
> >     $subKeyPath = Split-Path -Path $KeyPath -NoQualifier
> >     $subKeyPath = $subKeyPath.Substring(1)
> >  
> >     $registryKey = $registryDrive.OpenSubKey($subKeyPath, $true)
> 
> Use `Get-RegistryKey`.
</details>
Will fix in new PR.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 376 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVeRniRh4L5jac2G3m:-KRVoWiUm0bU29doQoHc:b-pawp0r) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L376)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > @newPSDriveParams
> 
> Where is this coming from?
</details>
Ick. This is leftover from copying code. Will fix in new PR.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 376 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVdFrSvAcfrMx3Zg_O:-KRVpGvWvi6CBjbwFmIp:b74557p) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L376)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > $registryDriveRootMappings[$mappingKey]
> 
> This is the same as `$driveName`. So no need to lookup `$mappingKey` for this translation. Just use `$driveName`.
</details>
Will fix in new PR.

---

*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 31 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVgW5vr3HeuODCymyf:-KRVnTW-00F15Sfvh0WW:b-tmqbw3) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L31)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > if (Test-RegistryKeyExists -KeyPath $script:registryKeyPath)
> 
> What's the point of this IF statement here?
</details>
This is to check if we have timed out or if we have found a registry key that does not exist.

---

*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 33 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVgb7ephMbR6WF8d_A:-KRVnd0WltgOQkblf4kh:b-fddang) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L33)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > $script:doNotDeleteRegistryKey = $true
> >                     throw "Timed out while attempting to set up a non-destructive registry key for testing. Last testing key attempted: $script:registryKeyPath"
> >                     return
> 
> Why set a variable right before throwing an exception? And what's the `return` for?
</details>
Pester still runs the AfterAll block even after I throw the error and return.
The return is just making sure that Pester STOPS after the error rather than continuing the tests.
It's probably overkill.

---

*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 56 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVh7IhltVJrOW9ce1d:-KRVnsRMDx4VO47wpC1p:b-x1dszv) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L56)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > $script:doNotDeleteRegistryKey
> 
> I don't see the need for this variable. If the key is supposed to be a test key created for this test suite only, why should we not delete it afterwards?
</details>
Pester runs this block last ALWAYS.
Even if the timeout occurs and an error is thrown, it still runs this block.
When I tested the timeout it was still removing the existing key which would be considered destructive to the test-runner's system.

---

*[Tests/Unit/MSFT_xRegistryResource.Tests.ps1, line 114 at r2](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-KRVi4MIjFzHyKQ6Tp_Z:-KRVoAOLIoNfgUM6mwIp:b9eigwq) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/bbbc0b402b9f73f1dc6c21a6397e54f241baedec/Tests/Unit/MSFT_xRegistryResource.Tests.ps1#L114)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > $registryKeyTreePath
> 
> Why not define this in `BeforeAll` too. It is common between at least two tests.
</details>
Eh. It's only in two tests.
I don't want to clutter up the BeforeAll even more just for the two tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/226#-:-KRVqNjObYOyRN1OIOvY:bj5su2l)*

**Comment by ArieHein** [comment]
should have probably dealt with #114 as well, while at it, its not a big change either.

**Pull request merged**
