### PR TITLE
xDscWebService: Fixed issue 464

### PR DESCRIPTION
**Pull request by tmeckel**
#### Pull Request (PR) description

This Pull Requests fixes issue #464 in which the IIS Application Pool is not removed on retracting a deployed DSC Pull Server with "Ensure=Absent"

#### This Pull Request (PR) fixes the following issues

#464 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/465)

### CODE REVIEW

**Comment by mhendric** [comment]
> Hi @mhendric .. thanks for reviewing my PR. But I had to smile a little bit about your comment, because at first the mentioned issue in capitalization isn't part of my PR and therefore was part of the original code. 

Agreed. I wouldn't worry about it unless you do decide to implement my -le suggestion, which in that case, you might as well fix two problems with one new line of code. The only real critical thing that needs to be changed with this PR is the need for an Unreleased entry in README.MD.

> And second, in my opinion the code inside PSWSIISEndpoint.psm1 isnt't really a role model for how how you would write "clean code" for POSH.

Totally agree here too. It's got to be fixed at some point though, right? No better time to fix it than while you're working on it. (I'm assuming a goal is for this module is to eventually be a high quality module https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md, or at a minimum, to allow easier integration into PSDscResources, which is a high quality module already.)

**Comment by tmeckel** [comment]
> Agreed. I wouldn't worry about it unless you do decide to implement my -le suggestion, which in that case, you might as well fix two problems with one new line of code. 
> 
We are talking about coding style and stuff like that as it seems to me :-D And thus I personally would prefer the code that I submitted with my PR. Not because I'm narcissistic but because you should test for a null reference on an object before you access any members.

I know this is an epic discussion between people using compiled languages like C# and others using "interpreted" languages like Javascript or Powershell. The latter ones support the concept of returning defined values when you access a property of an uninitialized variable. Your `-le` comparison relies on Powershell returning 0 for the Count member if the actual variable is null. But this will fail if you use "Set-StrictMode" ... I know know using `Set-StrictMode  would probably blow up the most code here in xPSDesiredStateConfiguration :-D but ever since the days of Visual Basic there was something like `StrictMode` oder `Option Explicit` to discipline the programmers. I love to use the lax mode in scripts that are for my personal use or do no "dangerous" things but with a module like that we eventually should create code that follows the "strictmode" principle.

>The only real critical thing that needs to be changed with this PR is the need for an Unreleased entry in README.MD.
>
I forgot to ask about this yesterday. What do you mean by "is the need for an Unreleased entry in README.MD". Do I've to add something in which README.MD?

**Comment by mhendric** [comment]
> Your -le comparison relies on Powershell returning 0 for the Count member if the actual variable is null. But this will fail if you use "Set-StrictMode"

Ah, I wasn't aware that $null.Count doesn't work if in StrictMode. That's a very good reason not to take my suggestion.

> What do you mean by "is the need for an Unreleased entry in README.MD". Do I've to add something in which README.MD?

Yes, see the first step in the Task List from the original PR comment. Just find the ### Unreleased section, and then put an entry under it saying what you did. Use the same style as underneath all the version number specific comments below it.

**Comment by tmeckel** [comment]
> > What do you mean by "is the need for an Unreleased entry in README.MD". Do I've to add something in which README.MD?
> 
> Yes, see the first step in the Task List from the original PR comment. Just find the ### Unreleased section, and then put an entry under it saying what you did. Use the same style as underneath all the version number specific comments below it.

Ah now I got it! I wasn't ware of that I have to add the description to the unreleased section of the toplevel README.md. But duh me! It's obvious. Thank's for the clarification.

**Comment by tmeckel** [comment]
@mhendric added the required entry in the Unreleased section of README.MD

**Comment by PlagueHO** [comment]
We should be able to pick this one up again once I've got all the integration tests passing again (and we've got a maintainer with merge permissions).

**Comment by mhendric** [comment]
@tmeckel , @PlagueHO was able to fix the integration tests. Can you rebase this when you get a chance? That will trigger a new CI build, which should pass. Thanks for your patience on this!

https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by PlagueHO** [comment]
The new (new since we wrote the rebase instructions) allows us to update the branch ourselves (if it can) by clicking Update Branch button. So I've done this and it looks like there is no conflict now - so the tests are running :grin:

**Comment by mhendric** [comment]
@PlagueHO , I did a 'Resolve Conflicts' on this one. Assuming CI passes, this should be ready for merge. I'm gonna sign off for the day so if you're still active on your side of the world once CI finishes, feel free to merge this.

**Pull request merged**
