### PR TITLE
Fixing Bugs in xGroup Resource (Fixes #180)

### LINKED ISSUE #180: xGroup fails on group 'Users'
Very simple resource:

     Node $NodeName
     {
        xGroup GroupUsers
        {
            Ensure = "Present"
            GroupName = "Users"
        }
     }

In Version `3.12.0.0` this gets me the exception:

`Exception calling ".ctor" with "2" argument(s): "Server names cannot contain a space character."`

Interestingly enough, trying the same with Resource `Group (MSFT_GroupResource)` gives the error:

`Credentials are required to resolve the domain account INTERACTIVE`

this happened on non-Domain machines.

So I can not check whether any user is a member of the `users` group.

### PR DESCRIPTION
**Pull request by kwirkykat**
This should fix the Administrator issues occurring in #175 as well as the issue occurring in #180.

I made several small (but important) bug fixes:
- Test-TargetResource will no longer check for group members if they are not specified.
- You can now specify only one member.
- Set-TargetResource no longer uses group.Clear() when using the Members parameter, so the built-in Administrator account should not complain if it is being included properly.
- Get-Group will now properly return null when the specified group does not exist rather than throwing an error.
- Length --> Count for arrays. No functionality change. They are the exact same thing, but in case one variable gets overwritten with a string by some weird accident, the script will properly throw an error since a string does not have Count but it does have length.
- More null checks

I added 1 new unit test to make sure Set-Target resource will properly create an empty group, and I also added 2 new integration tests to check for these issues, one that creates a new empty group, and one that ensures that the built in Administrator (username 'Administrator') is in the Administrators group.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/182)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@PlagueHO Can you please look this over before I merge it?

**Comment by PlagueHO** [comment]
Looking great to me! I've put in comments on the bugs I found. You could include the fixes in your PR if you want or I could submit another one after yours. If you want me to submit my fixes in another PR, give me a shout. After you've merged this PR I'll look at adding some more tests (although the coverage is getting much better now).

I did also want to do a bit of work bringing the code into line with the styleguidelines, but if you're working on that then I won't. Feel free to let me know what parts I can help out on!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 373 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL3Jo5qwgvmqVqHJ50:-KNL3Jo67J2Tw1GxOmGE:1428272125) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L373)):*
> ```PowerShell
>                 $whatIfShouldProcess = $pscmdlet.ShouldProcess(($LocalizedData.GroupWithName -f $GroupName), $LocalizedData.SetOperation)
> 
>                 $actualMembersAsPrincipals = Get-MembersAsPrincipals `
> ```

This line has one of the bugs I found: if Get-MembersAsPrincipals only returns a single record it won't be an array and so the .Count property used later on won't exist. I resolved by wrapping the cmdlet with an @( ) to explicitly cast to an array.

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 753 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL5RUZOPUhId2Co0_I:-KNL5RU_NLfXJCMvSmes:-298601663) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L753)):*
> ```PowerShell
>                     -Credential $Credential )
> 
>                 if (($null -eq $expectedMembersAsPrincipals -xor $null -eq $actualGroupMembers) -or (($null -ne $expectedMembersAsPrincipals -and $null -ne $actualGroupMembers) -and $expectedMembersAsPrincipals.Count -ne $actualGroupMembers.Count))
> ```

 This line makes my brain hurt :smile: Any chance we could split it with back ticks to under 100 chars to make it easier to read? Although I think the logic is sound.

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 778 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL4b1IGjkP1NPbmh4m:-KNL4b1IGjkP1NPbmh4n:1428272125) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L778)):*
> ```PowerShell
>         elseif ($PSBoundParameters.ContainsKey('MembersToInclude') -or $PSBoundParameters.ContainsKey('MembersToExclude'))
>         {
>             $actualMembersAsPrincipals = Get-MembersAsPrincipals `
> ```

This line has one of the bugs I found: if Get-MembersAsPrincipals only returns a single record it won't be an array and so the .Count property used later on won't exist. I resolved by wrapping the cmdlet with an @( ) to explicitly cast to an array.

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 2303 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL7919UmmNduOCnKbl:-KNL7919UmmNduOCnKbm:-1361438717) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L2303)):*
> ```PowerShell
>     if ($GroupName.IndexOfAny($invalidCharacters) -ne -1)
>     {
>         ThrowInvalidArgumentError -ErrorId 'GroupNameHasInvalidCharacter' -ErrorMessage ($LocalizedData.InvalidGroupName -f $GroupName, [String]::Join(' ', $invalidCharacters))
> ```

I found a bug in this line: ThrowInvalidArgumentError does not exist - should be:
```powershell
New-InvalidArgumentException `
            -ArgumentName 'GroupNameHasInvalidCharacter' `
            -Message ($LocalizedData.InvalidGroupName `
                -f $GroupName, [String]::Join(' ', $invalidCharacters))
```

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 2320 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL7RwDLFTmsPiU_RFC:-KNL7RwDLFTmsPiU_RFD:-464060433) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L2320)):*
> ```PowerShell
>     if ($nameContainsOnlyWhitspaceOrDots)
>     {
>         ThrowInvalidArgumentError -ErrorId 'GroupNameHasOnlyWhiteSpacesAndDots' -ErrorMessage ($LocalizedData.InvalidGroupName -f $GroupName, [String]::Join(' ', $invalidCharacters))
> ```

I found a bug in this line: ThrowInvalidArgumentError does not exist - should be:
```powershell
New-InvalidArgumentException `
            -ErrorId 'GroupNameHasOnlyWhiteSpacesAndDots' `
            -Message ($LocalizedData.InvalidGroupName `
                -f $GroupName, [String]::Join(' ', $invalidCharacters))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-:-KNL7oRuL8iq_wT-TfG8:-1894870156)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 347 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL8fM3CI757Yi3hVgi:-KNL8fM4pnrWmawIe_Tw:1503099726) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/README.md#L347)):*
> ```Markdown
>     * Fixed logic bug in MembersToInclude and MembersToExclude.
>     * Fixed bug when trying to include the built-in Administrator in Members.
>     * Fixed bug where Test-TargetResource would check for members when none specified.
> ```

Also, if you include my fixes, this is the Readme.md changes I put in:
+          Fix bug in Test-TargetResourceOnFullSKU function when group being set to a single member.
+          Fix bug in Set-TargetResourceOnFullSKU function when group being set to a single member.
+          Fix bugs in Assert-GroupNameValid to throw correct exception.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182)*

**Comment by kwirkykat** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 347 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL8fM3CI757Yi3hVgi:-KNY31R_Il88ltlB-Q0w:-499146009) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/README.md#L347)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Also, if you include my fixes, this is the Readme.md changes I put in:
> +          Fix bug in Test-TargetResourceOnFullSKU function when group being set to a single member.
> +          Fix bug in Set-TargetResourceOnFullSKU function when group being set to a single member.
> +          Fix bugs in Assert-GroupNameValid to throw correct exception.
</details>
Done.

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 373 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL3Jo5qwgvmqVqHJ50:-KNY32jRbNoLr4c8NN_H:679744966) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L373)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> This line has one of the bugs I found: if Get-MembersAsPrincipals only returns a single record it won't be an array and so the .Count property used later on won't exist. I resolved by wrapping the cmdlet with an @( ) to explicitly cast to an array.
</details>
Done. I also added the array wrapper around any other calls to Get-MembersAsPrincipals that I found.

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 753 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL5RUZOPUhId2Co0_I:-KNY38tmSwxriH2lor_B:-1595830206) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L753)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
>  This line makes my brain hurt :smile: Any chance we could split it with back ticks to under 100 chars to make it easier to read? Although I think the logic is sound.
</details>
Simplified it. The null checks here are actually no longer needed since we now have array wrappers around the calls to Get-MembersAsPrincipals (which populates both these variables), so I just removed them.

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 778 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL4b1IGjkP1NPbmh4m:-KNY3N8xwZ7sWtJaZ53F:-499146009) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L778)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> This line has one of the bugs I found: if Get-MembersAsPrincipals only returns a single record it won't be an array and so the .Count property used later on won't exist. I resolved by wrapping the cmdlet with an @( ) to explicitly cast to an array.
</details>
Done.

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 2303 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL7919UmmNduOCnKbl:-KNY3NiepSpWEtNn7rZ3:-499146009) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L2303)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> I found a bug in this line: ThrowInvalidArgumentError does not exist - should be:
> ```powershell
> New-InvalidArgumentException `
>             -ArgumentName 'GroupNameHasInvalidCharacter' `
>             -Message ($LocalizedData.InvalidGroupName `
>                 -f $GroupName, [String]::Join(' ', $invalidCharacters))
> ```
</details>
Done.

---

*[DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1, line 2320 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-KNL7RwDLFTmsPiU_RFC:-KNY3O6oevekZoDeF27V:-499146009) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/5f3c1715e24dde7c454d4fb53ad0b2c6349938a3/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L2320)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> I found a bug in this line: ThrowInvalidArgumentError does not exist - should be:
> ```powershell
> New-InvalidArgumentException `
>             -ErrorId 'GroupNameHasOnlyWhiteSpacesAndDots' `
>             -Message ($LocalizedData.InvalidGroupName `
>                 -f $GroupName, [String]::Join(' ', $invalidCharacters))
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182)*

**Comment by kwirkykat** [comment]
@PlagueHO Is this good to go?

**Comment by PlagueHO** [comment]
Hi @kwirkykat, sorry,  I forgot to do this last night. I'll review when I get to work in about an hour. Sorry about the delay.

**Comment by PlagueHO** [comment]
:lgtm: Thanks @KwirkyKat!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/182#-:-KNcqFBjbcilgWgtXfpl:-163260482)*

**Pull request merged**
