### PR TITLE
Add support for dynamically selecting SSL certificate for Pull Server

### PR DESCRIPTION
**Pull request by mgreenegit**

### CODE REVIEW

**Comment by vors** [comment]
Please, update baseline from our dev branch and resolve merge conflicts: `git pull origin dev`.

**Comment by mgreenegit** [comment]
Looks good at this point.

**Comment by rayhayes** [comment]
This looks good to me.

**Comment by KarolKaczmarek** [comment]
Thanks @mgreenegit for this significant contribution.
We are ready to accept it, however it took a while to review it and there were some conflicting changes introduced in the meantime. Could you please resolve them before we are able to merge?

**Comment by TravisEz13** [comment]
@mgreenegit I resolved the merge conflicts and saved the results [here](https://github.com/TravisEz13/xPSDesiredStateConfiguration/tree/mgreengit-master)

but it had [test failures](https://ci.appveyor.com/project/TravisEz13/xpsdesiredstateconfiguration/build/1.0.2)

**Comment by TravisEz13** [comment]
If there is no update of the pull request within 7 days, we will close the pull request.  After that, if you have an update, feel free to reopen the pull request or a new pull request.

**Comment by TravisEz13** [comment]
Closing because the pull request has not been updated for feedback given for 21 days.  Once you update the code, please feel free to reopen the pull request.  Thanks, Travis.

**Pull request closed without merging**
