### PR TITLE
xService update service Path

### PR DESCRIPTION
**Pull request by CtrlC-Root**
* Modify `Test-TargetResource` to compare binary paths.
* Add new `WriteBinaryProperties` cmdlet to update the binary path.
* Modify `Set-TargetResource` to call `WriteBinaryProperties` and restart the service if required.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/73)

### CODE REVIEW

**Comment by CtrlC-Root** [comment]
This pull request fixes #72.

**Comment by CtrlC-Root** [comment]
Actually, hang on, I have to make one small fix.

**Comment by CtrlC-Root** [comment]
Ok, that's better. Not it properly restarts services.

**Comment by CtrlC-Root** [comment]
Not sure what caused the automated tests to fail this last time. Seems like it couldn't download and install pester?

**Comment by CtrlC-Root** [comment]
@KarolKaczmarek Do you think you could trigger the tests to run again? I suspect they failed due to a transient issue. Also, assuming they pass, is there anything else I can do to help get this pull request merged?

**Comment by TravisEz13** [comment]
It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  
Add a unit test that the new property is passed appropriately to stopservice
add tests for the new function you added

**Comment by TravisEz13** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.psm1, line 14 \[r3\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/73#-KEO4O_M1hxv2EKbEsvj:-KEO4O_M1hxv2EKbEsvk:959174943) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/7e29c3f49837a1856dcf6fd3ba82c94a84497bad/DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.psm1#L14)):*
It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

Suggestion: Base the tests on the [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/73)*

**Comment by kwirkykat** [comment]
@CtrlC-Root Any updates here?

**Comment by CtrlC-Root** [comment]
@kwirkykat I'm not very familiar with Pester and it looks like there are no existing unit tests for the `xServiceResource` so I would have to set them up from scratch. I realize this is no substitute for runnable tests but this code has been working in production without issue for months. Unfortunately, that's a double edged sword, because it means I doubt I'll be given the time to come back and add unit tests to this anytime soon. I'd be willing to resolve the merge conflicts, and if someone is kind enough to contribute some basic unit tests for this resource, I could add one or two on top of them for the changes I've made.

**Comment by kwirkykat** [comment]
@CtrlC-Root It looks like we have a couple in-box tests for Service. I can port them as soon as I'm done porting our newly-open-sourced resources over.

**Comment by kwirkykat** [comment]
@CtrlC-Root It looks like xService needs a rather large overhaul to merge with the existing in-box Service resource and its tests. I'd prefer to merge this PR in first. If you can resolve the merge conflicts (I'm guessing it's the README that's complaining), I can make an exception for the testing and merge this in.

**Comment by CtrlC-Root** [comment]
@kwirkykat Weird, I saw something fail in the AppVeyor tests but it says the build was successful. In any case, the conflict has been resolved.

**Comment by kwirkykat** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/73#-:-KKKAzinh6U84NrBCh-p:1417088721)*

**Comment by kwirkykat** [comment]
@CtrlC-Root Thanks! The error is from the new xServiceSet which was just ported from the in-box version. It expects the in-box Service resource which I'm about to merge in.

**Comment by kwirkykat** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/73)*

**Pull request merged**
