### PR TITLE
Add NT Authority and NT Service to list of local scopes and add integration tests

### LINKED ISSUE #250: xGroup - Error if group contains "NT AUTHORITY" members
If a group that should be modified / monitored by DSC xGroup resource contains a member with "NT AUTHORIY" principal, an exception is thrown.

Repo: 
1. create a local group
2. add members "NT AUTHORIY\SYSTEM" or "NT AUTHORITY\NETWORK SERVICE"
3. create and apply a simple xGroup Configuration to edit the group
(e.g.  xGroup xIisUsrs {
            GroupName = "TestGroup";
            MembersToInclude = "DOMAIN\username";
            PsDscRunAsCredential = $credential;
            Credential = $credential;
        }

Results in:
Exception calling ".ctor" with "4" argument(s): "Server names cannot contain a space character."
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

The error is inside the Get-MembersAsPrincipals function. The member object can not be used to construct a DirectoryEntry
$memberDirectoryEntry = New-Object -TypeName 'System.DirectoryServices.DirectoryEntry' -ArgumentList @( $groupDirectoryMember ) # <-- line 1525 in current master

### PR DESCRIPTION
**Pull request by kwirkykat**
This is the same fix that is in https://github.com/PowerShell/PSDscResources/pull/29 but also with NT Service (which should also be added to PSDscResources in a moment).
This fixes #250 and #288

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/314)

### CODE REVIEW

**Comment by mbreakey3** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/MSFT_xGroupResource_NoMembers.config.ps1, line 25 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/314#-Kc0_WI-62b1ys82ourW:-Kc0_WI-62b1ys82ourX:bt7negv) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/3a19ea55c9b67f9d27f202b69be0ed86ac318563/Tests/Integration/MSFT_xGroupResource_NoMembers.config.ps1#L25)):*
> ```PowerShell
>     Import-DscResource -ModuleName 'xPSDesiredStateConfiguration'
> 
>     xGroup xGroup1
> ```

I know we don't totally have a hard naming rule for the configurations - some start with x, some don't, etc. - but to follow the other group examples, I would change this to: xGroup Group3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/314)*

**Comment by kwirkykat** [comment]
@mbreakey3 After talking to Travis, I also added BuiltIn to the list of local scopes

**Comment by kwirkykat** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/MSFT_xGroupResource_NoMembers.config.ps1, line 25 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/314#-Kc0_WI-62b1ys82ourW:-Kc0gwGR7C0xrQ9cDWWN:b-896fix) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/3a19ea55c9b67f9d27f202b69be0ed86ac318563/Tests/Integration/MSFT_xGroupResource_NoMembers.config.ps1#L25)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

I know we don't totally have a hard naming rule for the configurations - some start with x, some don't, etc. - but to follow the other group examples, I would change this to: xGroup Group3
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/314)*

**Comment by mbreakey3** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/314)*

**Comment by mbreakey3** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/314#-:-Kc3tSHLhRp2RYO7m3A0:bnfp4nl)*

**Pull request merged**
