### PR TITLE
Latest demo

### PR DESCRIPTION
**Pull request by BerheAbrha**
Added two cmdlets to publish module and configuration from a pipeline ModuleInfo and FileInfo object. The cmdlets will also figure out the location of the module and configuration repositories of the pull server from web.config.

-  Publishing module(s) :-  Get-Module 'xWebAdministration' -ListAvailable | pmp
- Publishing a configuration(s) :-  Dir c:\*mof  | pcp

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/102)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCPullServerSetup/PublishModulesAndMofsToPullServer.psm1, line 165 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/102#-KEmr1YRiQ70-cMhzA1F:-KEmr1YRiQ70-cMhzA1G:-219289958) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/fb5bfeb81ee2a0fbaca9941618fc72a6fea03ff4/DSCPullServerSetup/PublishModulesAndMofsToPullServer.psm1#L165)):*
Talk to me offline on how to resolve the cla-required

---

*[DSCPullServerSetup/PublishModulesAndMofsToPullServer.psm1, line 166 \[r1\]](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/102#-KEmrSrdiA7xgqMtOUJE:-KEmrSrdiA7xgqMtOUJF:-1203691781) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/fb5bfeb81ee2a0fbaca9941618fc72a6fea03ff4/DSCPullServerSetup/PublishModulesAndMofsToPullServer.psm1#L166)):*

Please include a summary of changes in an unreleased version change per the [contribution guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#lifecycle-of-a-pull-request)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/102)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/102)*

**Comment by TravisEz13** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/102#-:-KErW7dVFFxS7ctR5Mjp:1417088721)*

**Comment by BerheAbrha** [comment]
Thanks Travis!

**Pull request merged**
