### PR TITLE
xPackage: Fix misnamed variable

### LINKED ISSUE #449: xPackage: The variable '$Localized' cannot be retrieved because it has not been set.
#### Details of the scenario you tried and the problem that is occurring
Trying to install a package and got this error. I forgot to include two backward slashes (it's a network location) so it is expected to have an error - but this ended with an unexpected different error message because there's a misnamed variable.

#### Verbose logs showing the problem
```
VERBOSE: [CHWS01]: LCM:  [ Start  Resource ]  [[xPackage]NetFx472]
VERBOSE: [CHWS01]: LCM:  [ Start  Test     ]  [[xPackage]NetFx472]
VERBOSE: [CHWS01]:                            [[xPackage]NetFx472] The path extension was .exe
VERBOSE: [CHWS01]: LCM:  [ End    Test     ]  [[xPackage]NetFx472]  in 0.1720 seconds.
C:\BootStrap\BootStrap.ps1 : PowerShell DSC resource MSFT_xPackageResource  failed to execute Test-TargetResource
functionality with error message: The variable '$Localized' cannot be retrieved because it has not been set.
At line:1 char:1
+ .\bootstrap.ps1
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,BootStrap.ps1
```

#### Suggested solution to the issue
Change: 
Write-Verbose -Message ($Localized.TheUriSchemeWasUriScheme -f $uri.Scheme)
To:
Write-Verbose -Message ($localizedData.TheUriSchemeWasUriScheme -f $uri.Scheme)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
                xPackage 'NetFx472' {
                    Name = 'NetFx472'
                    Path = "$($domainController.$($node.DomainName))\Resources\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
                    ProductId = ''
                    InstalledCheckRegKey = "SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full"
                    InstalledCheckRegValueName = "Release"
                    InstalledCheckRegValueData = "461814"
                    Arguments = "/q"
                    DependsOn  = '[WindowsFeatureSet]All', '[Computer]Rename'
                }
```

#### The operating system the target node is running
Windows Server 2012

#### Version and build of PowerShell the target node is running

WMF 5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by codykonior**
#### Pull Request (PR) description
There's a misnamed variable which causes an error during certain error output.

#### This Pull Request (PR) fixes the following issues
- Fixes #449

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/450)

### CODE REVIEW

**Comment by codykonior** [comment]
Try to trigger AppVeyor rebuild

**Comment by codykonior** [comment]
@johlju What's the plan here? It seems the build has been failing on multiple PRs for a while now.

**Comment by johlju** [comment]
Sorry have been very busy with the day job. :/ Will be back at it as soon as I can.

**Comment by johlju** [comment]
See the issue https://github.com/Crypt32/PSPKI/issues/56. We have to wait for the PSPKI module to be rereleased.

**Comment by codykonior** [comment]
Thanks so much for letting me know. Will wait ^^

**Comment by codykonior** [comment]
All the failed tests are unrelated in xArchive.

**Comment by PlagueHO** [comment]
I've fixed the integration tests so hopefully this one will be able to be completed.

**Comment by mhendric** [comment]
Hi @codykonior , I still recommend changing $localizedData to $script:localizedData. Other than that, I think this just needs a rebase per the below article and it should be ready to go. Thanks for your contribution and your patience on this!

https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by mhendric** [comment]
FYI, I went ahead and updated this one myself with my only suggested code fix. @PlagueHO or @johlju , would one of you be able to give this one another review? Should be an easy one.

**Comment by PlagueHO** [comment]
Hi @codykonior - can you fix the merge conflicts (again, sorry). But in this case you actually need to move the changed entry from the README.MD into the CHANGELOG.MD due to this now being split out.

**Comment by codykonior** [comment]
Trying to rebase just made everything 100,000x worse.

**Comment by codykonior** [comment]
Aborting this PR, I can't fix this.

**Pull request closed without merging**
