### PR TITLE
Moving the Environment Resource to Open-Source xEnvironment

### PR DESCRIPTION
**Pull request by kwirkykat**
xEnvironment is an open-source copy of the in-box Environment resource.
Tests and an example have been added.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/147)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Remaining test failure is due to PSSA errors in existing resources.
#129 and #131 are already filed to address these issues.

**Comment by PlagueHO** [comment]
@kwirkykat - I fixed all the PSSA errors with PR #123. So once that is merged you should be able to trigger a dummy commit on this PR to resolve the AppVeyor failure.

**Comment by vors** [comment]
@PlagueHO @kwirkykat should be able to trigger re-build without dummy commit, directly from appveyor.
image

I tried to figure out how to enable it for non-powershell org members, but AppVeyor doesn't support it out-of-the-box http://help.appveyor.com/discussions/questions/2288-how-i-can-allow-anybody-trigger-a-re-build-on-a-public-project

**Comment by PlagueHO** [comment]
@Vors - no worries :smile: I'm OK with doing dummy commits every now and then. I forgot @kwirkykat could issue them directly.

**Pull request merged**
