### PR TITLE
xRegistry: Update test helper per previous PR comments

### PR DESCRIPTION
**Pull request by kwirkykat**
This PR addresses the late comments to the Registry test helper made in #226.
@zjalali Please review.

Since this only modifies the Registry test helper I will not update the README.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/234)

### CODE REVIEW

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 366 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234#-KRaA60SxDPqczJVEAbM:-KRaA60SxDPqczJVEAbN:ba54nym) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/77c8a54d150f8fa896a6583e4d1663c043902464/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L366)):*
> $mappingKey = $null
>  
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
>         # Find the abbreviated key that goes with the given registry drive path
>         foreach ($key in $registryDriveRootMappings.Keys)
>         {
>             if ($registryDriveRootMappings[$key] -ieq $driveName)
>             {
>                 $mappingKey = $key
>                 break
>             }
>         }
</details>


I think you can get rid of this section. I don't see any need for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234)*

**Comment by zjalali** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234)*

**Comment by kwirkykat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 366 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234#-KRaA60SxDPqczJVEAbM:-KRe6SSJ3bl7eODcGLED:b54g1wi) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/77c8a54d150f8fa896a6583e4d1663c043902464/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L366)):*
<details><summary><i>Previously, zjalali (Zia Jalali) wrote…</i></summary>
> > $mappingKey = $null
> >  
> >         # Find the abbreviated key that goes with the given registry drive path
> >         foreach ($key in $registryDriveRootMappings.Keys)
> >         {
> >             if ($registryDriveRootMappings[$key] -ieq $driveName)
> >             {
> >                 $mappingKey = $key
> >                 break
> >             }
> >         }
> 
> 
> I think you can get rid of this section. I don't see any need for that.
</details>
This section is here in case someone decides to write a test that uses the unabbreviated drive name (e.g. HKEY_LOCAL_MACHINE) which would be completely valid.

This specific part of the function finds the abbreviation (e.g. HKLM) from the hashtable so that both the abbreviated and unabbreviated names can be passed to New-PSDrive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234)*

**Comment by zjalali** [comment]
*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 366 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234#-KRaA60SxDPqczJVEAbM:-KRt0MqCzAUJDX4G0fbe:bmdlu9i) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/77c8a54d150f8fa896a6583e4d1663c043902464/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L366)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> This section is here in case someone decides to write a test that uses the unabbreviated drive name (e.g. HKEY_LOCAL_MACHINE) which would be completely valid.
> 
> This specific part of the function finds the abbreviation (e.g. HKLM) from the hashtable so that both the abbreviated and unabbreviated names can be passed to New-PSDrive.
</details>
We are not using the results of this section any more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234)*

**Comment by zjalali** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1, line 366 at r1](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234#-KRaA60SxDPqczJVEAbM:-KS2YnqwIZ-PMfSHJT4i:bgh7qjd) ([raw file](https://github.com/powershell/xpsdesiredstateconfiguration/blob/77c8a54d150f8fa896a6583e4d1663c043902464/Tests/Unit/MSFT_xRegistryResource.TestHelper.psm1#L366)):*
> -Name $mappingKey
Please ignore my last comment. Since you are passing the `$mappingKey` to `New-PSDrive`  you need to keep the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234)*

**Comment by zjalali** [comment]
:lgtm

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/234#-:-KRaAP1YTzw7ylFxgykc:b-8eqf7b)*

**Pull request merged**
