### PR TITLE
Tests\Unit\MSFT_xMsiPackage.Tests.ps1: Fixes issue where tests fail if executed from a drive other than C:

### LINKED ISSUE #573: Tests\Unit\MSFT_xMsiPackage.Tests.ps1: Test broken when executed from a drive other than C:
#### Details of the scenario you tried and the problem that is occurring
Test 'Failure while creating the file stream object to download to' currently fails when tests are run and the module is located on a drive other than C:. It runs fine from any location on C:.

#### Verbose logs showing the problem
```
      Context Failure while creating the file stream object to download to
        [-] Should throw an error for not being able to open the destination file to write to 127ms
          Expected an exception, with message 'Could not open the file C:\ProgramData\Microsoft\Windows\PowerShell\Configuration\BuiltinProvCache\MSFT_xMsiPa
ckage\C:\ for writing' to be thrown, but the message was 'System.InvalidOperationException: Could not open the file C:\ProgramData\Microsoft\Windows\PowerShe
ll\Configuration\BuiltinProvCache\MSFT_xMsiPackage\D:\ for writing ---> System.Management.Automation.RuntimeException: ScriptHalted
             --- End of inner exception stack trace ---'. from D:\GitHub\xPSDesiredStateConfiguration-ConsolidatePackageFunctions\xPSDesiredStateConfiguratio
n\DSCResources\CommonResourceHelper.psm1:171 char:5
              +     throw $errorRecordToThrow
              +     ~~~~~~~~~~~~~~~~~~~~~~~~~
          329:             { $null = Set-TargetResource @SetTargetResourceParameters } | Should -Throw -ExpectedMessage $ErrorMessage
          at <ScriptBlock>, D:\GitHub\xPSDesiredStateConfiguration-ConsolidatePackageFunctions\xPSDesiredStateConfiguration\Tests\CommonTestHelper.psm1: line
 329
```
#### Suggested solution to the issue
TBD

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
invoke-pester .\MSFT_xMsiPackage.Tests.ps1

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Tests\Unit\MSFT_xMsiPackage.Tests.ps1: Fixes issue where tests fail if executed from a drive other than C:

#### This Pull Request (PR) fixes the following issues
-Fixes #573 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as
      appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/578)

### CODE REVIEW

**Comment by mhendric** [comment]
@PlagueHO , I'll leave this one for you to merge since it's my PR and someone else did the code review. Thanks.

**Comment by PlagueHO** [comment]
Hi @ykuijs - could you resolve conflicts?

**Comment by mhendric** [comment]
@PlagueHO , I'll resolve the conflicts since it's my PR (@ykuijs just did the review). Thanks.

**Comment by PlagueHO** [comment]
@mhendric - doh! It was a long week at work :cry:

**Pull request merged**
