### PR TITLE
Fixes Issue #257: Changed call to Get-WmiObject to be Get-CimInstance to be compatibile…

### PR DESCRIPTION
**Pull request by NickMRamirez**
… with Windows Nano.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/258)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Still curious whether this change fully fixes this resource on Nano, but even if not this change should be made anyways.
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/258#-:-KUsqApLu7QMwjDcv2ub:b-rz05yg)*

**Comment by kwirkykat** [comment]
@mbreakey3 Watch out. This is a tiny change but will probably trigger a merge with your code.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpsdesiredstateconfiguration/258#-:-KUsqSwBBN9ftTqe85ij:b-4gn1df)*

**Comment by NickMRamirez** [comment]
Even though this has been merged...I'm still learning the ropes about how to test Powershell modules. I have a Nano VM. Is there a way to replace the default module with this updated one? For testing.

**Comment by mbreakey3** [comment]
You can clone whichever branch you want on your local machine, is that what you mean? You can then copy it into your programs file (where powershell modules are downloaded by default) and delete any other copies. It should then run as if that version were the one installed.

**Comment by mbreakey3** [comment]
However, I don't believe there's a way to change the inbox DSC modules. You'll have to run any testing through your cloned module.

**Comment by kwirkykat** [comment]
@NickMRamirez This module does not replace the default in-box module. All the resources here have different names (with the 'x' prefix) than the in-box resources, so you can use this module just as you would use any custom DSC resource module. Only PSDscResources overwrites the default in-box resources. This particular resource is not yet included in PSDscResources though.

If you have a previous version of xPSDesiredStateConfiguration installed, you will need to use ```Remove-Module``` to uninstall it.

To install the module, copy it into the ```C:\Windows\System32\WindowsPowerShell\v1.0\Modules``` folder or the ```C:\Program Files\WindowsPowerShell\Modules``` folder. Make sure one if these paths is defined in your ```$env:PSModulePath``` variable. Then just run your configuration/tests. This should import the module automatically from the correct folder. You can explicitly call ```Import-Module xPSDesiredStateConfiguration``` or ```Import-Module``` with the specific path to the module folder.

**Comment by NickMRamirez** [comment]
Thanks. I was able to test this change on Nano server by doing the following:

1. Copy the C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration to another directory
2. Call Uninstall-Module on xPSDesiredStateConfiguration
3. Make changes to the module and then copy it back to the C:\Program Files... directory

Then, the error about using Get-WmiObject was gone.

I get a new error on Nano, but that's not related and I'll do some research on it separately:

> PowerShell DSC resource MSFT_xWindowsFeature  failed to execute Test-TargetResource functionality with error message: Installing roles and features using PowerShell Desired State Configuration is supported only on Server SKU's. It is not supported on Client SKU.

**Comment by kwirkykat** [comment]
@NickMRamirez Yeah. That's more what I expected. WindowsFeature is supposedly not compatible with Nano server because there are some types missing/the types don't have all the full properties on Nano. If you can figure out how to get it to work on Nano, I would love to hear it, but as it is now DSC is not supporting WindowsFeature on Nano. Sorry 😢

**Pull request merged**
